(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/Loader.svelte":
/*!**************************************!*\
  !*** ./src/components/Loader.svelte ***!
  \**************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/Loader.svelte generated by Svelte v3.22.2 */


const file = "src/components/Loader.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-145waro-style";
	style.textContent = ".spinner.svelte-145waro.svelte-145waro{width:50px;height:40px;text-align:center;font-size:10px}.spinner.svelte-145waro>div.svelte-145waro{background-color:white;height:100%;width:6px;display:inline-block;animation:svelte-145waro-sk-stretchdelay 1.2s infinite ease-in-out}.spinner.svelte-145waro .rect2.svelte-145waro{animation-delay:-1.1s}.spinner.svelte-145waro .rect3.svelte-145waro{animation-delay:-1.0s}.spinner.svelte-145waro .rect4.svelte-145waro{-webkit-animation-delay:-0.9s;animation-delay:-0.9s}.spinner.svelte-145waro .rect5.svelte-145waro{animation-delay:-0.8s}@keyframes svelte-145waro-sk-stretchdelay{0%,40%,100%{transform:scaleY(0.4)}20%{transform:scaleY(1.0)}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTG9hZGVyLnN2ZWx0ZSIsInNvdXJjZXMiOlsiTG9hZGVyLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyIgICAgICBcbiAgICAgIDxkaXYgY2xhc3M9XCJzcGlubmVyXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyZWN0MVwiPjwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicmVjdDJcIj48L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJlY3QzXCI+PC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyZWN0NFwiPjwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicmVjdDVcIj48L2Rpdj5cbiAgICAgIDwvZGl2PlxuXG48c3R5bGU+XG4gIC5zcGlubmVyIHtcbiAgICB3aWR0aDogNTBweDtcbiAgICBoZWlnaHQ6IDQwcHg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGZvbnQtc2l6ZTogMTBweDtcbiAgfVxuXG4gIC5zcGlubmVyID4gZGl2IHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcbiAgICBoZWlnaHQ6IDEwMCU7XG4gICAgd2lkdGg6IDZweDtcbiAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gICAgYW5pbWF0aW9uOiBzay1zdHJldGNoZGVsYXkgMS4ycyBpbmZpbml0ZSBlYXNlLWluLW91dDtcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0MiB7XG4gICAgYW5pbWF0aW9uLWRlbGF5OiAtMS4xcztcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0MyB7XG4gICAgYW5pbWF0aW9uLWRlbGF5OiAtMS4wcztcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0NCB7XG4gICAgLXdlYmtpdC1hbmltYXRpb24tZGVsYXk6IC0wLjlzO1xuICAgIGFuaW1hdGlvbi1kZWxheTogLTAuOXM7XG4gIH1cblxuICAuc3Bpbm5lciAucmVjdDUge1xuICAgIGFuaW1hdGlvbi1kZWxheTogLTAuOHM7XG4gIH1cblxuXG4gIEBrZXlmcmFtZXMgc2stc3RyZXRjaGRlbGF5IHtcbiAgICAwJSwgNDAlLCAxMDAlIHtcbiAgICAgIHRyYW5zZm9ybTogc2NhbGVZKDAuNCk7XG4gICAgfSAgMjAlIHtcbiAgICAgIHRyYW5zZm9ybTogc2NhbGVZKDEuMCk7XG4gICAgfVxuICB9XG48L3N0eWxlPiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFVRSxRQUFRLDhCQUFDLENBQUMsQUFDUixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osVUFBVSxDQUFFLE1BQU0sQ0FDbEIsU0FBUyxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUVELHVCQUFRLENBQUcsR0FBRyxlQUFDLENBQUMsQUFDZCxnQkFBZ0IsQ0FBRSxLQUFLLENBQ3ZCLE1BQU0sQ0FBRSxJQUFJLENBQ1osS0FBSyxDQUFFLEdBQUcsQ0FDVixPQUFPLENBQUUsWUFBWSxDQUNyQixTQUFTLENBQUUsOEJBQWUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLFdBQVcsQUFDdEQsQ0FBQyxBQUVELHVCQUFRLENBQUMsTUFBTSxlQUFDLENBQUMsQUFDZixlQUFlLENBQUUsS0FBSyxBQUN4QixDQUFDLEFBRUQsdUJBQVEsQ0FBQyxNQUFNLGVBQUMsQ0FBQyxBQUNmLGVBQWUsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFFRCx1QkFBUSxDQUFDLE1BQU0sZUFBQyxDQUFDLEFBQ2YsdUJBQXVCLENBQUUsS0FBSyxDQUM5QixlQUFlLENBQUUsS0FBSyxBQUN4QixDQUFDLEFBRUQsdUJBQVEsQ0FBQyxNQUFNLGVBQUMsQ0FBQyxBQUNmLGVBQWUsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFHRCxXQUFXLDhCQUFnQixDQUFDLEFBQzFCLEVBQUUsQ0FBRSxHQUFHLENBQUUsSUFBSSxBQUFDLENBQUMsQUFDYixTQUFTLENBQUUsT0FBTyxHQUFHLENBQUMsQUFDeEIsQ0FBQyxBQUFFLEdBQUcsQUFBQyxDQUFDLEFBQ04sU0FBUyxDQUFFLE9BQU8sR0FBRyxDQUFDLEFBQ3hCLENBQUMsQUFDSCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div5;
	let div0;
	let t0;
	let div1;
	let t1;
	let div2;
	let t2;
	let div3;
	let t3;
	let div4;

	const block = {
		c: function create() {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			this.h();
		},
		l: function claim(nodes) {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "rect1 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 2, 8, 43);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "rect2 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 3, 8, 77);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "rect3 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 4, 8, 111);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "rect4 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 5, 8, 145);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "rect5 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 6, 8, 179);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "spinner svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 1, 6, 13);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div5, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div4);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div5);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Loader> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Loader", $$slots, []);
	return [];
}

class Loader extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-145waro-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Loader",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Loader);

/***/ }),

/***/ "./src/components/World.svelte":
/*!*************************************!*\
  !*** ./src/components/World.svelte ***!
  \*************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/World.svelte generated by Svelte v3.22.2 */


const file = "src/components/World.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-zw5xux-style";
	style.textContent = "article.svelte-zw5xux{background-color:rgba(4, 4, 4, .6);padding:1rem}.white.svelte-zw5xux{color:white}.green.svelte-zw5xux{color:green}.red.svelte-zw5xux{color:red}.orange.svelte-zw5xux{color:orange}a.svelte-zw5xux{text-decoration:none}a.svelte-zw5xux:hover{background-color:white}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiV29ybGQuc3ZlbHRlIiwic291cmNlcyI6WyJXb3JsZC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cblxuZXhwb3J0IGxldCBpdGVtXG5leHBvcnQgbGV0IHNlZ21lbnRcblxuPC9zY3JpcHQ+XG5cbjxhIHJlbD1wcmVmZXRjaCBhcmlhLWN1cnJlbnQ9J3tzZWdtZW50ID09PSBcImNvdW50cnlcIiA/IFwicGFnZVwiIDogdW5kZWZpbmVkfScgaHJlZj0nY291bnRyeSc+XG5cdDxhcnRpY2xlPlxuXHRcdDxoMSBjbGFzcz1cIndoaXRlXCI+e2l0ZW0uQ291bnRyeX08L2gxPlxuXHRcdDxwIGNsYXNzPVwib3JhbmdlXCI+VG90YWwgaW5mZWN0ZWQ6IHtpdGVtLlRvdGFsQ29uZmlybWVkLnRvU3RyaW5nKCkucmVwbGFjZSgvXFxCKD89KFxcZHszfSkrKD8hXFxkKSkvZywgXCIsXCIpfTwvcD5cblx0XHQ8cCBjbGFzcz1cInJlZFwiPlRvdGFsIGRlYXRoczoge2l0ZW0uVG90YWxEZWF0aHMudG9TdHJpbmcoKS5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCBcIixcIil9PC9wPlxuXHRcdDxwIGNsYXNzPVwiZ3JlZW5cIj5Ub3RhbCByZWNvdmVyZWQ6IHtpdGVtLlRvdGFsUmVjb3ZlcmVkLnRvU3RyaW5nKCkucmVwbGFjZSgvXFxCKD89KFxcZHszfSkrKD8hXFxkKSkvZywgXCIsXCIpfTwvcD5cblx0PC9hcnRpY2xlPlx0XHRcbjwvYT5cblxuXG48c3R5bGU+XG5cdGFydGljbGUge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHJnYmEoNCwgNCwgNCwgLjYpO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdH1cblx0LndoaXRlIHtcblx0XHRjb2xvcjogd2hpdGU7XG5cdH1cblx0LmdyZWVuIHtcblx0XHRjb2xvcjogZ3JlZW47XG5cdH1cblx0LnJlZCB7XG5cdFx0Y29sb3I6IHJlZDtcblx0fVxuXHQub3JhbmdlIHtcblx0XHRjb2xvcjogb3JhbmdlO1xuXHR9XG4gICAgYSB7XG5cdCAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7XG5cdH1cblxuXHRhOmhvdmVyIHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcblx0fVxuXG48L3N0eWxlPiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFrQkMsT0FBTyxjQUFDLENBQUMsQUFDUixnQkFBZ0IsQ0FBRSxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUNuQyxPQUFPLENBQUUsSUFBSSxBQUNkLENBQUMsQUFDRCxNQUFNLGNBQUMsQ0FBQyxBQUNQLEtBQUssQ0FBRSxLQUFLLEFBQ2IsQ0FBQyxBQUNELE1BQU0sY0FBQyxDQUFDLEFBQ1AsS0FBSyxDQUFFLEtBQUssQUFDYixDQUFDLEFBQ0QsSUFBSSxjQUFDLENBQUMsQUFDTCxLQUFLLENBQUUsR0FBRyxBQUNYLENBQUMsQUFDRCxPQUFPLGNBQUMsQ0FBQyxBQUNSLEtBQUssQ0FBRSxNQUFNLEFBQ2QsQ0FBQyxBQUNFLENBQUMsY0FBQyxDQUFDLEFBQ0YsZUFBZSxDQUFFLElBQUksQUFDekIsQ0FBQyxBQUVELGVBQUMsTUFBTSxBQUFDLENBQUMsQUFDUixnQkFBZ0IsQ0FBRSxLQUFLLEFBQ3hCLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let a;
	let article;
	let h1;
	let t0_value = /*item*/ ctx[0].Country + "";
	let t0;
	let t1;
	let p0;
	let t2;
	let t3_value = /*item*/ ctx[0].TotalConfirmed.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t3;
	let t4;
	let p1;
	let t5;
	let t6_value = /*item*/ ctx[0].TotalDeaths.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t6;
	let t7;
	let p2;
	let t8;
	let t9_value = /*item*/ ctx[0].TotalRecovered.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t9;
	let a_aria_current_value;

	const block = {
		c: function create() {
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("article");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total infected: ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total deaths: ");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t6_value);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total recovered: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t9_value);
			this.h();
		},
		l: function claim(nodes) {
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "A", {
				rel: true,
				"aria-current": true,
				href: true,
				class: true
			});

			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(a_nodes, "ARTICLE", { class: true });
			var article_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(article);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, t0_value);
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Total infected: ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, t3_value);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Total deaths: ");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, t6_value);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "Total recovered: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, t9_value);
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			article_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "white svelte-zw5xux");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 9, 2, 162);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "orange svelte-zw5xux");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 10, 2, 202);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "red svelte-zw5xux");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 11, 2, 313);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p2, "class", "green svelte-zw5xux");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 12, 2, 416);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(article, "class", "svelte-zw5xux");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(article, file, 8, 1, 150);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "rel", "prefetch");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "aria-current", a_aria_current_value = /*segment*/ ctx[1] === "country" ? "page" : undefined);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "country");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "svelte-zw5xux");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 7, 0, 57);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, a, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, article);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t9);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*item*/ 1 && t0_value !== (t0_value = /*item*/ ctx[0].Country + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, t0_value);
			if (dirty & /*item*/ 1 && t3_value !== (t3_value = /*item*/ ctx[0].TotalConfirmed.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, t3_value);
			if (dirty & /*item*/ 1 && t6_value !== (t6_value = /*item*/ ctx[0].TotalDeaths.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t6, t6_value);
			if (dirty & /*item*/ 1 && t9_value !== (t9_value = /*item*/ ctx[0].TotalRecovered.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t9, t9_value);

			if (dirty & /*segment*/ 2 && a_aria_current_value !== (a_aria_current_value = /*segment*/ ctx[1] === "country" ? "page" : undefined)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "aria-current", a_aria_current_value);
			}
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(a);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { item } = $$props;
	let { segment } = $$props;
	const writable_props = ["item", "segment"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<World> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("World", $$slots, []);

	$$self.$set = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
		if ("segment" in $$props) $$invalidate(1, segment = $$props.segment);
	};

	$$self.$capture_state = () => ({ item, segment });

	$$self.$inject_state = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
		if ("segment" in $$props) $$invalidate(1, segment = $$props.segment);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [item, segment];
}

class World extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-zw5xux-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { item: 0, segment: 1 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "World",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*item*/ ctx[0] === undefined && !("item" in props)) {
			console.warn("<World> was created without expected prop 'item'");
		}

		if (/*segment*/ ctx[1] === undefined && !("segment" in props)) {
			console.warn("<World> was created without expected prop 'segment'");
		}
	}

	get item() {
		throw new Error("<World>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set item(value) {
		throw new Error("<World>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	get segment() {
		throw new Error("<World>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set segment(value) {
		throw new Error("<World>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (World);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/Loader.svelte */ "./src/components/Loader.svelte");
/* harmony import */ var _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/World.svelte */ "./src/components/World.svelte");
/* src/routes/index.svelte generated by Svelte v3.22.2 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1lqfd2b-style";
	style.textContent = "div.svelte-1lqfd2b{display:grid;background-color:#1b1b30;width:100vw;justify-content:center}section.svelte-1lqfd2b{display:grid;grid-template-columns:repeat(auto-fill, minmax(200px, 1fr));grid-template-columns:repeat(5, 1fr);justify-content:center;gap:2rem;margin:auto;width:80vw}.sort.svelte-1lqfd2b{height:10vh;display:grid;grid-template-columns:100px 100px 100px 100px;gap:10px;width:90vw;margin:auto;justify-content:center;padding:1rem}.button.svelte-1lqfd2b{height:30px;background-color:indigo;color:white;outline:none}.active.svelte-1lqfd2b{background-color:rgba(4, 4, 4, .6)}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+Q29yb25hIGluZm9ybWF0aW9uPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxzY3JpcHQ+XG5cdGltcG9ydCB7IG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCJcblx0aW1wb3J0IExvYWRlciBmcm9tIFwiLi4vY29tcG9uZW50cy9Mb2FkZXIuc3ZlbHRlXCJcblx0aW1wb3J0IFdvcmxkIGZyb20gXCIuLi9jb21wb25lbnRzL1dvcmxkLnN2ZWx0ZVwiXG5cblxuXHRsZXQgd29ybGQgPSBbXVxuXG5cbiAgICBvbk1vdW50KCBhc3luYyAoKSA9PiB7XG5cdFx0YXdhaXQgZmV0Y2goYGh0dHBzOi8vYXBpLmNvdmlkMTlhcGkuY29tL3N1bW1hcnlgKVxuXHRcdC50aGVuKCByZXNwb25zZSA9PiByZXNwb25zZS5qc29uKCkgKVxuICAgICAgICAudGhlbigganNvbiA9PiB7XG5cdFx0XHQvLyBXb3JsZFxuICAgICAgICAgICAgd29ybGQgPSBqc29uLkNvdW50cmllc1xuICAgICAgICB9XG4gICAgICAgICkuY2F0Y2goKGVycikgPT4gY29uc29sZS5sb2coZXJyKSlcblx0fSApXG5cblx0bGV0IG9yZGVyID0gXCJ0aXRsZVwiXG4gICAgJDogIHN3aXRjaChvcmRlcil7ICAgICAgXG5cdFx0Y2FzZSAndGl0bGUnOiB3b3JsZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuQ291bnRyeSA+IGIuQ291bnRyeSA/IDEgOiAtMSk7YnJlYWtcbiAgICAgICAgICAgIGNhc2UgJ2RlYXRoJzogd29ybGQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLlRvdGFsRGVhdGhzIDwgYi5Ub3RhbERlYXRocyA/IDEgOiAtMSk7IGJyZWFrXG4gICAgICAgICAgICBjYXNlICdpbmZlY3RlZCc6IHdvcmxkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Ub3RhbENvbmZpcm1lZCA8IGIuVG90YWxDb25maXJtZWQgPyAxIDogLTEpOyBicmVha1xuICAgICAgICAgICAgY2FzZSAncmVjb3ZlcmVkJzogd29ybGQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLlRvdGFsUmVjb3ZlcmVkIDwgYi5Ub3RhbFJlY292ZXJlZCA/IDEgOiAtMSk7IGJyZWFrXG5cdH1cblxuPC9zY3JpcHQ+XG5cbjxkaXY+XG5cdDxkaXYgY2xhc3M9XCJzb3J0XCIgaWQ9XCJteURpdlwiPlxuXHRcdDxidXR0b24gY2xhc3M9XCJidG4gYnV0dG9uIGFjdGl2ZVwiIG9uOmNsaWNrPXsoKSA9PiBvcmRlciA9IFwidGl0bGVcIn0+VGl0bGU8L2J1dHRvbj5cbiAgICBcdDxidXR0b24gY2xhc3M9XCJidG4gYnV0dG9uXCIgb246Y2xpY2s9eygpID0+IG9yZGVyID0gXCJkZWF0aFwifT5EZWF0aDwvYnV0dG9uPlxuICAgIFx0PGJ1dHRvbiBjbGFzcz1cImJ0biBidXR0b25cIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBcImluZmVjdGVkXCJ9PkluZmVjdGVkPC9idXR0b24+XG4gICAgXHQ8YnV0dG9uIGNsYXNzPVwiYnRuIGJ1dHRvblwiIG9uOmNsaWNrPXsoKSA9PiBvcmRlciA9IFwicmVjb3ZlcmVkXCJ9PlJlY292ZXJlZDwvYnV0dG9uPlxuXHQ8L2Rpdj5cblx0PHNlY3Rpb24+XG5cdFx0eyNlYWNoIHdvcmxkIGFzIGl0ZW19XG5cdFx0XHQ8V29ybGQgaXRlbT17aXRlbX0gLz5cblx0XHR7OmVsc2V9XG5cdFx0XHQ8TG9hZGVyIC8+XG5cdFx0ey9lYWNofSAgIFxuXHQ8L3NlY3Rpb24+XG48L2Rpdj5cblxuPHN0eWxlPlxuXHRkaXYge1xuXHRcdGRpc3BsYXk6IGdyaWQ7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogIzFiMWIzMDtcblx0XHR3aWR0aDogMTAwdnc7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdH1cbiAgICBzZWN0aW9ue1xuXHRcdGRpc3BsYXk6IGdyaWQ7XG4gICAgICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogcmVwZWF0KGF1dG8tZmlsbCwgbWlubWF4KDIwMHB4LCAxZnIpKTtcbiAgICAgICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoNSwgMWZyKTtcbiAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0Z2FwOiAycmVtO1xuICAgICAgICBtYXJnaW46IGF1dG87XG5cdFx0d2lkdGg6IDgwdnc7XG4gICAgfVxuXHQuc29ydCB7XG5cdFx0aGVpZ2h0OiAxMHZoO1xuXHRcdGRpc3BsYXk6IGdyaWQ7XG5cdFx0Z3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxMDBweCAxMDBweCAxMDBweCAxMDBweDtcblx0XHRnYXA6IDEwcHg7XG5cdFx0d2lkdGg6IDkwdnc7XG5cdFx0bWFyZ2luOiBhdXRvO1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdH1cblx0LmJ1dHRvbiB7XG5cdFx0aGVpZ2h0OiAzMHB4O1xuXHRcdGJhY2tncm91bmQtY29sb3I6IGluZGlnbztcblx0XHRjb2xvcjogd2hpdGU7XG5cdFx0b3V0bGluZTogbm9uZTtcblx0fVxuXHQuYWN0aXZlIHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiByZ2JhKDQsIDQsIDQsIC42KTtcblx0fVxuPC9zdHlsZT5cblxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWtEQyxHQUFHLGVBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZ0JBQWdCLENBQUUsT0FBTyxDQUN6QixLQUFLLENBQUUsS0FBSyxDQUNaLGVBQWUsQ0FBRSxNQUFNLEFBQ3hCLENBQUMsQUFDRSxzQkFBTyxDQUFDLEFBQ1YsT0FBTyxDQUFFLElBQUksQ0FDUCxxQkFBcUIsQ0FBRSxPQUFPLFNBQVMsQ0FBQyxDQUFDLE9BQU8sS0FBSyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsQ0FDNUQscUJBQXFCLENBQUUsT0FBTyxDQUFDLENBQUMsQ0FBQyxHQUFHLENBQUMsQ0FDckMsZUFBZSxDQUFFLE1BQU0sQ0FDN0IsR0FBRyxDQUFFLElBQUksQ0FDSCxNQUFNLENBQUUsSUFBSSxDQUNsQixLQUFLLENBQUUsSUFBSSxBQUNULENBQUMsQUFDSixLQUFLLGVBQUMsQ0FBQyxBQUNOLE1BQU0sQ0FBRSxJQUFJLENBQ1osT0FBTyxDQUFFLElBQUksQ0FDYixxQkFBcUIsQ0FBRSxLQUFLLENBQUMsS0FBSyxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQzlDLEdBQUcsQ0FBRSxJQUFJLENBQ1QsS0FBSyxDQUFFLElBQUksQ0FDWCxNQUFNLENBQUUsSUFBSSxDQUNaLGVBQWUsQ0FBRSxNQUFNLENBQ3ZCLE9BQU8sQ0FBRSxJQUFJLEFBQ2QsQ0FBQyxBQUNELE9BQU8sZUFBQyxDQUFDLEFBQ1IsTUFBTSxDQUFFLElBQUksQ0FDWixnQkFBZ0IsQ0FBRSxNQUFNLENBQ3hCLEtBQUssQ0FBRSxLQUFLLENBQ1osT0FBTyxDQUFFLElBQUksQUFDZCxDQUFDLEFBQ0QsT0FBTyxlQUFDLENBQUMsQUFDUixnQkFBZ0IsQ0FBRSxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxBQUNwQyxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[6] = list[i];
	return child_ctx;
}

// (44:2) {:else}
function create_else_block(ctx) {
	let current;
	const loader = new _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(loader.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(loader.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(loader, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(loader.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(loader.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(loader, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(44:2) {:else}",
		ctx
	});

	return block;
}

// (42:2) {#each world as item}
function create_each_block(ctx) {
	let current;

	const world_1 = new _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: { item: /*item*/ ctx[6] },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(world_1.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(world_1.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(world_1, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const world_1_changes = {};
			if (dirty & /*world*/ 1) world_1_changes.item = /*item*/ ctx[6];
			world_1.$set(world_1_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(world_1.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(world_1.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(world_1, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(42:2) {#each world as item}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let t0;
	let div1;
	let div0;
	let button0;
	let t1;
	let t2;
	let button1;
	let t3;
	let t4;
	let button2;
	let t5;
	let t6;
	let button3;
	let t7;
	let t8;
	let section;
	let current;
	let dispose;
	let each_value = /*world*/ ctx[0];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	let each_1_else = null;

	if (!each_value.length) {
		each_1_else = create_else_block(ctx);
	}

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Title");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Death");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Infected");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Recovered");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			if (each_1_else) {
				each_1_else.c();
			}

			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1136c5u\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "DIV", { class: true, id: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			button0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "BUTTON", { class: true });
			var button0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button0);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button0_nodes, "Title");
			button0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			button1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "BUTTON", { class: true });
			var button1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button1);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button1_nodes, "Death");
			button1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			button2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "BUTTON", { class: true });
			var button2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button2);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button2_nodes, "Infected");
			button2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div0_nodes);
			button3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "BUTTON", { class: true });
			var button3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button3);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button3_nodes, "Recovered");
			button3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div1_nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(section_nodes);
			}

			if (each_1_else) {
				each_1_else.l(section_nodes);
			}

			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "Corona information";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button0, "class", "btn button active svelte-1lqfd2b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button0, file, 35, 2, 987);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button1, "class", "btn button svelte-1lqfd2b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button1, file, 36, 5, 1074);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button2, "class", "btn button svelte-1lqfd2b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button2, file, 37, 5, 1154);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button3, "class", "btn button svelte-1lqfd2b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button3, file, 38, 5, 1240);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "sort svelte-1lqfd2b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "id", "myDiv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 34, 1, 955);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "svelte-1lqfd2b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 40, 1, 1332);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "svelte-1lqfd2b");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 33, 0, 948);
		},
		m: function mount(target, anchor, remount) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, button0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, button1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button1, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, button2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button2, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, button3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button3, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, section);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(section, null);
			}

			if (each_1_else) {
				each_1_else.m(section, null);
			}

			current = true;
			if (remount) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);

			dispose = [
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button0, "click", /*click_handler*/ ctx[2], false, false, false),
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button1, "click", /*click_handler_1*/ ctx[3], false, false, false),
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button2, "click", /*click_handler_2*/ ctx[4], false, false, false),
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button3, "click", /*click_handler_3*/ ctx[5], false, false, false)
			];
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*world*/ 1) {
				each_value = /*world*/ ctx[0];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(section, null);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();

				if (each_value.length) {
					if (each_1_else) {
						each_1_else.d(1);
						each_1_else = null;
					}
				} else if (!each_1_else) {
					each_1_else = create_else_block(ctx);
					each_1_else.c();
					each_1_else.m(section, null);
				}
			}
		},
		i: function intro(local) {
			if (current) return;

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			current = true;
		},
		o: function outro(local) {
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
			if (each_1_else) each_1_else.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let world = [];

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		await fetch(`https://api.covid19api.com/summary`).then(response => response.json()).then(json => {
			// World
			$$invalidate(0, world = json.Countries);
		}).catch(err => console.log(err));
	});

	let order = "title";
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", $$slots, []);
	const click_handler = () => $$invalidate(1, order = "title");
	const click_handler_1 = () => $$invalidate(1, order = "death");
	const click_handler_2 = () => $$invalidate(1, order = "infected");
	const click_handler_3 = () => $$invalidate(1, order = "recovered");
	$$self.$capture_state = () => ({ onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"], Loader: _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__["default"], World: _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__["default"], world, order });

	$$self.$inject_state = $$props => {
		if ("world" in $$props) $$invalidate(0, world = $$props.world);
		if ("order" in $$props) $$invalidate(1, order = $$props.order);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*order, world*/ 3) {
			$: switch (order) {
				case "title":
					$$invalidate(0, world = world.sort((a, b) => a.Country > b.Country ? 1 : -1));
					break;
				case "death":
					$$invalidate(0, world = world.sort((a, b) => a.TotalDeaths < b.TotalDeaths ? 1 : -1));
					break;
				case "infected":
					$$invalidate(0, world = world.sort((a, b) => a.TotalConfirmed < b.TotalConfirmed ? 1 : -1));
					break;
				case "recovered":
					$$invalidate(0, world = world.sort((a, b) => a.TotalRecovered < b.TotalRecovered ? 1 : -1));
					break;
			}
		}
	};

	return [world, order, click_handler, click_handler_1, click_handler_2, click_handler_3];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1lqfd2b-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9Xb3JsZC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9pbmRleC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkFTcUIsR0FBSSxJQUFDLE9BQU87Ozs7O3lCQUNJLEdBQUksSUFBQyxjQUFjLENBQUMsUUFBUSxHQUFHLE9BQU8sQ0FBQyx1QkFBdUIsRUFBRSxHQUFHOzs7Ozt5QkFDeEUsR0FBSSxJQUFDLFdBQVcsQ0FBQyxRQUFRLEdBQUcsT0FBTyxDQUFDLHVCQUF1QixFQUFFLEdBQUc7Ozs7O3lCQUMzRCxHQUFJLElBQUMsY0FBYyxDQUFDLFFBQVEsR0FBRyxPQUFPLENBQUMsdUJBQXVCLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzswSEFMekUsR0FBTyxRQUFLLFNBQVMsR0FBRyxNQUFNLEdBQUcsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OytEQUVwRCxHQUFJLElBQUMsT0FBTzsrREFDSSxHQUFJLElBQUMsY0FBYyxDQUFDLFFBQVEsR0FBRyxPQUFPLENBQUMsdUJBQXVCLEVBQUUsR0FBRzsrREFDeEUsR0FBSSxJQUFDLFdBQVcsQ0FBQyxRQUFRLEdBQUcsT0FBTyxDQUFDLHVCQUF1QixFQUFFLEdBQUc7K0RBQzNELEdBQUksSUFBQyxjQUFjLENBQUMsUUFBUSxHQUFHLE9BQU8sQ0FBQyx1QkFBdUIsRUFBRSxHQUFHOzs2RkFMekUsR0FBTyxRQUFLLFNBQVMsR0FBRyxNQUFNLEdBQUcsU0FBUzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7T0FMOUQsSUFBSTtPQUNKLE9BQU87Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0FDRWU7QUFDZ0I7QUFDRjs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MkJBbUMvQixHQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs0REFBSixHQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0QkFEWCxHQUFLOzs7O2dDQUFWLE1BQUk7Ozs7Ozs7Ozs7aUJBQUosTUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsyQkFBQyxHQUFLOzs7OytCQUFWLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7d0JBQUosTUFBSTs7Ozs7O21CQUFKLE1BQUk7Ozs7Ozs7Ozs7Ozs7OztrQ0FBSixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7S0EvQkgsS0FBSzs7Q0FHTixzREFBTztRQUNILEtBQUssdUNBQ1YsSUFBSSxDQUFFLFFBQVEsSUFBSSxRQUFRLENBQUMsSUFBSSxJQUN6QixJQUFJLENBQUUsSUFBSTs7bUJBRVAsS0FBSyxHQUFHLElBQUksQ0FBQyxTQUFTO0tBRXhCLEtBQUssQ0FBRSxHQUFHLElBQUssT0FBTyxDQUFDLEdBQUcsQ0FBQyxHQUFHOzs7S0FHbkMsS0FBSyxHQUFHLE9BQU87Ozs7Ozs7Ozs2Q0FZZ0MsS0FBSyxHQUFHLE9BQU87K0NBQ25CLEtBQUssR0FBRyxPQUFPOytDQUNmLEtBQUssR0FBRyxVQUFVOytDQUNsQixLQUFLLEdBQUcsV0FBVzs7Ozs7Ozs7Ozs7Ozs7R0FkL0QsQ0FBQyxVQUFVLEtBQUs7U0FDYixPQUFPO3FCQUFFLEtBQUssR0FBRyxLQUFLLENBQUMsSUFBSSxFQUFHLENBQUMsRUFBQyxDQUFDLEtBQUssQ0FBQyxDQUFDLE9BQU8sR0FBRyxDQUFDLENBQUMsT0FBTyxHQUFHLENBQUMsSUFBSSxDQUFDOztTQUMxRCxPQUFPO3FCQUFFLEtBQUssR0FBRyxLQUFLLENBQUMsSUFBSSxFQUFHLENBQUMsRUFBQyxDQUFDLEtBQUssQ0FBQyxDQUFDLFdBQVcsR0FBRyxDQUFDLENBQUMsV0FBVyxHQUFHLENBQUMsSUFBSSxDQUFDOztTQUM1RSxVQUFVO3FCQUFFLEtBQUssR0FBRyxLQUFLLENBQUMsSUFBSSxFQUFHLENBQUMsRUFBQyxDQUFDLEtBQUssQ0FBQyxDQUFDLGNBQWMsR0FBRyxDQUFDLENBQUMsY0FBYyxHQUFHLENBQUMsSUFBSSxDQUFDOztTQUNyRixXQUFXO3FCQUFFLEtBQUssR0FBRyxLQUFLLENBQUMsSUFBSSxFQUFHLENBQUMsRUFBQyxDQUFDLEtBQUssQ0FBQyxDQUFDLGNBQWMsR0FBRyxDQUFDLENBQUMsY0FBYyxHQUFHLENBQUMsSUFBSSxDQUFDIiwiZmlsZSI6ImFkZGI4OWE0ZjRjYzk0YTAwMzc1L2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cblxuZXhwb3J0IGxldCBpdGVtXG5leHBvcnQgbGV0IHNlZ21lbnRcblxuPC9zY3JpcHQ+XG5cbjxhIHJlbD1wcmVmZXRjaCBhcmlhLWN1cnJlbnQ9J3tzZWdtZW50ID09PSBcImNvdW50cnlcIiA/IFwicGFnZVwiIDogdW5kZWZpbmVkfScgaHJlZj0nY291bnRyeSc+XG5cdDxhcnRpY2xlPlxuXHRcdDxoMSBjbGFzcz1cIndoaXRlXCI+e2l0ZW0uQ291bnRyeX08L2gxPlxuXHRcdDxwIGNsYXNzPVwib3JhbmdlXCI+VG90YWwgaW5mZWN0ZWQ6IHtpdGVtLlRvdGFsQ29uZmlybWVkLnRvU3RyaW5nKCkucmVwbGFjZSgvXFxCKD89KFxcZHszfSkrKD8hXFxkKSkvZywgXCIsXCIpfTwvcD5cblx0XHQ8cCBjbGFzcz1cInJlZFwiPlRvdGFsIGRlYXRoczoge2l0ZW0uVG90YWxEZWF0aHMudG9TdHJpbmcoKS5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCBcIixcIil9PC9wPlxuXHRcdDxwIGNsYXNzPVwiZ3JlZW5cIj5Ub3RhbCByZWNvdmVyZWQ6IHtpdGVtLlRvdGFsUmVjb3ZlcmVkLnRvU3RyaW5nKCkucmVwbGFjZSgvXFxCKD89KFxcZHszfSkrKD8hXFxkKSkvZywgXCIsXCIpfTwvcD5cblx0PC9hcnRpY2xlPlx0XHRcbjwvYT5cblxuXG48c3R5bGU+XG5cdGFydGljbGUge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHJnYmEoNCwgNCwgNCwgLjYpO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdH1cblx0LndoaXRlIHtcblx0XHRjb2xvcjogd2hpdGU7XG5cdH1cblx0LmdyZWVuIHtcblx0XHRjb2xvcjogZ3JlZW47XG5cdH1cblx0LnJlZCB7XG5cdFx0Y29sb3I6IHJlZDtcblx0fVxuXHQub3JhbmdlIHtcblx0XHRjb2xvcjogb3JhbmdlO1xuXHR9XG4gICAgYSB7XG5cdCAgICB0ZXh0LWRlY29yYXRpb246IG5vbmU7XG5cdH1cblxuXHRhOmhvdmVyIHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcblx0fVxuXG48L3N0eWxlPiIsIjxzdmVsdGU6aGVhZD5cblx0PHRpdGxlPkNvcm9uYSBpbmZvcm1hdGlvbjwvdGl0bGU+XG48L3N2ZWx0ZTpoZWFkPlxuXG48c2NyaXB0PlxuXHRpbXBvcnQgeyBvbk1vdW50IH0gZnJvbSBcInN2ZWx0ZVwiXG5cdGltcG9ydCBMb2FkZXIgZnJvbSBcIi4uL2NvbXBvbmVudHMvTG9hZGVyLnN2ZWx0ZVwiXG5cdGltcG9ydCBXb3JsZCBmcm9tIFwiLi4vY29tcG9uZW50cy9Xb3JsZC5zdmVsdGVcIlxuXG5cblx0bGV0IHdvcmxkID0gW11cblxuXG4gICAgb25Nb3VudCggYXN5bmMgKCkgPT4ge1xuXHRcdGF3YWl0IGZldGNoKGBodHRwczovL2FwaS5jb3ZpZDE5YXBpLmNvbS9zdW1tYXJ5YClcblx0XHQudGhlbiggcmVzcG9uc2UgPT4gcmVzcG9uc2UuanNvbigpIClcbiAgICAgICAgLnRoZW4oIGpzb24gPT4ge1xuXHRcdFx0Ly8gV29ybGRcbiAgICAgICAgICAgIHdvcmxkID0ganNvbi5Db3VudHJpZXNcbiAgICAgICAgfVxuICAgICAgICApLmNhdGNoKChlcnIpID0+IGNvbnNvbGUubG9nKGVycikpXG5cdH0gKVxuXG5cdGxldCBvcmRlciA9IFwidGl0bGVcIlxuICAgICQ6ICBzd2l0Y2gob3JkZXIpeyAgICAgIFxuXHRcdGNhc2UgJ3RpdGxlJzogd29ybGQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLkNvdW50cnkgPiBiLkNvdW50cnkgPyAxIDogLTEpO2JyZWFrXG4gICAgICAgICAgICBjYXNlICdkZWF0aCc6IHdvcmxkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Ub3RhbERlYXRocyA8IGIuVG90YWxEZWF0aHMgPyAxIDogLTEpOyBicmVha1xuICAgICAgICAgICAgY2FzZSAnaW5mZWN0ZWQnOiB3b3JsZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxDb25maXJtZWQgPCBiLlRvdGFsQ29uZmlybWVkID8gMSA6IC0xKTsgYnJlYWtcbiAgICAgICAgICAgIGNhc2UgJ3JlY292ZXJlZCc6IHdvcmxkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Ub3RhbFJlY292ZXJlZCA8IGIuVG90YWxSZWNvdmVyZWQgPyAxIDogLTEpOyBicmVha1xuXHR9XG5cbjwvc2NyaXB0PlxuXG48ZGl2PlxuXHQ8ZGl2IGNsYXNzPVwic29ydFwiIGlkPVwibXlEaXZcIj5cblx0XHQ8YnV0dG9uIGNsYXNzPVwiYnRuIGJ1dHRvbiBhY3RpdmVcIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBcInRpdGxlXCJ9PlRpdGxlPC9idXR0b24+XG4gICAgXHQ8YnV0dG9uIGNsYXNzPVwiYnRuIGJ1dHRvblwiIG9uOmNsaWNrPXsoKSA9PiBvcmRlciA9IFwiZGVhdGhcIn0+RGVhdGg8L2J1dHRvbj5cbiAgICBcdDxidXR0b24gY2xhc3M9XCJidG4gYnV0dG9uXCIgb246Y2xpY2s9eygpID0+IG9yZGVyID0gXCJpbmZlY3RlZFwifT5JbmZlY3RlZDwvYnV0dG9uPlxuICAgIFx0PGJ1dHRvbiBjbGFzcz1cImJ0biBidXR0b25cIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBcInJlY292ZXJlZFwifT5SZWNvdmVyZWQ8L2J1dHRvbj5cblx0PC9kaXY+XG5cdDxzZWN0aW9uPlxuXHRcdHsjZWFjaCB3b3JsZCBhcyBpdGVtfVxuXHRcdFx0PFdvcmxkIGl0ZW09e2l0ZW19IC8+XG5cdFx0ezplbHNlfVxuXHRcdFx0PExvYWRlciAvPlxuXHRcdHsvZWFjaH0gICBcblx0PC9zZWN0aW9uPlxuPC9kaXY+XG5cbjxzdHlsZT5cblx0ZGl2IHtcblx0XHRkaXNwbGF5OiBncmlkO1xuXHRcdGJhY2tncm91bmQtY29sb3I6ICMxYjFiMzA7XG5cdFx0d2lkdGg6IDEwMHZ3O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHR9XG4gICAgc2VjdGlvbntcblx0XHRkaXNwbGF5OiBncmlkO1xuICAgICAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdChhdXRvLWZpbGwsIG1pbm1heCgyMDBweCwgMWZyKSk7XG4gICAgICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogcmVwZWF0KDUsIDFmcik7XG4gICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGdhcDogMnJlbTtcbiAgICAgICAgbWFyZ2luOiBhdXRvO1xuXHRcdHdpZHRoOiA4MHZ3O1xuICAgIH1cblx0LnNvcnQge1xuXHRcdGhlaWdodDogMTB2aDtcblx0XHRkaXNwbGF5OiBncmlkO1xuXHRcdGdyaWQtdGVtcGxhdGUtY29sdW1uczogMTAwcHggMTAwcHggMTAwcHggMTAwcHg7XG5cdFx0Z2FwOiAxMHB4O1xuXHRcdHdpZHRoOiA5MHZ3O1xuXHRcdG1hcmdpbjogYXV0bztcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRwYWRkaW5nOiAxcmVtO1xuXHR9XG5cdC5idXR0b24ge1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiBpbmRpZ287XG5cdFx0Y29sb3I6IHdoaXRlO1xuXHRcdG91dGxpbmU6IG5vbmU7XG5cdH1cblx0LmFjdGl2ZSB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogcmdiYSg0LCA0LCA0LCAuNik7XG5cdH1cbjwvc3R5bGU+XG5cbiJdLCJzb3VyY2VSb290IjoiIn0=