(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/Loader.svelte":
/*!**************************************!*\
  !*** ./src/components/Loader.svelte ***!
  \**************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/Loader.svelte generated by Svelte v3.22.2 */


const file = "src/components/Loader.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-145waro-style";
	style.textContent = ".spinner.svelte-145waro.svelte-145waro{width:50px;height:40px;text-align:center;font-size:10px}.spinner.svelte-145waro>div.svelte-145waro{background-color:white;height:100%;width:6px;display:inline-block;animation:svelte-145waro-sk-stretchdelay 1.2s infinite ease-in-out}.spinner.svelte-145waro .rect2.svelte-145waro{animation-delay:-1.1s}.spinner.svelte-145waro .rect3.svelte-145waro{animation-delay:-1.0s}.spinner.svelte-145waro .rect4.svelte-145waro{-webkit-animation-delay:-0.9s;animation-delay:-0.9s}.spinner.svelte-145waro .rect5.svelte-145waro{animation-delay:-0.8s}@keyframes svelte-145waro-sk-stretchdelay{0%,40%,100%{transform:scaleY(0.4)}20%{transform:scaleY(1.0)}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTG9hZGVyLnN2ZWx0ZSIsInNvdXJjZXMiOlsiTG9hZGVyLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyIgICAgICBcbiAgICAgIDxkaXYgY2xhc3M9XCJzcGlubmVyXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyZWN0MVwiPjwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicmVjdDJcIj48L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJlY3QzXCI+PC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyZWN0NFwiPjwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicmVjdDVcIj48L2Rpdj5cbiAgICAgIDwvZGl2PlxuXG48c3R5bGU+XG4gIC5zcGlubmVyIHtcbiAgICB3aWR0aDogNTBweDtcbiAgICBoZWlnaHQ6IDQwcHg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGZvbnQtc2l6ZTogMTBweDtcbiAgfVxuXG4gIC5zcGlubmVyID4gZGl2IHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcbiAgICBoZWlnaHQ6IDEwMCU7XG4gICAgd2lkdGg6IDZweDtcbiAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gICAgYW5pbWF0aW9uOiBzay1zdHJldGNoZGVsYXkgMS4ycyBpbmZpbml0ZSBlYXNlLWluLW91dDtcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0MiB7XG4gICAgYW5pbWF0aW9uLWRlbGF5OiAtMS4xcztcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0MyB7XG4gICAgYW5pbWF0aW9uLWRlbGF5OiAtMS4wcztcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0NCB7XG4gICAgLXdlYmtpdC1hbmltYXRpb24tZGVsYXk6IC0wLjlzO1xuICAgIGFuaW1hdGlvbi1kZWxheTogLTAuOXM7XG4gIH1cblxuICAuc3Bpbm5lciAucmVjdDUge1xuICAgIGFuaW1hdGlvbi1kZWxheTogLTAuOHM7XG4gIH1cblxuXG4gIEBrZXlmcmFtZXMgc2stc3RyZXRjaGRlbGF5IHtcbiAgICAwJSwgNDAlLCAxMDAlIHtcbiAgICAgIHRyYW5zZm9ybTogc2NhbGVZKDAuNCk7XG4gICAgfSAgMjAlIHtcbiAgICAgIHRyYW5zZm9ybTogc2NhbGVZKDEuMCk7XG4gICAgfVxuICB9XG48L3N0eWxlPiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFVRSxRQUFRLDhCQUFDLENBQUMsQUFDUixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osVUFBVSxDQUFFLE1BQU0sQ0FDbEIsU0FBUyxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUVELHVCQUFRLENBQUcsR0FBRyxlQUFDLENBQUMsQUFDZCxnQkFBZ0IsQ0FBRSxLQUFLLENBQ3ZCLE1BQU0sQ0FBRSxJQUFJLENBQ1osS0FBSyxDQUFFLEdBQUcsQ0FDVixPQUFPLENBQUUsWUFBWSxDQUNyQixTQUFTLENBQUUsOEJBQWUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLFdBQVcsQUFDdEQsQ0FBQyxBQUVELHVCQUFRLENBQUMsTUFBTSxlQUFDLENBQUMsQUFDZixlQUFlLENBQUUsS0FBSyxBQUN4QixDQUFDLEFBRUQsdUJBQVEsQ0FBQyxNQUFNLGVBQUMsQ0FBQyxBQUNmLGVBQWUsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFFRCx1QkFBUSxDQUFDLE1BQU0sZUFBQyxDQUFDLEFBQ2YsdUJBQXVCLENBQUUsS0FBSyxDQUM5QixlQUFlLENBQUUsS0FBSyxBQUN4QixDQUFDLEFBRUQsdUJBQVEsQ0FBQyxNQUFNLGVBQUMsQ0FBQyxBQUNmLGVBQWUsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFHRCxXQUFXLDhCQUFnQixDQUFDLEFBQzFCLEVBQUUsQ0FBRSxHQUFHLENBQUUsSUFBSSxBQUFDLENBQUMsQUFDYixTQUFTLENBQUUsT0FBTyxHQUFHLENBQUMsQUFDeEIsQ0FBQyxBQUFFLEdBQUcsQUFBQyxDQUFDLEFBQ04sU0FBUyxDQUFFLE9BQU8sR0FBRyxDQUFDLEFBQ3hCLENBQUMsQUFDSCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div5;
	let div0;
	let t0;
	let div1;
	let t1;
	let div2;
	let t2;
	let div3;
	let t3;
	let div4;

	const block = {
		c: function create() {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			this.h();
		},
		l: function claim(nodes) {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "rect1 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 2, 8, 43);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "rect2 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 3, 8, 77);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "rect3 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 4, 8, 111);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "rect4 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 5, 8, 145);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "rect5 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 6, 8, 179);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "spinner svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 1, 6, 13);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div5, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div4);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div5);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Loader> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Loader", $$slots, []);
	return [];
}

class Loader extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-145waro-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Loader",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Loader);

/***/ }),

/***/ "./src/components/World.svelte":
/*!*************************************!*\
  !*** ./src/components/World.svelte ***!
  \*************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/World.svelte generated by Svelte v3.22.2 */


const file = "src/components/World.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-bch2qw-style";
	style.textContent = "article.svelte-bch2qw{background-color:rgba(4, 4, 4, .6);padding:1rem;border-radius:10px;display:grid;max-width:15rem;max-height:16rem}article.svelte-bch2qw:hover{background-color:rgba(4, 4, 4, .2)}.white.svelte-bch2qw{color:white;text-align:center;font-size:1.8rem}.green.svelte-bch2qw{color:green}.red.svelte-bch2qw{color:red}.orange.svelte-bch2qw{color:orange}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiV29ybGQuc3ZlbHRlIiwic291cmNlcyI6WyJXb3JsZC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cblxuZXhwb3J0IGxldCBpdGVtXG5cbjwvc2NyaXB0PlxuXG5cbjxhcnRpY2xlPlxuXHQ8aDEgY2xhc3M9XCJ3aGl0ZVwiPntpdGVtLkNvdW50cnl9PC9oMT5cblx0PHAgY2xhc3M9XCJ0ZXh0IG9yYW5nZVwiPlRvdGFsIGluZmVjdGVkOiB7aXRlbS5Ub3RhbENvbmZpcm1lZC50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG5cdDxwIGNsYXNzPVwidGV4dCByZWRcIj5Ub3RhbCBkZWF0aHM6IHtpdGVtLlRvdGFsRGVhdGhzLnRvU3RyaW5nKCkucmVwbGFjZSgvXFxCKD89KFxcZHszfSkrKD8hXFxkKSkvZywgXCIsXCIpfTwvcD5cblx0PHAgY2xhc3M9XCJ0ZXh0IGdyZWVuXCI+VG90YWwgcmVjb3ZlcmVkOiB7aXRlbS5Ub3RhbFJlY292ZXJlZC50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG48L2FydGljbGU+XHRcdFxuXG48c3R5bGU+XG5cdGFydGljbGUge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHJnYmEoNCwgNCwgNCwgLjYpO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdFx0Ym9yZGVyLXJhZGl1czogMTBweDtcblx0XHRkaXNwbGF5OiBncmlkO1xuXHRcdG1heC13aWR0aDogMTVyZW07XG5cdFx0bWF4LWhlaWdodDogMTZyZW07XG5cdH1cblx0YXJ0aWNsZTpob3ZlciB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogcmdiYSg0LCA0LCA0LCAuMik7XG5cdH1cblx0LndoaXRlIHtcblx0XHRjb2xvcjogd2hpdGU7XG5cdFx0dGV4dC1hbGlnbjogY2VudGVyO1xuXHRcdGZvbnQtc2l6ZTogMS44cmVtO1xuXHR9XG5cdC5ncmVlbiB7XG5cdFx0Y29sb3I6IGdyZWVuO1xuXHR9XG5cdC5yZWQge1xuXHRcdGNvbG9yOiByZWQ7XG5cdH1cblx0Lm9yYW5nZSB7XG5cdFx0Y29sb3I6IG9yYW5nZTtcblx0fVxuPC9zdHlsZT4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBZUMsT0FBTyxjQUFDLENBQUMsQUFDUixnQkFBZ0IsQ0FBRSxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUNuQyxPQUFPLENBQUUsSUFBSSxDQUNiLGFBQWEsQ0FBRSxJQUFJLENBQ25CLE9BQU8sQ0FBRSxJQUFJLENBQ2IsU0FBUyxDQUFFLEtBQUssQ0FDaEIsVUFBVSxDQUFFLEtBQUssQUFDbEIsQ0FBQyxBQUNELHFCQUFPLE1BQU0sQUFBQyxDQUFDLEFBQ2QsZ0JBQWdCLENBQUUsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsQUFDcEMsQ0FBQyxBQUNELE1BQU0sY0FBQyxDQUFDLEFBQ1AsS0FBSyxDQUFFLEtBQUssQ0FDWixVQUFVLENBQUUsTUFBTSxDQUNsQixTQUFTLENBQUUsTUFBTSxBQUNsQixDQUFDLEFBQ0QsTUFBTSxjQUFDLENBQUMsQUFDUCxLQUFLLENBQUUsS0FBSyxBQUNiLENBQUMsQUFDRCxJQUFJLGNBQUMsQ0FBQyxBQUNMLEtBQUssQ0FBRSxHQUFHLEFBQ1gsQ0FBQyxBQUNELE9BQU8sY0FBQyxDQUFDLEFBQ1IsS0FBSyxDQUFFLE1BQU0sQUFDZCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let article;
	let h1;
	let t0_value = /*item*/ ctx[0].Country + "";
	let t0;
	let t1;
	let p0;
	let t2;
	let t3_value = /*item*/ ctx[0].TotalConfirmed.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t3;
	let t4;
	let p1;
	let t5;
	let t6_value = /*item*/ ctx[0].TotalDeaths.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t6;
	let t7;
	let p2;
	let t8;
	let t9_value = /*item*/ ctx[0].TotalRecovered.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t9;

	const block = {
		c: function create() {
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("article");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total infected: ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total deaths: ");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t6_value);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total recovered: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t9_value);
			this.h();
		},
		l: function claim(nodes) {
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "ARTICLE", { class: true });
			var article_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(article);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, t0_value);
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Total infected: ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, t3_value);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Total deaths: ");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, t6_value);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "Total recovered: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, t9_value);
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			article_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "white svelte-bch2qw");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 8, 1, 50);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "text orange svelte-bch2qw");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 9, 1, 89);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "text red svelte-bch2qw");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 10, 1, 204);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p2, "class", "text green svelte-bch2qw");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 11, 1, 311);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(article, "class", "svelte-bch2qw");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(article, file, 7, 0, 39);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, article, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t9);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*item*/ 1 && t0_value !== (t0_value = /*item*/ ctx[0].Country + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, t0_value);
			if (dirty & /*item*/ 1 && t3_value !== (t3_value = /*item*/ ctx[0].TotalConfirmed.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, t3_value);
			if (dirty & /*item*/ 1 && t6_value !== (t6_value = /*item*/ ctx[0].TotalDeaths.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t6, t6_value);
			if (dirty & /*item*/ 1 && t9_value !== (t9_value = /*item*/ ctx[0].TotalRecovered.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t9, t9_value);
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(article);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { item } = $$props;
	const writable_props = ["item"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<World> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("World", $$slots, []);

	$$self.$set = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
	};

	$$self.$capture_state = () => ({ item });

	$$self.$inject_state = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [item];
}

class World extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-bch2qw-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { item: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "World",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*item*/ ctx[0] === undefined && !("item" in props)) {
			console.warn("<World> was created without expected prop 'item'");
		}
	}

	get item() {
		throw new Error("<World>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set item(value) {
		throw new Error("<World>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (World);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/Loader.svelte */ "./src/components/Loader.svelte");
/* harmony import */ var _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/World.svelte */ "./src/components/World.svelte");
/* src/routes/index.svelte generated by Svelte v3.22.2 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-mj86kf-style";
	style.textContent = "div.svelte-mj86kf{display:grid;background-color:#1b1b30;width:100vw;justify-content:center}section.svelte-mj86kf{display:grid;grid-template-columns:repeat(auto-fit, minmax(200px, 1fr));justify-content:center;gap:2rem;margin:auto;width:70vw;min-height:100vh}.sort.svelte-mj86kf{display:grid;grid-template-columns:100px 100px 100px 100px;gap:10px;width:90vw;margin:auto;justify-content:center}label.svelte-mj86kf{color:white;margin:auto;padding:1rem;text-align:1.9rem}.button.svelte-mj86kf{height:30px;background-color:indigo;color:white;outline:none}.searchbar.svelte-mj86kf{align-content:center;width:100vw;text-align:center}.search-input.svelte-mj86kf{border-radius:4px;border:1px solid black;padding:1rem;font-size:20px;margin:15px;outline:none;width:30rem}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+Q29yb25hIGluZm9ybWF0aW9uPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxzY3JpcHQ+XG5cdGltcG9ydCB7IG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCJcblx0aW1wb3J0IExvYWRlciBmcm9tIFwiLi4vY29tcG9uZW50cy9Mb2FkZXIuc3ZlbHRlXCJcblx0aW1wb3J0IFdvcmxkIGZyb20gXCIuLi9jb21wb25lbnRzL1dvcmxkLnN2ZWx0ZVwiXG5cdGV4cG9ydCBjb25zdCBmYXZvcml0ZXMgPSBbXVxuXG5cblx0bGV0IHdvcmxkID0gW11cblx0bGV0IHNlYXJjaGVkID0gW11cblxuICAgIG9uTW91bnQoIGFzeW5jICgpID0+IHtcblx0XHRhd2FpdCBmZXRjaChgaHR0cHM6Ly9hcGkuY292aWQxOWFwaS5jb20vc3VtbWFyeWApXG5cdFx0LnRoZW4oIHJlc3BvbnNlID0+IHJlc3BvbnNlLmpzb24oKSApXG4gICAgICAgIC50aGVuKCBqc29uID0+IHtcblx0XHRcdC8vIFdvcmxkXG5cdFx0XHR3b3JsZCA9IGpzb24uQ291bnRyaWVzXG5cdFx0XHRzZWFyY2hlZCA9IHdvcmxkXG4gICAgICAgIH1cbiAgICAgICAgKS5jYXRjaCgoZXJyKSA9PiBjb25zb2xlLmxvZyhlcnIpKVxuXHR9IClcblxuXHRsZXQgb3JkZXIgPSBcInRpdGxlXCJcbiAgICAkOiAgc3dpdGNoKG9yZGVyKXsgICAgICBcblx0XHRjYXNlICd0aXRsZSc6IHNlYXJjaGVkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Db3VudHJ5ID4gYi5Db3VudHJ5ID8gMSA6IC0xKTticmVha1xuICAgICAgICAgICAgY2FzZSAnZGVhdGgnOiBzZWFyY2hlZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxEZWF0aHMgPCBiLlRvdGFsRGVhdGhzID8gMSA6IC0xKTsgYnJlYWtcbiAgICAgICAgICAgIGNhc2UgJ2luZmVjdGVkJzogc2VhcmNoZWQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLlRvdGFsQ29uZmlybWVkIDwgYi5Ub3RhbENvbmZpcm1lZCA/IDEgOiAtMSk7IGJyZWFrXG4gICAgICAgICAgICBjYXNlICdyZWNvdmVyZWQnOiBzZWFyY2hlZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxSZWNvdmVyZWQgPCBiLlRvdGFsUmVjb3ZlcmVkID8gMSA6IC0xKTsgYnJlYWtcblx0fVxuXG5cdCAgICBsZXQgc2VhcmNoID0gXCJcIlxuICAgIGNvbnN0IGZpbHRlclJlc3VsdCA9ICgpID0+IHtcblx0XHRpZihzZWFyY2ggPT09IFwiIFwiKXtcblx0XHRcdHNlYXJjaGVkID0gd29ybGRcblx0XHR9ZWxzZSB7XG5cdFx0XHRzZWFyY2hlZCA9IHdvcmxkLmZpbHRlciggd29ybGQgPT4gd29ybGQuQ291bnRyeS50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKHNlYXJjaC50b0xvd2VyQ2FzZSgpKSlcblx0XHR9XG4gICAgfVxuXG5cbi8qXG5cdGNvbnN0IGJ0bkNvbnRhaW5lciA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIjbXlEaXZcIik7XG5cdGNvbnN0IGJ0bnMgPSBidG5Db250YWluZXIucXVlcnlTZWxlY3RvcihcIi5idG5cIilcblx0Zm9yKHZhciBpID0gMDsgaSA8IGJ0bnMubGVuZ3RoOyBpKyspIHtcblx0XHRidG5zW2ldLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCBmdW5jdGlvbigpIHtcblx0XHRcdHZhciBjdXJyZW50ID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZShcImFjdGl2ZVwiKTtcblxuXHRcdFx0aWYoY3VycmVudC5sZW5ndGggPiAwKSB7XG5cdFx0XHRcdGN1cnJlbnRbMF0uY2xhc3NOYW1lID0gY3VycmVudFswXS5jbGFzc05hbWUucmVwbGFjZShcIiBhY3RpdmVcIiwgXCJcIik7XG5cdFx0XHR9XG5cblx0XHRcdHRoaXMuY2xhc3NOYW1lICs9IFwiIGFjdGl2ZVwiXG5cdFx0fSlcblx0fVxuXG4qL1xuXG5cdGNvbnN0IGJ1dHRvbnMgPSBbXG5cdFx0e29yZGVyOiBcIlRpdGxlXCIsIG9yZGVyVHlwZTogXCJ0aXRsZVwifSxcblx0XHR7b3JkZXI6IFwiRGVhdGhcIiwgb3JkZXJUeXBlOiBcImRlYXRoXCJ9LFxuXHRcdHtvcmRlcjogXCJJbmZlY3RlZFwiLCBvcmRlclR5cGU6IFwiaW5mZWN0ZWRcIn0sXG5cdFx0e29yZGVyOiBcIlJlY292ZXJlZFwiLCBvcmRlclR5cGU6IFwicmVjb3ZlcmVkXCJ9XG5cblx0XVxuXG48L3NjcmlwdD5cblxuPGRpdj5cblx0PGxhYmVsIGZvcj1cImJ0blwiID5Tb3J0IGJ5OjwvbGFiZWw+XG5cdDxkaXYgY2xhc3M9XCJzb3J0XCIgaWQ9XCJteURpdlwiPlxuXHR7I2VhY2ggYnV0dG9ucyBhcyBidXR0b259XG5cdFx0PGJ1dHRvbiBpZD1cImJ0blwiIGNsYXNzPVwiYnV0dG9uXCIgb246Y2xpY2s9eygpID0+IG9yZGVyID0gYCR7YnV0dG9uLm9yZGVyVHlwZX1gfSA+e2J1dHRvbi5vcmRlcn08L2J1dHRvbj5cblx0ey9lYWNofVxuXG5cdDwvZGl2PlxuXHQ8ZGl2IGNsYXNzPVwic2VhcmNoYmFyXCI+XG4gICAgICAgIDxpbnB1dCBhdXRvY29tcGxldGU9XCJvZmZcIiAgY2xhc3M9XCJzZWFyY2gtaW5wdXRcIiB0eXBlPVwic2VhcmNoXCIgcGxhY2Vob2xkZXI9XCJTZWFyY2ggYWZ0ZXIgY291bnRyeVwiIGJpbmQ6dmFsdWU9e3NlYXJjaH0gb246aW5wdXR8cHJldmVudERlZmF1bHQ9e2ZpbHRlclJlc3VsdH0vPlxuICAgIDwvZGl2PlxuXHQ8c2VjdGlvbj5cblx0XHR7I2VhY2ggc2VhcmNoZWQgYXMgaXRlbX1cblx0XHRcdDxXb3JsZCBpdGVtPXtpdGVtfSAvPlxuXHRcdHs6ZWxzZX1cblx0XHRcdDxMb2FkZXIgLz5cblx0XHR7L2VhY2h9ICAgXG5cdDwvc2VjdGlvbj5cbjwvZGl2PlxuXG48c3R5bGU+XG5cdGRpdiB7XG5cdFx0ZGlzcGxheTogZ3JpZDtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiAjMWIxYjMwO1xuXHRcdHdpZHRoOiAxMDB2dztcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0fVxuICAgIHNlY3Rpb257XG5cdFx0ZGlzcGxheTogZ3JpZDtcbiAgICAgICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoYXV0by1maXQsIG1pbm1heCgyMDBweCwgMWZyKSk7XG4gICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGdhcDogMnJlbTtcbiAgICAgICAgbWFyZ2luOiBhdXRvO1xuXHRcdHdpZHRoOiA3MHZ3O1xuXHRcdG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgIH1cblx0LnNvcnQge1xuXHRcdGRpc3BsYXk6IGdyaWQ7XG5cdFx0Z3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxMDBweCAxMDBweCAxMDBweCAxMDBweDtcblx0XHRnYXA6IDEwcHg7XG5cdFx0d2lkdGg6IDkwdnc7XG5cdFx0bWFyZ2luOiBhdXRvO1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHR9XG5cdGxhYmVsIHtcblx0XHRjb2xvcjogd2hpdGU7XG5cdFx0bWFyZ2luOiBhdXRvO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdFx0dGV4dC1hbGlnbjogMS45cmVtO1xuXHR9XG5cdC5idXR0b24ge1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiBpbmRpZ287XG5cdFx0Y29sb3I6IHdoaXRlO1xuXHRcdG91dGxpbmU6IG5vbmU7XG5cdH1cblx0LnNlYXJjaGJhciB7XG4gICAgICAgIGFsaWduLWNvbnRlbnQ6IGNlbnRlcjtcbiAgICAgICAgd2lkdGg6IDEwMHZ3O1xuICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgfVxuICAgIC5zZWFyY2gtaW5wdXQge1xuICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7XG4gICAgICAgIGJvcmRlcjogMXB4IHNvbGlkIGJsYWNrO1xuICAgICAgICBwYWRkaW5nOiAxcmVtO1xuICAgICAgICBmb250LXNpemU6IDIwcHg7XG4gICAgICAgIG1hcmdpbjogMTVweDtcbiAgICAgICAgb3V0bGluZTogbm9uZTtcbiAgICAgICAgd2lkdGg6IDMwcmVtO1xuICAgIH1cblxuPC9zdHlsZT5cblxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQTJGQyxHQUFHLGNBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZ0JBQWdCLENBQUUsT0FBTyxDQUN6QixLQUFLLENBQUUsS0FBSyxDQUNaLGVBQWUsQ0FBRSxNQUFNLEFBQ3hCLENBQUMsQUFDRSxxQkFBTyxDQUFDLEFBQ1YsT0FBTyxDQUFFLElBQUksQ0FDUCxxQkFBcUIsQ0FBRSxPQUFPLFFBQVEsQ0FBQyxDQUFDLE9BQU8sS0FBSyxDQUFDLENBQUMsR0FBRyxDQUFDLENBQUMsQ0FDM0QsZUFBZSxDQUFFLE1BQU0sQ0FDN0IsR0FBRyxDQUFFLElBQUksQ0FDSCxNQUFNLENBQUUsSUFBSSxDQUNsQixLQUFLLENBQUUsSUFBSSxDQUNYLFVBQVUsQ0FBRSxLQUFLLEFBQ2YsQ0FBQyxBQUNKLEtBQUssY0FBQyxDQUFDLEFBQ04sT0FBTyxDQUFFLElBQUksQ0FDYixxQkFBcUIsQ0FBRSxLQUFLLENBQUMsS0FBSyxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQzlDLEdBQUcsQ0FBRSxJQUFJLENBQ1QsS0FBSyxDQUFFLElBQUksQ0FDWCxNQUFNLENBQUUsSUFBSSxDQUNaLGVBQWUsQ0FBRSxNQUFNLEFBQ3hCLENBQUMsQUFDRCxLQUFLLGNBQUMsQ0FBQyxBQUNOLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLElBQUksQ0FDWixPQUFPLENBQUUsSUFBSSxDQUNiLFVBQVUsQ0FBRSxNQUFNLEFBQ25CLENBQUMsQUFDRCxPQUFPLGNBQUMsQ0FBQyxBQUNSLE1BQU0sQ0FBRSxJQUFJLENBQ1osZ0JBQWdCLENBQUUsTUFBTSxDQUN4QixLQUFLLENBQUUsS0FBSyxDQUNaLE9BQU8sQ0FBRSxJQUFJLEFBQ2QsQ0FBQyxBQUNELFVBQVUsY0FBQyxDQUFDLEFBQ0wsYUFBYSxDQUFFLE1BQU0sQ0FDckIsS0FBSyxDQUFFLEtBQUssQ0FDWixVQUFVLENBQUUsTUFBTSxBQUN0QixDQUFDLEFBQ0QsYUFBYSxjQUFDLENBQUMsQUFDWCxhQUFhLENBQUUsR0FBRyxDQUNsQixNQUFNLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQ3ZCLE9BQU8sQ0FBRSxJQUFJLENBQ2IsU0FBUyxDQUFFLElBQUksQ0FDZixNQUFNLENBQUUsSUFBSSxDQUNaLE9BQU8sQ0FBRSxJQUFJLENBQ2IsS0FBSyxDQUFFLEtBQUssQUFDaEIsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[9] = list[i];
	return child_ctx;
}

function get_each_context_1(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[12] = list[i];
	return child_ctx;
}

// (74:1) {#each buttons as button}
function create_each_block_1(ctx) {
	let button;
	let t_value = /*button*/ ctx[12].order + "";
	let t;
	let dispose;

	function click_handler(...args) {
		return /*click_handler*/ ctx[7](/*button*/ ctx[12], ...args);
	}

	const block = {
		c: function create() {
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BUTTON", { id: true, class: true });
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button_nodes, t_value);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "id", "btn");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "class", "button svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 74, 2, 1940);
		},
		m: function mount(target, anchor, remount) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, button, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button, t);
			if (remount) dispose();
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button, "click", click_handler, false, false, false);
		},
		p: function update(new_ctx, dirty) {
			ctx = new_ctx;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(button);
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block_1.name,
		type: "each",
		source: "(74:1) {#each buttons as button}",
		ctx
	});

	return block;
}

// (85:2) {:else}
function create_else_block(ctx) {
	let current;
	const loader = new _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(loader.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(loader.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(loader, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(loader.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(loader.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(loader, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(85:2) {:else}",
		ctx
	});

	return block;
}

// (83:2) {#each searched as item}
function create_each_block(ctx) {
	let current;

	const world_1 = new _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: { item: /*item*/ ctx[9] },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(world_1.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(world_1.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(world_1, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const world_1_changes = {};
			if (dirty & /*searched*/ 1) world_1_changes.item = /*item*/ ctx[9];
			world_1.$set(world_1_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(world_1.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(world_1.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(world_1, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(83:2) {#each searched as item}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let t0;
	let div2;
	let label;
	let t1;
	let t2;
	let div0;
	let t3;
	let div1;
	let input;
	let t4;
	let section;
	let current;
	let dispose;
	let each_value_1 = /*buttons*/ ctx[4];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value_1);
	let each_blocks_1 = [];

	for (let i = 0; i < each_value_1.length; i += 1) {
		each_blocks_1[i] = create_each_block_1(get_each_context_1(ctx, each_value_1, i));
	}

	let each_value = /*searched*/ ctx[0];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	let each1_else = null;

	if (!each_value.length) {
		each1_else = create_else_block(ctx);
	}

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("label");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Sort by:");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].c();
			}

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			if (each1_else) {
				each1_else.c();
			}

			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1136c5u\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "LABEL", { for: true, class: true });
			var label_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(label);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(label_nodes, "Sort by:");
			label_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true, id: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].l(div0_nodes);
			}

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "INPUT", {
				autocomplete: true,
				class: true,
				type: true,
				placeholder: true
			});

			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(section_nodes);
			}

			if (each1_else) {
				each1_else.l(section_nodes);
			}

			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "Corona information";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "for", "btn");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(label, file, 71, 1, 1845);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "sort svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "id", "myDiv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 72, 1, 1881);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "autocomplete", "off");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "class", "search-input svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "type", "search");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "placeholder", "Search after country");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input, file, 79, 8, 2095);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "searchbar svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 78, 1, 2063);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 81, 1, 2265);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 70, 0, 1838);
		},
		m: function mount(target, anchor, remount) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, label);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div0);

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].m(div0, null);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, input);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*search*/ ctx[2]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, section);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(section, null);
			}

			if (each1_else) {
				each1_else.m(section, null);
			}

			current = true;
			if (remount) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);

			dispose = [
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "input", /*input_input_handler*/ ctx[8]),
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "input", Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prevent_default"])(/*filterResult*/ ctx[3]), false, true, false)
			];
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*order, buttons*/ 18) {
				each_value_1 = /*buttons*/ ctx[4];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value_1);
				let i;

				for (i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks_1[i]) {
						each_blocks_1[i].p(child_ctx, dirty);
					} else {
						each_blocks_1[i] = create_each_block_1(child_ctx);
						each_blocks_1[i].c();
						each_blocks_1[i].m(div0, null);
					}
				}

				for (; i < each_blocks_1.length; i += 1) {
					each_blocks_1[i].d(1);
				}

				each_blocks_1.length = each_value_1.length;
			}

			if (dirty & /*search*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*search*/ ctx[2]);
			}

			if (dirty & /*searched*/ 1) {
				each_value = /*searched*/ ctx[0];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(section, null);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();

				if (each_value.length) {
					if (each1_else) {
						each1_else.d(1);
						each1_else = null;
					}
				} else if (!each1_else) {
					each1_else = create_else_block(ctx);
					each1_else.c();
					each1_else.m(section, null);
				}
			}
		},
		i: function intro(local) {
			if (current) return;

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			current = true;
		},
		o: function outro(local) {
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks_1, detaching);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
			if (each1_else) each1_else.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	const favorites = [];
	let world = [];
	let searched = [];

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		await fetch(`https://api.covid19api.com/summary`).then(response => response.json()).then(json => {
			// World
			$$invalidate(6, world = json.Countries);

			$$invalidate(0, searched = world);
		}).catch(err => console.log(err));
	});

	let order = "title";
	let search = "";

	const filterResult = () => {
		if (search === " ") {
			$$invalidate(0, searched = world);
		} else {
			$$invalidate(0, searched = world.filter(world => world.Country.toLowerCase().includes(search.toLowerCase())));
		}
	};

	/*
	const btnContainer = document.querySelector("#myDiv");
	const btns = btnContainer.querySelector(".btn")
	for(var i = 0; i < btns.length; i++) {
		btns[i].addEventListener("click", function() {
			var current = document.getElementsByClassName("active");

			if(current.length > 0) {
				current[0].className = current[0].className.replace(" active", "");
			}

			this.className += " active"
		})
	}

*/
	const buttons = [
		{ order: "Title", orderType: "title" },
		{ order: "Death", orderType: "death" },
		{ order: "Infected", orderType: "infected" },
		{
			order: "Recovered",
			orderType: "recovered"
		}
	];

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", $$slots, []);
	const click_handler = button => $$invalidate(1, order = `${button.orderType}`);

	function input_input_handler() {
		search = this.value;
		$$invalidate(2, search);
	}

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		Loader: _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__["default"],
		World: _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__["default"],
		favorites,
		world,
		searched,
		order,
		search,
		filterResult,
		buttons
	});

	$$self.$inject_state = $$props => {
		if ("world" in $$props) $$invalidate(6, world = $$props.world);
		if ("searched" in $$props) $$invalidate(0, searched = $$props.searched);
		if ("order" in $$props) $$invalidate(1, order = $$props.order);
		if ("search" in $$props) $$invalidate(2, search = $$props.search);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*order, world*/ 66) {
			$: switch (order) {
				case "title":
					$$invalidate(0, searched = world.sort((a, b) => a.Country > b.Country ? 1 : -1));
					break;
				case "death":
					$$invalidate(0, searched = world.sort((a, b) => a.TotalDeaths < b.TotalDeaths ? 1 : -1));
					break;
				case "infected":
					$$invalidate(0, searched = world.sort((a, b) => a.TotalConfirmed < b.TotalConfirmed ? 1 : -1));
					break;
				case "recovered":
					$$invalidate(0, searched = world.sort((a, b) => a.TotalRecovered < b.TotalRecovered ? 1 : -1));
					break;
			}
		}
	};

	return [
		searched,
		order,
		search,
		filterResult,
		buttons,
		favorites,
		world,
		click_handler,
		input_input_handler
	];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-mj86kf-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { favorites: 5 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}

	get favorites() {
		return this.$$.ctx[5];
	}

	set favorites(value) {
		throw new Error("<Routes>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9Xb3JsZC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9pbmRleC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lCQVFvQixHQUFJLElBQUMsT0FBTzs7Ozs7eUJBQ1MsR0FBSSxJQUFDLGNBQWMsQ0FBQyxRQUFRLEdBQUcsT0FBTyxDQUFDLHVCQUF1QixFQUFFLEdBQUc7Ozs7O3lCQUN4RSxHQUFJLElBQUMsV0FBVyxDQUFDLFFBQVEsR0FBRyxPQUFPLENBQUMsdUJBQXVCLEVBQUUsR0FBRzs7Ozs7eUJBQzNELEdBQUksSUFBQyxjQUFjLENBQUMsUUFBUSxHQUFHLE9BQU8sQ0FBQyx1QkFBdUIsRUFBRSxHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrREFIeEYsR0FBSSxJQUFDLE9BQU87K0RBQ1MsR0FBSSxJQUFDLGNBQWMsQ0FBQyxRQUFRLEdBQUcsT0FBTyxDQUFDLHVCQUF1QixFQUFFLEdBQUc7K0RBQ3hFLEdBQUksSUFBQyxXQUFXLENBQUMsUUFBUSxHQUFHLE9BQU8sQ0FBQyx1QkFBdUIsRUFBRSxHQUFHOytEQUMzRCxHQUFJLElBQUMsY0FBYyxDQUFDLFFBQVEsR0FBRyxPQUFPLENBQUMsdUJBQXVCLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BVGpHLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ0drQjtBQUNnQjtBQUNGOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBCQW1Fb0MsR0FBTSxLQUFDLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzJCQVMvRSxHQUFJOzs7Ozs7Ozs7Ozs7Ozs7OzsrREFBSixHQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Z0NBVlosR0FBTzs7OztrQ0FBWixNQUFJOzs7OytCQVNFLEdBQVE7Ozs7Z0NBQWIsTUFBSTs7Ozs7Ozs7OztpQkFBSixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzZGQUg2RyxHQUFNOzs7Ozs7Ozs7Ozs7Ozs7OztnTEFBMkIsR0FBWTs7Ozs7K0JBTjFKLEdBQU87Ozs7aUNBQVosTUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozt3Q0FBSixNQUFJOzs7OzhGQU04RyxHQUFNOzs7OzhCQUdsSCxHQUFROzs7OytCQUFiLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7d0JBQUosTUFBSTs7Ozs7O21CQUFKLE1BQUk7Ozs7Ozs7Ozs7Ozs7OztrQ0FBSixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BMUVNLFNBQVM7S0FHbEIsS0FBSztLQUNMLFFBQVE7O0NBRVQsc0RBQU87UUFDSCxLQUFLLHVDQUNWLElBQUksQ0FBRSxRQUFRLElBQUksUUFBUSxDQUFDLElBQUksSUFDekIsSUFBSSxDQUFFLElBQUk7O21CQUVoQixLQUFLLEdBQUcsSUFBSSxDQUFDLFNBQVM7O21CQUN0QixRQUFRLEdBQUcsS0FBSztLQUVULEtBQUssQ0FBRSxHQUFHLElBQUssT0FBTyxDQUFDLEdBQUcsQ0FBQyxHQUFHOzs7S0FHbkMsS0FBSyxHQUFHLE9BQU87S0FRWCxNQUFNLEdBQUcsRUFBRTs7T0FDVixZQUFZO01BQ2pCLE1BQU0sS0FBSyxHQUFHO21CQUNoQixRQUFRLEdBQUcsS0FBSzs7bUJBRWhCLFFBQVEsR0FBRyxLQUFLLENBQUMsTUFBTSxDQUFFLEtBQUssSUFBSSxLQUFLLENBQUMsT0FBTyxDQUFDLFdBQVcsR0FBRyxRQUFRLENBQUMsTUFBTSxDQUFDLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09Bc0JyRixPQUFPO0lBQ1gsS0FBSyxFQUFFLE9BQU8sRUFBRSxTQUFTLEVBQUUsT0FBTztJQUNsQyxLQUFLLEVBQUUsT0FBTyxFQUFFLFNBQVMsRUFBRSxPQUFPO0lBQ2xDLEtBQUssRUFBRSxVQUFVLEVBQUUsU0FBUyxFQUFFLFVBQVU7O0dBQ3hDLEtBQUssRUFBRSxXQUFXO0dBQUUsU0FBUyxFQUFFLFdBQVc7Ozs7Ozs7Ozs7OztpREFVSyxLQUFLLE1BQU0sTUFBTSxDQUFDLFNBQVM7OztFQUt3QyxNQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7R0FyRHZILENBQUMsVUFBVSxLQUFLO1NBQ2IsT0FBTztxQkFBRSxRQUFRLEdBQUcsS0FBSyxDQUFDLElBQUksRUFBRyxDQUFDLEVBQUMsQ0FBQyxLQUFLLENBQUMsQ0FBQyxPQUFPLEdBQUcsQ0FBQyxDQUFDLE9BQU8sR0FBRyxDQUFDLElBQUksQ0FBQzs7U0FDN0QsT0FBTztxQkFBRSxRQUFRLEdBQUcsS0FBSyxDQUFDLElBQUksRUFBRyxDQUFDLEVBQUMsQ0FBQyxLQUFLLENBQUMsQ0FBQyxXQUFXLEdBQUcsQ0FBQyxDQUFDLFdBQVcsR0FBRyxDQUFDLElBQUksQ0FBQzs7U0FDL0UsVUFBVTtxQkFBRSxRQUFRLEdBQUcsS0FBSyxDQUFDLElBQUksRUFBRyxDQUFDLEVBQUMsQ0FBQyxLQUFLLENBQUMsQ0FBQyxjQUFjLEdBQUcsQ0FBQyxDQUFDLGNBQWMsR0FBRyxDQUFDLElBQUksQ0FBQzs7U0FDeEYsV0FBVztxQkFBRSxRQUFRLEdBQUcsS0FBSyxDQUFDLElBQUksRUFBRyxDQUFDLEVBQUMsQ0FBQyxLQUFLLENBQUMsQ0FBQyxjQUFjLEdBQUcsQ0FBQyxDQUFDLGNBQWMsR0FBRyxDQUFDLElBQUksQ0FBQyIsImZpbGUiOiJkOThkNjI3ZTIxYmUzN2U2OTMxZC9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG5cbmV4cG9ydCBsZXQgaXRlbVxuXG48L3NjcmlwdD5cblxuXG48YXJ0aWNsZT5cblx0PGgxIGNsYXNzPVwid2hpdGVcIj57aXRlbS5Db3VudHJ5fTwvaDE+XG5cdDxwIGNsYXNzPVwidGV4dCBvcmFuZ2VcIj5Ub3RhbCBpbmZlY3RlZDoge2l0ZW0uVG90YWxDb25maXJtZWQudG9TdHJpbmcoKS5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCBcIixcIil9PC9wPlxuXHQ8cCBjbGFzcz1cInRleHQgcmVkXCI+VG90YWwgZGVhdGhzOiB7aXRlbS5Ub3RhbERlYXRocy50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG5cdDxwIGNsYXNzPVwidGV4dCBncmVlblwiPlRvdGFsIHJlY292ZXJlZDoge2l0ZW0uVG90YWxSZWNvdmVyZWQudG9TdHJpbmcoKS5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCBcIixcIil9PC9wPlxuPC9hcnRpY2xlPlx0XHRcblxuPHN0eWxlPlxuXHRhcnRpY2xlIHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiByZ2JhKDQsIDQsIDQsIC42KTtcblx0XHRwYWRkaW5nOiAxcmVtO1xuXHRcdGJvcmRlci1yYWRpdXM6IDEwcHg7XG5cdFx0ZGlzcGxheTogZ3JpZDtcblx0XHRtYXgtd2lkdGg6IDE1cmVtO1xuXHRcdG1heC1oZWlnaHQ6IDE2cmVtO1xuXHR9XG5cdGFydGljbGU6aG92ZXIge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHJnYmEoNCwgNCwgNCwgLjIpO1xuXHR9XG5cdC53aGl0ZSB7XG5cdFx0Y29sb3I6IHdoaXRlO1xuXHRcdHRleHQtYWxpZ246IGNlbnRlcjtcblx0XHRmb250LXNpemU6IDEuOHJlbTtcblx0fVxuXHQuZ3JlZW4ge1xuXHRcdGNvbG9yOiBncmVlbjtcblx0fVxuXHQucmVkIHtcblx0XHRjb2xvcjogcmVkO1xuXHR9XG5cdC5vcmFuZ2Uge1xuXHRcdGNvbG9yOiBvcmFuZ2U7XG5cdH1cbjwvc3R5bGU+IiwiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+Q29yb25hIGluZm9ybWF0aW9uPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxzY3JpcHQ+XG5cdGltcG9ydCB7IG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCJcblx0aW1wb3J0IExvYWRlciBmcm9tIFwiLi4vY29tcG9uZW50cy9Mb2FkZXIuc3ZlbHRlXCJcblx0aW1wb3J0IFdvcmxkIGZyb20gXCIuLi9jb21wb25lbnRzL1dvcmxkLnN2ZWx0ZVwiXG5cdGV4cG9ydCBjb25zdCBmYXZvcml0ZXMgPSBbXVxuXG5cblx0bGV0IHdvcmxkID0gW11cblx0bGV0IHNlYXJjaGVkID0gW11cblxuICAgIG9uTW91bnQoIGFzeW5jICgpID0+IHtcblx0XHRhd2FpdCBmZXRjaChgaHR0cHM6Ly9hcGkuY292aWQxOWFwaS5jb20vc3VtbWFyeWApXG5cdFx0LnRoZW4oIHJlc3BvbnNlID0+IHJlc3BvbnNlLmpzb24oKSApXG4gICAgICAgIC50aGVuKCBqc29uID0+IHtcblx0XHRcdC8vIFdvcmxkXG5cdFx0XHR3b3JsZCA9IGpzb24uQ291bnRyaWVzXG5cdFx0XHRzZWFyY2hlZCA9IHdvcmxkXG4gICAgICAgIH1cbiAgICAgICAgKS5jYXRjaCgoZXJyKSA9PiBjb25zb2xlLmxvZyhlcnIpKVxuXHR9IClcblxuXHRsZXQgb3JkZXIgPSBcInRpdGxlXCJcbiAgICAkOiAgc3dpdGNoKG9yZGVyKXsgICAgICBcblx0XHRjYXNlICd0aXRsZSc6IHNlYXJjaGVkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Db3VudHJ5ID4gYi5Db3VudHJ5ID8gMSA6IC0xKTticmVha1xuICAgICAgICAgICAgY2FzZSAnZGVhdGgnOiBzZWFyY2hlZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxEZWF0aHMgPCBiLlRvdGFsRGVhdGhzID8gMSA6IC0xKTsgYnJlYWtcbiAgICAgICAgICAgIGNhc2UgJ2luZmVjdGVkJzogc2VhcmNoZWQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLlRvdGFsQ29uZmlybWVkIDwgYi5Ub3RhbENvbmZpcm1lZCA/IDEgOiAtMSk7IGJyZWFrXG4gICAgICAgICAgICBjYXNlICdyZWNvdmVyZWQnOiBzZWFyY2hlZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxSZWNvdmVyZWQgPCBiLlRvdGFsUmVjb3ZlcmVkID8gMSA6IC0xKTsgYnJlYWtcblx0fVxuXG5cdCAgICBsZXQgc2VhcmNoID0gXCJcIlxuICAgIGNvbnN0IGZpbHRlclJlc3VsdCA9ICgpID0+IHtcblx0XHRpZihzZWFyY2ggPT09IFwiIFwiKXtcblx0XHRcdHNlYXJjaGVkID0gd29ybGRcblx0XHR9ZWxzZSB7XG5cdFx0XHRzZWFyY2hlZCA9IHdvcmxkLmZpbHRlciggd29ybGQgPT4gd29ybGQuQ291bnRyeS50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKHNlYXJjaC50b0xvd2VyQ2FzZSgpKSlcblx0XHR9XG4gICAgfVxuXG5cbi8qXG5cdGNvbnN0IGJ0bkNvbnRhaW5lciA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIjbXlEaXZcIik7XG5cdGNvbnN0IGJ0bnMgPSBidG5Db250YWluZXIucXVlcnlTZWxlY3RvcihcIi5idG5cIilcblx0Zm9yKHZhciBpID0gMDsgaSA8IGJ0bnMubGVuZ3RoOyBpKyspIHtcblx0XHRidG5zW2ldLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCBmdW5jdGlvbigpIHtcblx0XHRcdHZhciBjdXJyZW50ID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZShcImFjdGl2ZVwiKTtcblxuXHRcdFx0aWYoY3VycmVudC5sZW5ndGggPiAwKSB7XG5cdFx0XHRcdGN1cnJlbnRbMF0uY2xhc3NOYW1lID0gY3VycmVudFswXS5jbGFzc05hbWUucmVwbGFjZShcIiBhY3RpdmVcIiwgXCJcIik7XG5cdFx0XHR9XG5cblx0XHRcdHRoaXMuY2xhc3NOYW1lICs9IFwiIGFjdGl2ZVwiXG5cdFx0fSlcblx0fVxuXG4qL1xuXG5cdGNvbnN0IGJ1dHRvbnMgPSBbXG5cdFx0e29yZGVyOiBcIlRpdGxlXCIsIG9yZGVyVHlwZTogXCJ0aXRsZVwifSxcblx0XHR7b3JkZXI6IFwiRGVhdGhcIiwgb3JkZXJUeXBlOiBcImRlYXRoXCJ9LFxuXHRcdHtvcmRlcjogXCJJbmZlY3RlZFwiLCBvcmRlclR5cGU6IFwiaW5mZWN0ZWRcIn0sXG5cdFx0e29yZGVyOiBcIlJlY292ZXJlZFwiLCBvcmRlclR5cGU6IFwicmVjb3ZlcmVkXCJ9XG5cblx0XVxuXG48L3NjcmlwdD5cblxuPGRpdj5cblx0PGxhYmVsIGZvcj1cImJ0blwiID5Tb3J0IGJ5OjwvbGFiZWw+XG5cdDxkaXYgY2xhc3M9XCJzb3J0XCIgaWQ9XCJteURpdlwiPlxuXHR7I2VhY2ggYnV0dG9ucyBhcyBidXR0b259XG5cdFx0PGJ1dHRvbiBpZD1cImJ0blwiIGNsYXNzPVwiYnV0dG9uXCIgb246Y2xpY2s9eygpID0+IG9yZGVyID0gYCR7YnV0dG9uLm9yZGVyVHlwZX1gfSA+e2J1dHRvbi5vcmRlcn08L2J1dHRvbj5cblx0ey9lYWNofVxuXG5cdDwvZGl2PlxuXHQ8ZGl2IGNsYXNzPVwic2VhcmNoYmFyXCI+XG4gICAgICAgIDxpbnB1dCBhdXRvY29tcGxldGU9XCJvZmZcIiAgY2xhc3M9XCJzZWFyY2gtaW5wdXRcIiB0eXBlPVwic2VhcmNoXCIgcGxhY2Vob2xkZXI9XCJTZWFyY2ggYWZ0ZXIgY291bnRyeVwiIGJpbmQ6dmFsdWU9e3NlYXJjaH0gb246aW5wdXR8cHJldmVudERlZmF1bHQ9e2ZpbHRlclJlc3VsdH0vPlxuICAgIDwvZGl2PlxuXHQ8c2VjdGlvbj5cblx0XHR7I2VhY2ggc2VhcmNoZWQgYXMgaXRlbX1cblx0XHRcdDxXb3JsZCBpdGVtPXtpdGVtfSAvPlxuXHRcdHs6ZWxzZX1cblx0XHRcdDxMb2FkZXIgLz5cblx0XHR7L2VhY2h9ICAgXG5cdDwvc2VjdGlvbj5cbjwvZGl2PlxuXG48c3R5bGU+XG5cdGRpdiB7XG5cdFx0ZGlzcGxheTogZ3JpZDtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiAjMWIxYjMwO1xuXHRcdHdpZHRoOiAxMDB2dztcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0fVxuICAgIHNlY3Rpb257XG5cdFx0ZGlzcGxheTogZ3JpZDtcbiAgICAgICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoYXV0by1maXQsIG1pbm1heCgyMDBweCwgMWZyKSk7XG4gICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGdhcDogMnJlbTtcbiAgICAgICAgbWFyZ2luOiBhdXRvO1xuXHRcdHdpZHRoOiA3MHZ3O1xuXHRcdG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgIH1cblx0LnNvcnQge1xuXHRcdGRpc3BsYXk6IGdyaWQ7XG5cdFx0Z3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxMDBweCAxMDBweCAxMDBweCAxMDBweDtcblx0XHRnYXA6IDEwcHg7XG5cdFx0d2lkdGg6IDkwdnc7XG5cdFx0bWFyZ2luOiBhdXRvO1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHR9XG5cdGxhYmVsIHtcblx0XHRjb2xvcjogd2hpdGU7XG5cdFx0bWFyZ2luOiBhdXRvO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdFx0dGV4dC1hbGlnbjogMS45cmVtO1xuXHR9XG5cdC5idXR0b24ge1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiBpbmRpZ287XG5cdFx0Y29sb3I6IHdoaXRlO1xuXHRcdG91dGxpbmU6IG5vbmU7XG5cdH1cblx0LnNlYXJjaGJhciB7XG4gICAgICAgIGFsaWduLWNvbnRlbnQ6IGNlbnRlcjtcbiAgICAgICAgd2lkdGg6IDEwMHZ3O1xuICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgfVxuICAgIC5zZWFyY2gtaW5wdXQge1xuICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7XG4gICAgICAgIGJvcmRlcjogMXB4IHNvbGlkIGJsYWNrO1xuICAgICAgICBwYWRkaW5nOiAxcmVtO1xuICAgICAgICBmb250LXNpemU6IDIwcHg7XG4gICAgICAgIG1hcmdpbjogMTVweDtcbiAgICAgICAgb3V0bGluZTogbm9uZTtcbiAgICAgICAgd2lkdGg6IDMwcmVtO1xuICAgIH1cblxuPC9zdHlsZT5cblxuIl0sInNvdXJjZVJvb3QiOiIifQ==