(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/Loader.svelte":
/*!**************************************!*\
  !*** ./src/components/Loader.svelte ***!
  \**************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/Loader.svelte generated by Svelte v3.22.2 */


const file = "src/components/Loader.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-145waro-style";
	style.textContent = ".spinner.svelte-145waro.svelte-145waro{width:50px;height:40px;text-align:center;font-size:10px}.spinner.svelte-145waro>div.svelte-145waro{background-color:white;height:100%;width:6px;display:inline-block;animation:svelte-145waro-sk-stretchdelay 1.2s infinite ease-in-out}.spinner.svelte-145waro .rect2.svelte-145waro{animation-delay:-1.1s}.spinner.svelte-145waro .rect3.svelte-145waro{animation-delay:-1.0s}.spinner.svelte-145waro .rect4.svelte-145waro{-webkit-animation-delay:-0.9s;animation-delay:-0.9s}.spinner.svelte-145waro .rect5.svelte-145waro{animation-delay:-0.8s}@keyframes svelte-145waro-sk-stretchdelay{0%,40%,100%{transform:scaleY(0.4)}20%{transform:scaleY(1.0)}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTG9hZGVyLnN2ZWx0ZSIsInNvdXJjZXMiOlsiTG9hZGVyLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyIgICAgICBcbiAgICAgIDxkaXYgY2xhc3M9XCJzcGlubmVyXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyZWN0MVwiPjwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicmVjdDJcIj48L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJlY3QzXCI+PC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyZWN0NFwiPjwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicmVjdDVcIj48L2Rpdj5cbiAgICAgIDwvZGl2PlxuXG48c3R5bGU+XG4gIC5zcGlubmVyIHtcbiAgICB3aWR0aDogNTBweDtcbiAgICBoZWlnaHQ6IDQwcHg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGZvbnQtc2l6ZTogMTBweDtcbiAgfVxuXG4gIC5zcGlubmVyID4gZGl2IHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcbiAgICBoZWlnaHQ6IDEwMCU7XG4gICAgd2lkdGg6IDZweDtcbiAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gICAgYW5pbWF0aW9uOiBzay1zdHJldGNoZGVsYXkgMS4ycyBpbmZpbml0ZSBlYXNlLWluLW91dDtcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0MiB7XG4gICAgYW5pbWF0aW9uLWRlbGF5OiAtMS4xcztcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0MyB7XG4gICAgYW5pbWF0aW9uLWRlbGF5OiAtMS4wcztcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0NCB7XG4gICAgLXdlYmtpdC1hbmltYXRpb24tZGVsYXk6IC0wLjlzO1xuICAgIGFuaW1hdGlvbi1kZWxheTogLTAuOXM7XG4gIH1cblxuICAuc3Bpbm5lciAucmVjdDUge1xuICAgIGFuaW1hdGlvbi1kZWxheTogLTAuOHM7XG4gIH1cblxuXG4gIEBrZXlmcmFtZXMgc2stc3RyZXRjaGRlbGF5IHtcbiAgICAwJSwgNDAlLCAxMDAlIHtcbiAgICAgIHRyYW5zZm9ybTogc2NhbGVZKDAuNCk7XG4gICAgfSAgMjAlIHtcbiAgICAgIHRyYW5zZm9ybTogc2NhbGVZKDEuMCk7XG4gICAgfVxuICB9XG48L3N0eWxlPiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFVRSxRQUFRLDhCQUFDLENBQUMsQUFDUixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osVUFBVSxDQUFFLE1BQU0sQ0FDbEIsU0FBUyxDQUFFLElBQUksQUFDakIsQ0FBQyxBQUVELHVCQUFRLENBQUcsR0FBRyxlQUFDLENBQUMsQUFDZCxnQkFBZ0IsQ0FBRSxLQUFLLENBQ3ZCLE1BQU0sQ0FBRSxJQUFJLENBQ1osS0FBSyxDQUFFLEdBQUcsQ0FDVixPQUFPLENBQUUsWUFBWSxDQUNyQixTQUFTLENBQUUsOEJBQWUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLFdBQVcsQUFDdEQsQ0FBQyxBQUVELHVCQUFRLENBQUMsTUFBTSxlQUFDLENBQUMsQUFDZixlQUFlLENBQUUsS0FBSyxBQUN4QixDQUFDLEFBRUQsdUJBQVEsQ0FBQyxNQUFNLGVBQUMsQ0FBQyxBQUNmLGVBQWUsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFFRCx1QkFBUSxDQUFDLE1BQU0sZUFBQyxDQUFDLEFBQ2YsdUJBQXVCLENBQUUsS0FBSyxDQUM5QixlQUFlLENBQUUsS0FBSyxBQUN4QixDQUFDLEFBRUQsdUJBQVEsQ0FBQyxNQUFNLGVBQUMsQ0FBQyxBQUNmLGVBQWUsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFHRCxXQUFXLDhCQUFnQixDQUFDLEFBQzFCLEVBQUUsQ0FBRSxHQUFHLENBQUUsSUFBSSxBQUFDLENBQUMsQUFDYixTQUFTLENBQUUsT0FBTyxHQUFHLENBQUMsQUFDeEIsQ0FBQyxBQUFFLEdBQUcsQUFBQyxDQUFDLEFBQ04sU0FBUyxDQUFFLE9BQU8sR0FBRyxDQUFDLEFBQ3hCLENBQUMsQUFDSCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div5;
	let div0;
	let t0;
	let div1;
	let t1;
	let div2;
	let t2;
	let div3;
	let t3;
	let div4;

	const block = {
		c: function create() {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			this.h();
		},
		l: function claim(nodes) {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "rect1 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 2, 8, 43);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "rect2 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 3, 8, 77);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "rect3 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 4, 8, 111);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "rect4 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 5, 8, 145);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "rect5 svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 6, 8, 179);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "spinner svelte-145waro");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 1, 6, 13);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div5, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div4);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div5);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Loader> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Loader", $$slots, []);
	return [];
}

class Loader extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-145waro-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Loader",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Loader);

/***/ }),

/***/ "./src/components/World.svelte":
/*!*************************************!*\
  !*** ./src/components/World.svelte ***!
  \*************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/World.svelte generated by Svelte v3.22.2 */


const file = "src/components/World.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1fghkfk-style";
	style.textContent = "article.svelte-1fghkfk{background-color:rgba(4, 4, 4, .6);padding:1rem}article.svelte-1fghkfk:hover{background-color:rgba(4, 4, 4, .2)}.white.svelte-1fghkfk{color:white}.green.svelte-1fghkfk{color:green}.red.svelte-1fghkfk{color:red}.orange.svelte-1fghkfk{color:orange}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiV29ybGQuc3ZlbHRlIiwic291cmNlcyI6WyJXb3JsZC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cblxuZXhwb3J0IGxldCBpdGVtXG5cbjwvc2NyaXB0PlxuXG5cbjxhcnRpY2xlPlxuXHQ8aDEgY2xhc3M9XCJ3aGl0ZVwiPntpdGVtLkNvdW50cnl9PC9oMT5cblx0PHAgY2xhc3M9XCJvcmFuZ2VcIj5Ub3RhbCBpbmZlY3RlZDoge2l0ZW0uVG90YWxDb25maXJtZWQudG9TdHJpbmcoKS5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCBcIixcIil9PC9wPlxuXHQ8cCBjbGFzcz1cInJlZFwiPlRvdGFsIGRlYXRoczoge2l0ZW0uVG90YWxEZWF0aHMudG9TdHJpbmcoKS5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCBcIixcIil9PC9wPlxuXHQ8cCBjbGFzcz1cImdyZWVuXCI+VG90YWwgcmVjb3ZlcmVkOiB7aXRlbS5Ub3RhbFJlY292ZXJlZC50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG48L2FydGljbGU+XHRcdFxuXG48c3R5bGU+XG5cdGFydGljbGUge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHJnYmEoNCwgNCwgNCwgLjYpO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdH1cblx0YXJ0aWNsZTpob3ZlciB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogcmdiYSg0LCA0LCA0LCAuMik7XG5cdH1cblx0LndoaXRlIHtcblx0XHRjb2xvcjogd2hpdGU7XG5cdH1cblx0LmdyZWVuIHtcblx0XHRjb2xvcjogZ3JlZW47XG5cdH1cblx0LnJlZCB7XG5cdFx0Y29sb3I6IHJlZDtcblx0fVxuXHQub3JhbmdlIHtcblx0XHRjb2xvcjogb3JhbmdlO1xuXHR9XG48L3N0eWxlPiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFlQyxPQUFPLGVBQUMsQ0FBQyxBQUNSLGdCQUFnQixDQUFFLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQ25DLE9BQU8sQ0FBRSxJQUFJLEFBQ2QsQ0FBQyxBQUNELHNCQUFPLE1BQU0sQUFBQyxDQUFDLEFBQ2QsZ0JBQWdCLENBQUUsS0FBSyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxFQUFFLENBQUMsQUFDcEMsQ0FBQyxBQUNELE1BQU0sZUFBQyxDQUFDLEFBQ1AsS0FBSyxDQUFFLEtBQUssQUFDYixDQUFDLEFBQ0QsTUFBTSxlQUFDLENBQUMsQUFDUCxLQUFLLENBQUUsS0FBSyxBQUNiLENBQUMsQUFDRCxJQUFJLGVBQUMsQ0FBQyxBQUNMLEtBQUssQ0FBRSxHQUFHLEFBQ1gsQ0FBQyxBQUNELE9BQU8sZUFBQyxDQUFDLEFBQ1IsS0FBSyxDQUFFLE1BQU0sQUFDZCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let article;
	let h1;
	let t0_value = /*item*/ ctx[0].Country + "";
	let t0;
	let t1;
	let p0;
	let t2;
	let t3_value = /*item*/ ctx[0].TotalConfirmed.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t3;
	let t4;
	let p1;
	let t5;
	let t6_value = /*item*/ ctx[0].TotalDeaths.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t6;
	let t7;
	let p2;
	let t8;
	let t9_value = /*item*/ ctx[0].TotalRecovered.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t9;

	const block = {
		c: function create() {
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("article");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total infected: ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total deaths: ");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t6_value);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total recovered: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t9_value);
			this.h();
		},
		l: function claim(nodes) {
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "ARTICLE", { class: true });
			var article_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(article);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, t0_value);
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Total infected: ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, t3_value);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Total deaths: ");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, t6_value);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "Total recovered: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, t9_value);
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			article_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "white svelte-1fghkfk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 8, 1, 50);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "orange svelte-1fghkfk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 9, 1, 89);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "red svelte-1fghkfk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 10, 1, 199);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p2, "class", "green svelte-1fghkfk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 11, 1, 301);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(article, "class", "svelte-1fghkfk");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(article, file, 7, 0, 39);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, article, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t9);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*item*/ 1 && t0_value !== (t0_value = /*item*/ ctx[0].Country + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, t0_value);
			if (dirty & /*item*/ 1 && t3_value !== (t3_value = /*item*/ ctx[0].TotalConfirmed.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, t3_value);
			if (dirty & /*item*/ 1 && t6_value !== (t6_value = /*item*/ ctx[0].TotalDeaths.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t6, t6_value);
			if (dirty & /*item*/ 1 && t9_value !== (t9_value = /*item*/ ctx[0].TotalRecovered.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t9, t9_value);
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(article);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { item } = $$props;
	const writable_props = ["item"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<World> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("World", $$slots, []);

	$$self.$set = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
	};

	$$self.$capture_state = () => ({ item });

	$$self.$inject_state = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [item];
}

class World extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1fghkfk-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { item: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "World",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*item*/ ctx[0] === undefined && !("item" in props)) {
			console.warn("<World> was created without expected prop 'item'");
		}
	}

	get item() {
		throw new Error("<World>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set item(value) {
		throw new Error("<World>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (World);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/Loader.svelte */ "./src/components/Loader.svelte");
/* harmony import */ var _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/World.svelte */ "./src/components/World.svelte");
/* src/routes/index.svelte generated by Svelte v3.22.2 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-1u2lue1-style";
	style.textContent = "div.svelte-1u2lue1{display:grid;background-color:#1b1b30;width:100vw;justify-content:center}section.svelte-1u2lue1{display:grid;grid-template-columns:repeat(5, 1fr);justify-content:center;gap:2rem;margin:auto;width:80vw;min-height:100vh}.sort.svelte-1u2lue1{height:10vh;display:grid;grid-template-columns:100px 100px 100px 100px;gap:10px;width:90vw;margin:auto;justify-content:center;padding:1rem}.button.svelte-1u2lue1{height:30px;background-color:indigo;color:white;outline:none}.searchbar.svelte-1u2lue1{align-content:center;width:100vw;text-align:center}.search-input.svelte-1u2lue1{border-radius:4px;border:1px solid black;padding:1rem;font-size:20px;margin:15px;outline:none;width:30rem}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+Q29yb25hIGluZm9ybWF0aW9uPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxzY3JpcHQ+XG5cdGltcG9ydCB7IG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCJcblx0aW1wb3J0IExvYWRlciBmcm9tIFwiLi4vY29tcG9uZW50cy9Mb2FkZXIuc3ZlbHRlXCJcblx0aW1wb3J0IFdvcmxkIGZyb20gXCIuLi9jb21wb25lbnRzL1dvcmxkLnN2ZWx0ZVwiXG5cblxuXHRsZXQgd29ybGQgPSBbXVxuXHRsZXQgc2VhcmNlaGQgPSBbXVxuXG5cblxuXG4gICAgb25Nb3VudCggYXN5bmMgKCkgPT4ge1xuXHRcdGF3YWl0IGZldGNoKGBodHRwczovL2FwaS5jb3ZpZDE5YXBpLmNvbS9zdW1tYXJ5YClcblx0XHQudGhlbiggcmVzcG9uc2UgPT4gcmVzcG9uc2UuanNvbigpIClcbiAgICAgICAgLnRoZW4oIGpzb24gPT4ge1xuXHRcdFx0Ly8gV29ybGRcblx0XHRcdHdvcmxkID0ganNvbi5Db3VudHJpZXNcblx0XHRcdHNlYXJjZWhkID0gd29ybGRcbiAgICAgICAgfVxuICAgICAgICApLmNhdGNoKChlcnIpID0+IGNvbnNvbGUubG9nKGVycikpXG5cdH0gKVxuXG5cdGxldCBvcmRlciA9IFwidGl0bGVcIlxuICAgICQ6ICBzd2l0Y2gob3JkZXIpeyAgICAgIFxuXHRcdGNhc2UgJ3RpdGxlJzogd29ybGQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLkNvdW50cnkgPiBiLkNvdW50cnkgPyAxIDogLTEpO2JyZWFrXG4gICAgICAgICAgICBjYXNlICdkZWF0aCc6IHdvcmxkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Ub3RhbERlYXRocyA8IGIuVG90YWxEZWF0aHMgPyAxIDogLTEpOyBicmVha1xuICAgICAgICAgICAgY2FzZSAnaW5mZWN0ZWQnOiB3b3JsZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxDb25maXJtZWQgPCBiLlRvdGFsQ29uZmlybWVkID8gMSA6IC0xKTsgYnJlYWtcbiAgICAgICAgICAgIGNhc2UgJ3JlY292ZXJlZCc6IHdvcmxkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Ub3RhbFJlY292ZXJlZCA8IGIuVG90YWxSZWNvdmVyZWQgPyAxIDogLTEpOyBicmVha1xuXHR9XG5cblx0ICAgIGxldCBzZWFyY2ggPSBcIlwiXG4gICAgY29uc3QgZmlsdGVyUmVzdWx0ID0gKCkgPT4ge1xuICAgICAgICBzZWFyY2hlZCA9IHdvcmxkLmZpbHRlciggd29ybGQgPT4gd29ybGQuQ291bnRyeS50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKHNlYXJjaC50b0xvd2VyQ2FzZSgpKSlcbiAgICB9XG5cblxuLypcblx0Y29uc3QgYnRuQ29udGFpbmVyID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIiNteURpdlwiKTtcblx0Y29uc3QgYnRucyA9IGJ0bkNvbnRhaW5lci5xdWVyeVNlbGVjdG9yKFwiLmJ0blwiKVxuXHRmb3IodmFyIGkgPSAwOyBpIDwgYnRucy5sZW5ndGg7IGkrKykge1xuXHRcdGJ0bnNbaV0uYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsIGZ1bmN0aW9uKCkge1xuXHRcdFx0dmFyIGN1cnJlbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5Q2xhc3NOYW1lKFwiYWN0aXZlXCIpO1xuXG5cdFx0XHRpZihjdXJyZW50Lmxlbmd0aCA+IDApIHtcblx0XHRcdFx0Y3VycmVudFswXS5jbGFzc05hbWUgPSBjdXJyZW50WzBdLmNsYXNzTmFtZS5yZXBsYWNlKFwiIGFjdGl2ZVwiLCBcIlwiKTtcblx0XHRcdH1cblxuXHRcdFx0dGhpcy5jbGFzc05hbWUgKz0gXCIgYWN0aXZlXCJcblx0XHR9KVxuXHR9XG5cbiovXG5cblx0Y29uc3QgYnV0dG9ucyA9IFtcblx0XHR7b3JkZXI6IFwiVGl0bGVcIiwgb3JkZXJUeXBlOiBcInRpdGxlXCJ9LFxuXHRcdHtvcmRlcjogXCJEZWF0aFwiLCBvcmRlclR5cGU6IFwiZGVhdGhcIn0sXG5cdFx0e29yZGVyOiBcIkluZmVjdGVkXCIsIG9yZGVyVHlwZTogXCJpbmZlY3RlZFwifSxcblx0XHR7b3JkZXI6IFwiUmVjb3ZlcmVkXCIsIG9yZGVyVHlwZTogXCJyZWNvdmVyZWRcIn1cblxuXHRdXG5cbjwvc2NyaXB0PlxuXG48ZGl2PlxuXHQ8ZGl2IGNsYXNzPVwic29ydFwiIGlkPVwibXlEaXZcIj5cblx0PCEtLTxidXR0b24gYXJpYS1jdXJyZW50PVwidHJ1ZVwiIGNsYXNzPVwiYnRuIGJ1dHRvbiBcIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBcInRpdGxlXCJ9PlRpdGxlPC9idXR0b24+XG4gICAgXHQ8YnV0dG9uIGFyaWEtY3VycmVudD1cImZhbHNlXCIgY2xhc3M9XCJidG4gYnV0dG9uXCIgb246Y2xpY2s9eygpID0+IG9yZGVyID0gXCJkZWF0aFwifT5EZWF0aDwvYnV0dG9uPlxuICAgIFx0PGJ1dHRvbiBhcmlhLWN1cnJlbnQ9XCJmYWxzZVwiIGNsYXNzPVwiYnRuIGJ1dHRvblwiIG9uOmNsaWNrPXsoKSA9PiBvcmRlciA9IFwiaW5mZWN0ZWRcIn0+SW5mZWN0ZWQ8L2J1dHRvbj5cbiAgICBcdDxidXR0b24gYXJpYS1jdXJyZW50PVwiZmFsc2VcIiBjbGFzcz1cImJ0biBidXR0b25cIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBcInJlY292ZXJlZFwifT5SZWNvdmVyZWQ8L2J1dHRvbj5cblx0LS0+XG5cblx0eyNlYWNoIGJ1dHRvbnMgYXMgYnV0dG9ufVxuXHRcdDxidXR0b24gY2xhc3M9XCJidXR0b25cIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBgJHtidXR0b24ub3JkZXJUeXBlfWB9ID57YnV0dG9uLm9yZGVyfTwvYnV0dG9uPlxuXHR7L2VhY2h9XG5cblx0PC9kaXY+XG5cdDxkaXYgY2xhc3M9XCJzZWFyY2hiYXJcIj5cbiAgICAgICAgPGlucHV0IGF1dG9jb21wbGV0ZT1cIm9mZlwiICBjbGFzcz1cInNlYXJjaC1pbnB1dFwiIHR5cGU9XCJzZWFyY2hcIiBwbGFjZWhvbGRlcj1cIlNlYXJjaCBhZnRlciBjb3VudHJ5XCIgYmluZDp2YWx1ZT17c2VhcmNofSBvbjppbnB1dHxwcmV2ZW50RGVmYXVsdD17ZmlsdGVyUmVzdWx0fS8+XG4gICAgPC9kaXY+XG5cdDxzZWN0aW9uPlxuXHRcdHsjZWFjaCBzZWFyY2hlZCBhcyBpdGVtfVxuXHRcdFx0PFdvcmxkIGl0ZW09e2l0ZW19IC8+XG5cdFx0ezplbHNlfVxuXHRcdFx0PExvYWRlciAvPlxuXHRcdHsvZWFjaH0gICBcblx0PC9zZWN0aW9uPlxuPC9kaXY+XG5cbjxzdHlsZT5cblx0ZGl2IHtcblx0XHRkaXNwbGF5OiBncmlkO1xuXHRcdGJhY2tncm91bmQtY29sb3I6ICMxYjFiMzA7XG5cdFx0d2lkdGg6IDEwMHZ3O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHR9XG4gICAgc2VjdGlvbntcblx0XHRkaXNwbGF5OiBncmlkO1xuICAgICAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCg1LCAxZnIpO1xuICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRnYXA6IDJyZW07XG4gICAgICAgIG1hcmdpbjogYXV0bztcblx0XHR3aWR0aDogODB2dztcblx0XHRtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICB9XG5cdC5zb3J0IHtcblx0XHRoZWlnaHQ6IDEwdmg7XG5cdFx0ZGlzcGxheTogZ3JpZDtcblx0XHRncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDEwMHB4IDEwMHB4IDEwMHB4IDEwMHB4O1xuXHRcdGdhcDogMTBweDtcblx0XHR3aWR0aDogOTB2dztcblx0XHRtYXJnaW46IGF1dG87XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0cGFkZGluZzogMXJlbTtcblx0fVxuXHQuYnV0dG9uIHtcblx0XHRoZWlnaHQ6IDMwcHg7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogaW5kaWdvO1xuXHRcdGNvbG9yOiB3aGl0ZTtcblx0XHRvdXRsaW5lOiBub25lO1xuXHR9XG5cblx0ICAgLnNlYXJjaGJhciB7XG4gICAgICAgIGFsaWduLWNvbnRlbnQ6IGNlbnRlcjtcbiAgICAgICAgd2lkdGg6IDEwMHZ3O1xuICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgfVxuICAgIC5zZWFyY2gtaW5wdXQge1xuICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7XG4gICAgICAgIGJvcmRlcjogMXB4IHNvbGlkIGJsYWNrO1xuICAgICAgICBwYWRkaW5nOiAxcmVtO1xuICAgICAgICBmb250LXNpemU6IDIwcHg7XG4gICAgICAgIG1hcmdpbjogMTVweDtcbiAgICAgICAgb3V0bGluZTogbm9uZTtcbiAgICAgICAgd2lkdGg6IDMwcmVtO1xuICAgIH1cblxuPC9zdHlsZT5cblxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQThGQyxHQUFHLGVBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZ0JBQWdCLENBQUUsT0FBTyxDQUN6QixLQUFLLENBQUUsS0FBSyxDQUNaLGVBQWUsQ0FBRSxNQUFNLEFBQ3hCLENBQUMsQUFDRSxzQkFBTyxDQUFDLEFBQ1YsT0FBTyxDQUFFLElBQUksQ0FDUCxxQkFBcUIsQ0FBRSxPQUFPLENBQUMsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUNyQyxlQUFlLENBQUUsTUFBTSxDQUM3QixHQUFHLENBQUUsSUFBSSxDQUNILE1BQU0sQ0FBRSxJQUFJLENBQ2xCLEtBQUssQ0FBRSxJQUFJLENBQ1gsVUFBVSxDQUFFLEtBQUssQUFDZixDQUFDLEFBQ0osS0FBSyxlQUFDLENBQUMsQUFDTixNQUFNLENBQUUsSUFBSSxDQUNaLE9BQU8sQ0FBRSxJQUFJLENBQ2IscUJBQXFCLENBQUUsS0FBSyxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUM5QyxHQUFHLENBQUUsSUFBSSxDQUNULEtBQUssQ0FBRSxJQUFJLENBQ1gsTUFBTSxDQUFFLElBQUksQ0FDWixlQUFlLENBQUUsTUFBTSxDQUN2QixPQUFPLENBQUUsSUFBSSxBQUNkLENBQUMsQUFDRCxPQUFPLGVBQUMsQ0FBQyxBQUNSLE1BQU0sQ0FBRSxJQUFJLENBQ1osZ0JBQWdCLENBQUUsTUFBTSxDQUN4QixLQUFLLENBQUUsS0FBSyxDQUNaLE9BQU8sQ0FBRSxJQUFJLEFBQ2QsQ0FBQyxBQUVFLFVBQVUsZUFBQyxDQUFDLEFBQ1IsYUFBYSxDQUFFLE1BQU0sQ0FDckIsS0FBSyxDQUFFLEtBQUssQ0FDWixVQUFVLENBQUUsTUFBTSxBQUN0QixDQUFDLEFBQ0QsYUFBYSxlQUFDLENBQUMsQUFDWCxhQUFhLENBQUUsR0FBRyxDQUNsQixNQUFNLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQ3ZCLE9BQU8sQ0FBRSxJQUFJLENBQ2IsU0FBUyxDQUFFLElBQUksQ0FDZixNQUFNLENBQUUsSUFBSSxDQUNaLE9BQU8sQ0FBRSxJQUFJLENBQ2IsS0FBSyxDQUFFLEtBQUssQUFDaEIsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[8] = list[i];
	return child_ctx;
}

function get_each_context_1(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[11] = list[i];
	return child_ctx;
}

// (77:1) {#each buttons as button}
function create_each_block_1(ctx) {
	let button;
	let t_value = /*button*/ ctx[11].order + "";
	let t;
	let dispose;

	function click_handler(...args) {
		return /*click_handler*/ ctx[6](/*button*/ ctx[11], ...args);
	}

	const block = {
		c: function create() {
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BUTTON", { class: true });
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button_nodes, t_value);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "class", "button svelte-1u2lue1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 77, 2, 2239);
		},
		m: function mount(target, anchor, remount) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, button, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button, t);
			if (remount) dispose();
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button, "click", click_handler, false, false, false);
		},
		p: function update(new_ctx, dirty) {
			ctx = new_ctx;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(button);
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block_1.name,
		type: "each",
		source: "(77:1) {#each buttons as button}",
		ctx
	});

	return block;
}

// (88:2) {:else}
function create_else_block(ctx) {
	let current;
	const loader = new _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(loader.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(loader.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(loader, target, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(loader.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(loader.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(loader, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(88:2) {:else}",
		ctx
	});

	return block;
}

// (86:2) {#each searched as item}
function create_each_block(ctx) {
	let current;

	const world_1 = new _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: { item: /*item*/ ctx[8] },
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(world_1.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(world_1.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(world_1, target, anchor);
			current = true;
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(world_1.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(world_1.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(world_1, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(86:2) {#each searched as item}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let t0;
	let div2;
	let div0;
	let t1;
	let div1;
	let input;
	let t2;
	let section;
	let current;
	let dispose;
	let each_value_1 = /*buttons*/ ctx[3];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value_1);
	let each_blocks_1 = [];

	for (let i = 0; i < each_value_1.length; i += 1) {
		each_blocks_1[i] = create_each_block_1(get_each_context_1(ctx, each_value_1, i));
	}

	let each_value = searched;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	let each1_else = null;

	if (!each_value.length) {
		each1_else = create_else_block(ctx);
	}

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].c();
			}

			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			if (each1_else) {
				each1_else.c();
			}

			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1136c5u\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true, id: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].l(div0_nodes);
			}

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "INPUT", {
				autocomplete: true,
				class: true,
				type: true,
				placeholder: true
			});

			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(section_nodes);
			}

			if (each1_else) {
				each1_else.l(section_nodes);
			}

			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "Corona information";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "sort svelte-1u2lue1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "id", "myDiv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 69, 1, 1756);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "autocomplete", "off");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "class", "search-input svelte-1u2lue1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "type", "search");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "placeholder", "Search after country");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input, file, 82, 8, 2385);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "searchbar svelte-1u2lue1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 81, 1, 2353);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "svelte-1u2lue1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 84, 1, 2555);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "svelte-1u2lue1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 68, 0, 1749);
		},
		m: function mount(target, anchor, remount) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div0);

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].m(div0, null);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, input);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*search*/ ctx[1]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, section);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(section, null);
			}

			if (each1_else) {
				each1_else.m(section, null);
			}

			current = true;
			if (remount) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);

			dispose = [
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "input", /*input_input_handler*/ ctx[7]),
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "input", Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prevent_default"])(/*filterResult*/ ctx[2]), false, true, false)
			];
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*order, buttons*/ 9) {
				each_value_1 = /*buttons*/ ctx[3];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value_1);
				let i;

				for (i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks_1[i]) {
						each_blocks_1[i].p(child_ctx, dirty);
					} else {
						each_blocks_1[i] = create_each_block_1(child_ctx);
						each_blocks_1[i].c();
						each_blocks_1[i].m(div0, null);
					}
				}

				for (; i < each_blocks_1.length; i += 1) {
					each_blocks_1[i].d(1);
				}

				each_blocks_1.length = each_value_1.length;
			}

			if (dirty & /*search*/ 2) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*search*/ ctx[1]);
			}

			if (dirty & /*searched*/ 0) {
				each_value = searched;
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(section, null);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();

				if (each_value.length) {
					if (each1_else) {
						each1_else.d(1);
						each1_else = null;
					}
				} else if (!each1_else) {
					each1_else = create_else_block(ctx);
					each1_else.c();
					each1_else.m(section, null);
				}
			}
		},
		i: function intro(local) {
			if (current) return;

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			current = true;
		},
		o: function outro(local) {
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks_1, detaching);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
			if (each1_else) each1_else.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let world = [];
	let searcehd = [];

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(async () => {
		await fetch(`https://api.covid19api.com/summary`).then(response => response.json()).then(json => {
			// World
			$$invalidate(4, world = json.Countries);

			searcehd = world;
		}).catch(err => console.log(err));
	});

	let order = "title";
	let search = "";

	const filterResult = () => {
		searched = world.filter(world => world.Country.toLowerCase().includes(search.toLowerCase()));
	};

	/*
	const btnContainer = document.querySelector("#myDiv");
	const btns = btnContainer.querySelector(".btn")
	for(var i = 0; i < btns.length; i++) {
		btns[i].addEventListener("click", function() {
			var current = document.getElementsByClassName("active");

			if(current.length > 0) {
				current[0].className = current[0].className.replace(" active", "");
			}

			this.className += " active"
		})
	}

*/
	const buttons = [
		{ order: "Title", orderType: "title" },
		{ order: "Death", orderType: "death" },
		{ order: "Infected", orderType: "infected" },
		{
			order: "Recovered",
			orderType: "recovered"
		}
	];

	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", $$slots, []);
	const click_handler = button => $$invalidate(0, order = `${button.orderType}`);

	function input_input_handler() {
		search = this.value;
		$$invalidate(1, search);
	}

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		Loader: _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__["default"],
		World: _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__["default"],
		world,
		searcehd,
		order,
		search,
		filterResult,
		buttons
	});

	$$self.$inject_state = $$props => {
		if ("world" in $$props) $$invalidate(4, world = $$props.world);
		if ("searcehd" in $$props) searcehd = $$props.searcehd;
		if ("order" in $$props) $$invalidate(0, order = $$props.order);
		if ("search" in $$props) $$invalidate(1, search = $$props.search);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*order, world*/ 17) {
			$: switch (order) {
				case "title":
					$$invalidate(4, world = world.sort((a, b) => a.Country > b.Country ? 1 : -1));
					break;
				case "death":
					$$invalidate(4, world = world.sort((a, b) => a.TotalDeaths < b.TotalDeaths ? 1 : -1));
					break;
				case "infected":
					$$invalidate(4, world = world.sort((a, b) => a.TotalConfirmed < b.TotalConfirmed ? 1 : -1));
					break;
				case "recovered":
					$$invalidate(4, world = world.sort((a, b) => a.TotalRecovered < b.TotalRecovered ? 1 : -1));
					break;
			}
		}
	};

	return [
		order,
		search,
		filterResult,
		buttons,
		world,
		searcehd,
		click_handler,
		input_input_handler
	];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1u2lue1-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9Xb3JsZC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9pbmRleC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O3lCQVFvQixHQUFJLElBQUMsT0FBTzs7Ozs7eUJBQ0ksR0FBSSxJQUFDLGNBQWMsQ0FBQyxRQUFRLEdBQUcsT0FBTyxDQUFDLHVCQUF1QixFQUFFLEdBQUc7Ozs7O3lCQUN4RSxHQUFJLElBQUMsV0FBVyxDQUFDLFFBQVEsR0FBRyxPQUFPLENBQUMsdUJBQXVCLEVBQUUsR0FBRzs7Ozs7eUJBQzNELEdBQUksSUFBQyxjQUFjLENBQUMsUUFBUSxHQUFHLE9BQU8sQ0FBQyx1QkFBdUIsRUFBRSxHQUFHOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrREFIbkYsR0FBSSxJQUFDLE9BQU87K0RBQ0ksR0FBSSxJQUFDLGNBQWMsQ0FBQyxRQUFRLEdBQUcsT0FBTyxDQUFDLHVCQUF1QixFQUFFLEdBQUc7K0RBQ3hFLEdBQUksSUFBQyxXQUFXLENBQUMsUUFBUSxHQUFHLE9BQU8sQ0FBQyx1QkFBdUIsRUFBRSxHQUFHOytEQUMzRCxHQUFJLElBQUMsY0FBYyxDQUFDLFFBQVEsR0FBRyxPQUFPLENBQUMsdUJBQXVCLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O09BVDVGLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ0drQjtBQUNnQjtBQUNGOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBCQXNFMkIsR0FBTSxLQUFDLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7MkJBU3RFLEdBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Z0NBVlosR0FBTzs7OztrQ0FBWixNQUFJOzs7O2tCQVNFLFFBQVE7Ozs7Z0NBQWIsTUFBSTs7Ozs7Ozs7OztpQkFBSixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs2RkFINkcsR0FBTTs7Ozs7Ozs7Ozs7Ozs7Ozs7Z0xBQTJCLEdBQVk7Ozs7OytCQU4xSixHQUFPOzs7O2lDQUFaLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7d0NBQUosTUFBSTs7Ozs4RkFNOEcsR0FBTTs7OztpQkFHbEgsUUFBUTs7OzsrQkFBYixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7O3dCQUFKLE1BQUk7Ozs7OzttQkFBSixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7a0NBQUosTUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztLQTNFSCxLQUFLO0tBQ0wsUUFBUTs7Q0FLVCxzREFBTztRQUNILEtBQUssdUNBQ1YsSUFBSSxDQUFFLFFBQVEsSUFBSSxRQUFRLENBQUMsSUFBSSxJQUN6QixJQUFJLENBQUUsSUFBSTs7bUJBRWhCLEtBQUssR0FBRyxJQUFJLENBQUMsU0FBUzs7R0FDdEIsUUFBUSxHQUFHLEtBQUs7S0FFVCxLQUFLLENBQUUsR0FBRyxJQUFLLE9BQU8sQ0FBQyxHQUFHLENBQUMsR0FBRzs7O0tBR25DLEtBQUssR0FBRyxPQUFPO0tBUVgsTUFBTSxHQUFHLEVBQUU7O09BQ1YsWUFBWTtFQUNkLFFBQVEsR0FBRyxLQUFLLENBQUMsTUFBTSxDQUFFLEtBQUssSUFBSSxLQUFLLENBQUMsT0FBTyxDQUFDLFdBQVcsR0FBRyxRQUFRLENBQUMsTUFBTSxDQUFDLFdBQVc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7T0FxQjFGLE9BQU87SUFDWCxLQUFLLEVBQUUsT0FBTyxFQUFFLFNBQVMsRUFBRSxPQUFPO0lBQ2xDLEtBQUssRUFBRSxPQUFPLEVBQUUsU0FBUyxFQUFFLE9BQU87SUFDbEMsS0FBSyxFQUFFLFVBQVUsRUFBRSxTQUFTLEVBQUUsVUFBVTs7R0FDeEMsS0FBSyxFQUFFLFdBQVc7R0FBRSxTQUFTLEVBQUUsV0FBVzs7Ozs7Ozs7Ozs7O2lEQWVKLEtBQUssTUFBTSxNQUFNLENBQUMsU0FBUzs7O0VBS2lELE1BQU07Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0dBdER2SCxDQUFDLFVBQVUsS0FBSztTQUNiLE9BQU87cUJBQUUsS0FBSyxHQUFHLEtBQUssQ0FBQyxJQUFJLEVBQUcsQ0FBQyxFQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsT0FBTyxHQUFHLENBQUMsQ0FBQyxPQUFPLEdBQUcsQ0FBQyxJQUFJLENBQUM7O1NBQzFELE9BQU87cUJBQUUsS0FBSyxHQUFHLEtBQUssQ0FBQyxJQUFJLEVBQUcsQ0FBQyxFQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsV0FBVyxHQUFHLENBQUMsQ0FBQyxXQUFXLEdBQUcsQ0FBQyxJQUFJLENBQUM7O1NBQzVFLFVBQVU7cUJBQUUsS0FBSyxHQUFHLEtBQUssQ0FBQyxJQUFJLEVBQUcsQ0FBQyxFQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsY0FBYyxHQUFHLENBQUMsQ0FBQyxjQUFjLEdBQUcsQ0FBQyxJQUFJLENBQUM7O1NBQ3JGLFdBQVc7cUJBQUUsS0FBSyxHQUFHLEtBQUssQ0FBQyxJQUFJLEVBQUcsQ0FBQyxFQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsY0FBYyxHQUFHLENBQUMsQ0FBQyxjQUFjLEdBQUcsQ0FBQyxJQUFJLENBQUMiLCJmaWxlIjoiY2E3YzA2ZDJjZDFkMzBhNjIwMjUvaW5kZXguaW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuXG5leHBvcnQgbGV0IGl0ZW1cblxuPC9zY3JpcHQ+XG5cblxuPGFydGljbGU+XG5cdDxoMSBjbGFzcz1cIndoaXRlXCI+e2l0ZW0uQ291bnRyeX08L2gxPlxuXHQ8cCBjbGFzcz1cIm9yYW5nZVwiPlRvdGFsIGluZmVjdGVkOiB7aXRlbS5Ub3RhbENvbmZpcm1lZC50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG5cdDxwIGNsYXNzPVwicmVkXCI+VG90YWwgZGVhdGhzOiB7aXRlbS5Ub3RhbERlYXRocy50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG5cdDxwIGNsYXNzPVwiZ3JlZW5cIj5Ub3RhbCByZWNvdmVyZWQ6IHtpdGVtLlRvdGFsUmVjb3ZlcmVkLnRvU3RyaW5nKCkucmVwbGFjZSgvXFxCKD89KFxcZHszfSkrKD8hXFxkKSkvZywgXCIsXCIpfTwvcD5cbjwvYXJ0aWNsZT5cdFx0XG5cbjxzdHlsZT5cblx0YXJ0aWNsZSB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogcmdiYSg0LCA0LCA0LCAuNik7XG5cdFx0cGFkZGluZzogMXJlbTtcblx0fVxuXHRhcnRpY2xlOmhvdmVyIHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiByZ2JhKDQsIDQsIDQsIC4yKTtcblx0fVxuXHQud2hpdGUge1xuXHRcdGNvbG9yOiB3aGl0ZTtcblx0fVxuXHQuZ3JlZW4ge1xuXHRcdGNvbG9yOiBncmVlbjtcblx0fVxuXHQucmVkIHtcblx0XHRjb2xvcjogcmVkO1xuXHR9XG5cdC5vcmFuZ2Uge1xuXHRcdGNvbG9yOiBvcmFuZ2U7XG5cdH1cbjwvc3R5bGU+IiwiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+Q29yb25hIGluZm9ybWF0aW9uPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxzY3JpcHQ+XG5cdGltcG9ydCB7IG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCJcblx0aW1wb3J0IExvYWRlciBmcm9tIFwiLi4vY29tcG9uZW50cy9Mb2FkZXIuc3ZlbHRlXCJcblx0aW1wb3J0IFdvcmxkIGZyb20gXCIuLi9jb21wb25lbnRzL1dvcmxkLnN2ZWx0ZVwiXG5cblxuXHRsZXQgd29ybGQgPSBbXVxuXHRsZXQgc2VhcmNlaGQgPSBbXVxuXG5cblxuXG4gICAgb25Nb3VudCggYXN5bmMgKCkgPT4ge1xuXHRcdGF3YWl0IGZldGNoKGBodHRwczovL2FwaS5jb3ZpZDE5YXBpLmNvbS9zdW1tYXJ5YClcblx0XHQudGhlbiggcmVzcG9uc2UgPT4gcmVzcG9uc2UuanNvbigpIClcbiAgICAgICAgLnRoZW4oIGpzb24gPT4ge1xuXHRcdFx0Ly8gV29ybGRcblx0XHRcdHdvcmxkID0ganNvbi5Db3VudHJpZXNcblx0XHRcdHNlYXJjZWhkID0gd29ybGRcbiAgICAgICAgfVxuICAgICAgICApLmNhdGNoKChlcnIpID0+IGNvbnNvbGUubG9nKGVycikpXG5cdH0gKVxuXG5cdGxldCBvcmRlciA9IFwidGl0bGVcIlxuICAgICQ6ICBzd2l0Y2gob3JkZXIpeyAgICAgIFxuXHRcdGNhc2UgJ3RpdGxlJzogd29ybGQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLkNvdW50cnkgPiBiLkNvdW50cnkgPyAxIDogLTEpO2JyZWFrXG4gICAgICAgICAgICBjYXNlICdkZWF0aCc6IHdvcmxkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Ub3RhbERlYXRocyA8IGIuVG90YWxEZWF0aHMgPyAxIDogLTEpOyBicmVha1xuICAgICAgICAgICAgY2FzZSAnaW5mZWN0ZWQnOiB3b3JsZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxDb25maXJtZWQgPCBiLlRvdGFsQ29uZmlybWVkID8gMSA6IC0xKTsgYnJlYWtcbiAgICAgICAgICAgIGNhc2UgJ3JlY292ZXJlZCc6IHdvcmxkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Ub3RhbFJlY292ZXJlZCA8IGIuVG90YWxSZWNvdmVyZWQgPyAxIDogLTEpOyBicmVha1xuXHR9XG5cblx0ICAgIGxldCBzZWFyY2ggPSBcIlwiXG4gICAgY29uc3QgZmlsdGVyUmVzdWx0ID0gKCkgPT4ge1xuICAgICAgICBzZWFyY2hlZCA9IHdvcmxkLmZpbHRlciggd29ybGQgPT4gd29ybGQuQ291bnRyeS50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKHNlYXJjaC50b0xvd2VyQ2FzZSgpKSlcbiAgICB9XG5cblxuLypcblx0Y29uc3QgYnRuQ29udGFpbmVyID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIiNteURpdlwiKTtcblx0Y29uc3QgYnRucyA9IGJ0bkNvbnRhaW5lci5xdWVyeVNlbGVjdG9yKFwiLmJ0blwiKVxuXHRmb3IodmFyIGkgPSAwOyBpIDwgYnRucy5sZW5ndGg7IGkrKykge1xuXHRcdGJ0bnNbaV0uYWRkRXZlbnRMaXN0ZW5lcihcImNsaWNrXCIsIGZ1bmN0aW9uKCkge1xuXHRcdFx0dmFyIGN1cnJlbnQgPSBkb2N1bWVudC5nZXRFbGVtZW50c0J5Q2xhc3NOYW1lKFwiYWN0aXZlXCIpO1xuXG5cdFx0XHRpZihjdXJyZW50Lmxlbmd0aCA+IDApIHtcblx0XHRcdFx0Y3VycmVudFswXS5jbGFzc05hbWUgPSBjdXJyZW50WzBdLmNsYXNzTmFtZS5yZXBsYWNlKFwiIGFjdGl2ZVwiLCBcIlwiKTtcblx0XHRcdH1cblxuXHRcdFx0dGhpcy5jbGFzc05hbWUgKz0gXCIgYWN0aXZlXCJcblx0XHR9KVxuXHR9XG5cbiovXG5cblx0Y29uc3QgYnV0dG9ucyA9IFtcblx0XHR7b3JkZXI6IFwiVGl0bGVcIiwgb3JkZXJUeXBlOiBcInRpdGxlXCJ9LFxuXHRcdHtvcmRlcjogXCJEZWF0aFwiLCBvcmRlclR5cGU6IFwiZGVhdGhcIn0sXG5cdFx0e29yZGVyOiBcIkluZmVjdGVkXCIsIG9yZGVyVHlwZTogXCJpbmZlY3RlZFwifSxcblx0XHR7b3JkZXI6IFwiUmVjb3ZlcmVkXCIsIG9yZGVyVHlwZTogXCJyZWNvdmVyZWRcIn1cblxuXHRdXG5cbjwvc2NyaXB0PlxuXG48ZGl2PlxuXHQ8ZGl2IGNsYXNzPVwic29ydFwiIGlkPVwibXlEaXZcIj5cblx0PCEtLTxidXR0b24gYXJpYS1jdXJyZW50PVwidHJ1ZVwiIGNsYXNzPVwiYnRuIGJ1dHRvbiBcIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBcInRpdGxlXCJ9PlRpdGxlPC9idXR0b24+XG4gICAgXHQ8YnV0dG9uIGFyaWEtY3VycmVudD1cImZhbHNlXCIgY2xhc3M9XCJidG4gYnV0dG9uXCIgb246Y2xpY2s9eygpID0+IG9yZGVyID0gXCJkZWF0aFwifT5EZWF0aDwvYnV0dG9uPlxuICAgIFx0PGJ1dHRvbiBhcmlhLWN1cnJlbnQ9XCJmYWxzZVwiIGNsYXNzPVwiYnRuIGJ1dHRvblwiIG9uOmNsaWNrPXsoKSA9PiBvcmRlciA9IFwiaW5mZWN0ZWRcIn0+SW5mZWN0ZWQ8L2J1dHRvbj5cbiAgICBcdDxidXR0b24gYXJpYS1jdXJyZW50PVwiZmFsc2VcIiBjbGFzcz1cImJ0biBidXR0b25cIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBcInJlY292ZXJlZFwifT5SZWNvdmVyZWQ8L2J1dHRvbj5cblx0LS0+XG5cblx0eyNlYWNoIGJ1dHRvbnMgYXMgYnV0dG9ufVxuXHRcdDxidXR0b24gY2xhc3M9XCJidXR0b25cIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBgJHtidXR0b24ub3JkZXJUeXBlfWB9ID57YnV0dG9uLm9yZGVyfTwvYnV0dG9uPlxuXHR7L2VhY2h9XG5cblx0PC9kaXY+XG5cdDxkaXYgY2xhc3M9XCJzZWFyY2hiYXJcIj5cbiAgICAgICAgPGlucHV0IGF1dG9jb21wbGV0ZT1cIm9mZlwiICBjbGFzcz1cInNlYXJjaC1pbnB1dFwiIHR5cGU9XCJzZWFyY2hcIiBwbGFjZWhvbGRlcj1cIlNlYXJjaCBhZnRlciBjb3VudHJ5XCIgYmluZDp2YWx1ZT17c2VhcmNofSBvbjppbnB1dHxwcmV2ZW50RGVmYXVsdD17ZmlsdGVyUmVzdWx0fS8+XG4gICAgPC9kaXY+XG5cdDxzZWN0aW9uPlxuXHRcdHsjZWFjaCBzZWFyY2hlZCBhcyBpdGVtfVxuXHRcdFx0PFdvcmxkIGl0ZW09e2l0ZW19IC8+XG5cdFx0ezplbHNlfVxuXHRcdFx0PExvYWRlciAvPlxuXHRcdHsvZWFjaH0gICBcblx0PC9zZWN0aW9uPlxuPC9kaXY+XG5cbjxzdHlsZT5cblx0ZGl2IHtcblx0XHRkaXNwbGF5OiBncmlkO1xuXHRcdGJhY2tncm91bmQtY29sb3I6ICMxYjFiMzA7XG5cdFx0d2lkdGg6IDEwMHZ3O1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHR9XG4gICAgc2VjdGlvbntcblx0XHRkaXNwbGF5OiBncmlkO1xuICAgICAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IHJlcGVhdCg1LCAxZnIpO1xuICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRnYXA6IDJyZW07XG4gICAgICAgIG1hcmdpbjogYXV0bztcblx0XHR3aWR0aDogODB2dztcblx0XHRtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICB9XG5cdC5zb3J0IHtcblx0XHRoZWlnaHQ6IDEwdmg7XG5cdFx0ZGlzcGxheTogZ3JpZDtcblx0XHRncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDEwMHB4IDEwMHB4IDEwMHB4IDEwMHB4O1xuXHRcdGdhcDogMTBweDtcblx0XHR3aWR0aDogOTB2dztcblx0XHRtYXJnaW46IGF1dG87XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdFx0cGFkZGluZzogMXJlbTtcblx0fVxuXHQuYnV0dG9uIHtcblx0XHRoZWlnaHQ6IDMwcHg7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogaW5kaWdvO1xuXHRcdGNvbG9yOiB3aGl0ZTtcblx0XHRvdXRsaW5lOiBub25lO1xuXHR9XG5cblx0ICAgLnNlYXJjaGJhciB7XG4gICAgICAgIGFsaWduLWNvbnRlbnQ6IGNlbnRlcjtcbiAgICAgICAgd2lkdGg6IDEwMHZ3O1xuICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgfVxuICAgIC5zZWFyY2gtaW5wdXQge1xuICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7XG4gICAgICAgIGJvcmRlcjogMXB4IHNvbGlkIGJsYWNrO1xuICAgICAgICBwYWRkaW5nOiAxcmVtO1xuICAgICAgICBmb250LXNpemU6IDIwcHg7XG4gICAgICAgIG1hcmdpbjogMTVweDtcbiAgICAgICAgb3V0bGluZTogbm9uZTtcbiAgICAgICAgd2lkdGg6IDMwcmVtO1xuICAgIH1cblxuPC9zdHlsZT5cblxuIl0sInNvdXJjZVJvb3QiOiIifQ==