(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/Loader.svelte":
/*!**************************************!*\
  !*** ./src/components/Loader.svelte ***!
  \**************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/Loader.svelte generated by Svelte v3.22.2 */


const file = "src/components/Loader.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-19eexb2-style";
	style.textContent = ".spinner.svelte-19eexb2.svelte-19eexb2{width:50px;height:40px;text-align:center;font-size:10px}.spinner.svelte-19eexb2>div.svelte-19eexb2{background-color:white;height:100%;width:6px;display:inline-block;animation:svelte-19eexb2-sk-stretchdelay 1.2s infinite ease-in-out}.spinner.svelte-19eexb2 .rect2.svelte-19eexb2{animation-delay:-1.1s}.spinner.svelte-19eexb2 .rect3.svelte-19eexb2{animation-delay:-1.0s}.spinner.svelte-19eexb2 .rect4.svelte-19eexb2{-webkit-animation-delay:-0.9s;animation-delay:-0.9s}.spinner.svelte-19eexb2 .rect5.svelte-19eexb2{animation-delay:-0.8s}@keyframes svelte-19eexb2-sk-stretchdelay{0%,40%,100%{transform:scaleY(0.4)}20%{transform:scaleY(1.0)}}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiTG9hZGVyLnN2ZWx0ZSIsInNvdXJjZXMiOlsiTG9hZGVyLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyIgICAgICBcbjxkaXYgY2xhc3M9XCJzcGlubmVyXCI+XG4gIDxkaXYgY2xhc3M9XCJyZWN0MVwiPjwvZGl2PlxuICA8ZGl2IGNsYXNzPVwicmVjdDJcIj48L2Rpdj5cbiAgPGRpdiBjbGFzcz1cInJlY3QzXCI+PC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJyZWN0NFwiPjwvZGl2PlxuICA8ZGl2IGNsYXNzPVwicmVjdDVcIj48L2Rpdj5cbjwvZGl2PlxuXG48c3R5bGU+XG4gIC5zcGlubmVyIHtcbiAgICB3aWR0aDogNTBweDtcbiAgICBoZWlnaHQ6IDQwcHg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGZvbnQtc2l6ZTogMTBweDtcbiAgICBcbiAgfVxuXG4gIC5zcGlubmVyID4gZGl2IHtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiB3aGl0ZTtcbiAgICBoZWlnaHQ6IDEwMCU7XG4gICAgd2lkdGg6IDZweDtcbiAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7XG4gICAgYW5pbWF0aW9uOiBzay1zdHJldGNoZGVsYXkgMS4ycyBpbmZpbml0ZSBlYXNlLWluLW91dDtcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0MiB7XG4gICAgYW5pbWF0aW9uLWRlbGF5OiAtMS4xcztcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0MyB7XG4gICAgYW5pbWF0aW9uLWRlbGF5OiAtMS4wcztcbiAgfVxuXG4gIC5zcGlubmVyIC5yZWN0NCB7XG4gICAgLXdlYmtpdC1hbmltYXRpb24tZGVsYXk6IC0wLjlzO1xuICAgIGFuaW1hdGlvbi1kZWxheTogLTAuOXM7XG4gIH1cblxuICAuc3Bpbm5lciAucmVjdDUge1xuICAgIGFuaW1hdGlvbi1kZWxheTogLTAuOHM7XG4gIH1cblxuXG4gIEBrZXlmcmFtZXMgc2stc3RyZXRjaGRlbGF5IHtcbiAgICAwJSwgNDAlLCAxMDAlIHtcbiAgICAgIHRyYW5zZm9ybTogc2NhbGVZKDAuNCk7XG4gICAgfSAgMjAlIHtcbiAgICAgIHRyYW5zZm9ybTogc2NhbGVZKDEuMCk7XG4gICAgfVxuICB9XG48L3N0eWxlPiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFVRSxRQUFRLDhCQUFDLENBQUMsQUFDUixLQUFLLENBQUUsSUFBSSxDQUNYLE1BQU0sQ0FBRSxJQUFJLENBQ1osVUFBVSxDQUFFLE1BQU0sQ0FDbEIsU0FBUyxDQUFFLElBQUksQUFFakIsQ0FBQyxBQUVELHVCQUFRLENBQUcsR0FBRyxlQUFDLENBQUMsQUFDZCxnQkFBZ0IsQ0FBRSxLQUFLLENBQ3ZCLE1BQU0sQ0FBRSxJQUFJLENBQ1osS0FBSyxDQUFFLEdBQUcsQ0FDVixPQUFPLENBQUUsWUFBWSxDQUNyQixTQUFTLENBQUUsOEJBQWUsQ0FBQyxJQUFJLENBQUMsUUFBUSxDQUFDLFdBQVcsQUFDdEQsQ0FBQyxBQUVELHVCQUFRLENBQUMsTUFBTSxlQUFDLENBQUMsQUFDZixlQUFlLENBQUUsS0FBSyxBQUN4QixDQUFDLEFBRUQsdUJBQVEsQ0FBQyxNQUFNLGVBQUMsQ0FBQyxBQUNmLGVBQWUsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFFRCx1QkFBUSxDQUFDLE1BQU0sZUFBQyxDQUFDLEFBQ2YsdUJBQXVCLENBQUUsS0FBSyxDQUM5QixlQUFlLENBQUUsS0FBSyxBQUN4QixDQUFDLEFBRUQsdUJBQVEsQ0FBQyxNQUFNLGVBQUMsQ0FBQyxBQUNmLGVBQWUsQ0FBRSxLQUFLLEFBQ3hCLENBQUMsQUFHRCxXQUFXLDhCQUFnQixDQUFDLEFBQzFCLEVBQUUsQ0FBRSxHQUFHLENBQUUsSUFBSSxBQUFDLENBQUMsQUFDYixTQUFTLENBQUUsT0FBTyxHQUFHLENBQUMsQUFDeEIsQ0FBQyxBQUFFLEdBQUcsQUFBQyxDQUFDLEFBQ04sU0FBUyxDQUFFLE9BQU8sR0FBRyxDQUFDLEFBQ3hCLENBQUMsQUFDSCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div5;
	let div0;
	let t0;
	let div1;
	let t1;
	let div2;
	let t2;
	let div3;
	let t3;
	let div4;

	const block = {
		c: function create() {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			this.h();
		},
		l: function claim(nodes) {
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div5_nodes);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "rect1 svelte-19eexb2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 2, 2, 31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "rect2 svelte-19eexb2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 3, 2, 59);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "rect3 svelte-19eexb2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 4, 2, 87);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "rect4 svelte-19eexb2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 5, 2, 115);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "rect5 svelte-19eexb2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 6, 2, 143);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "spinner svelte-19eexb2");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 1, 0, 7);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div5, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, div4);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div5);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<Loader> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Loader", $$slots, []);
	return [];
}

class Loader extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-19eexb2-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Loader",
			options,
			id: create_fragment.name
		});
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Loader);

/***/ }),

/***/ "./src/components/World.svelte":
/*!*************************************!*\
  !*** ./src/components/World.svelte ***!
  \*************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _routes_index_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../routes/index.svelte */ "./src/routes/index.svelte");
/* src/components/World.svelte generated by Svelte v3.22.2 */



const file = "src/components/World.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-sakdfv-style";
	style.textContent = "article.svelte-sakdfv{background-color:rgba(4, 4, 4, .6);padding:1rem;border-radius:10px;display:grid;max-width:15rem;max-height:16rem}article.svelte-sakdfv:hover{background-color:rgba(4, 4, 4, .2)}.btn.svelte-sakdfv{border:1px solid red;outline:none}.white.svelte-sakdfv{color:white;text-align:center;font-size:1.8rem}.green.svelte-sakdfv{color:green}.red.svelte-sakdfv{color:red}.orange.svelte-sakdfv{color:orange}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiV29ybGQuc3ZlbHRlIiwic291cmNlcyI6WyJXb3JsZC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cblx0aW1wb3J0IHsgZmF2b3JpdGUgfSBmcm9tIFwiLi4vcm91dGVzL2luZGV4LnN2ZWx0ZVwiXG5cdGV4cG9ydCBsZXQgaXRlbVxuXHRlXG5cbjwvc2NyaXB0PlxuXG5cbjxhcnRpY2xlID5cblx0PGgxIGNsYXNzPVwid2hpdGVcIj57aXRlbS5Db3VudHJ5fTwvaDE+XG5cdDxwIGNsYXNzPVwidGV4dCBvcmFuZ2VcIj5Ub3RhbCBpbmZlY3RlZDoge2l0ZW0uVG90YWxDb25maXJtZWQudG9TdHJpbmcoKS5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCBcIixcIil9PC9wPlxuXHQ8cCBjbGFzcz1cInRleHQgcmVkXCI+VG90YWwgZGVhdGhzOiB7aXRlbS5Ub3RhbERlYXRocy50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG5cdDxwIGNsYXNzPVwidGV4dCBncmVlblwiPlRvdGFsIHJlY292ZXJlZDoge2l0ZW0uVG90YWxSZWNvdmVyZWQudG9TdHJpbmcoKS5yZXBsYWNlKC9cXEIoPz0oXFxkezN9KSsoPyFcXGQpKS9nLCBcIixcIil9PC9wPlxuXHQ8YnV0dG9uIG9uOmNsaWNrPXthZGRUb0Zhdm9yaXRlKGl0ZW0pfSBjbGFzcz1cImJ0blwiPkFkZCB0byBmYXZvcml0ZTwvYnV0dG9uPlxuPC9hcnRpY2xlPlx0XHRcblxuPHN0eWxlPlxuXHRhcnRpY2xlIHtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiByZ2JhKDQsIDQsIDQsIC42KTtcblx0XHRwYWRkaW5nOiAxcmVtO1xuXHRcdGJvcmRlci1yYWRpdXM6IDEwcHg7XG5cdFx0ZGlzcGxheTogZ3JpZDtcblx0XHRtYXgtd2lkdGg6IDE1cmVtO1xuXHRcdG1heC1oZWlnaHQ6IDE2cmVtO1xuXHR9XG5cdGFydGljbGU6aG92ZXIge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHJnYmEoNCwgNCwgNCwgLjIpO1xuXHR9XG5cdC5idG4ge1xuXHRcdGJvcmRlcjogMXB4IHNvbGlkIHJlZDtcblx0XHRvdXRsaW5lOiBub25lO1xuXHR9XG5cdC53aGl0ZSB7XG5cdFx0Y29sb3I6IHdoaXRlO1xuXHRcdHRleHQtYWxpZ246IGNlbnRlcjtcblx0XHRmb250LXNpemU6IDEuOHJlbTtcblx0fVxuXHQuZ3JlZW4ge1xuXHRcdGNvbG9yOiBncmVlbjtcblx0fVxuXHQucmVkIHtcblx0XHRjb2xvcjogcmVkO1xuXHR9XG5cdC5vcmFuZ2Uge1xuXHRcdGNvbG9yOiBvcmFuZ2U7XG5cdH1cbjwvc3R5bGU+Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQWlCQyxPQUFPLGNBQUMsQ0FBQyxBQUNSLGdCQUFnQixDQUFFLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQ25DLE9BQU8sQ0FBRSxJQUFJLENBQ2IsYUFBYSxDQUFFLElBQUksQ0FDbkIsT0FBTyxDQUFFLElBQUksQ0FDYixTQUFTLENBQUUsS0FBSyxDQUNoQixVQUFVLENBQUUsS0FBSyxBQUNsQixDQUFDLEFBQ0QscUJBQU8sTUFBTSxBQUFDLENBQUMsQUFDZCxnQkFBZ0IsQ0FBRSxLQUFLLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxBQUNwQyxDQUFDLEFBQ0QsSUFBSSxjQUFDLENBQUMsQUFDTCxNQUFNLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxHQUFHLENBQ3JCLE9BQU8sQ0FBRSxJQUFJLEFBQ2QsQ0FBQyxBQUNELE1BQU0sY0FBQyxDQUFDLEFBQ1AsS0FBSyxDQUFFLEtBQUssQ0FDWixVQUFVLENBQUUsTUFBTSxDQUNsQixTQUFTLENBQUUsTUFBTSxBQUNsQixDQUFDLEFBQ0QsTUFBTSxjQUFDLENBQUMsQUFDUCxLQUFLLENBQUUsS0FBSyxBQUNiLENBQUMsQUFDRCxJQUFJLGNBQUMsQ0FBQyxBQUNMLEtBQUssQ0FBRSxHQUFHLEFBQ1gsQ0FBQyxBQUNELE9BQU8sY0FBQyxDQUFDLEFBQ1IsS0FBSyxDQUFFLE1BQU0sQUFDZCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let article;
	let h1;
	let t0_value = /*item*/ ctx[0].Country + "";
	let t0;
	let t1;
	let p0;
	let t2;
	let t3_value = /*item*/ ctx[0].TotalConfirmed.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t3;
	let t4;
	let p1;
	let t5;
	let t6_value = /*item*/ ctx[0].TotalDeaths.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t6;
	let t7;
	let p2;
	let t8;
	let t9_value = /*item*/ ctx[0].TotalRecovered.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "";
	let t9;
	let t10;
	let button;
	let t11;
	let dispose;

	const block = {
		c: function create() {
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("article");
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t0_value);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total infected: ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t3_value);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total deaths: ");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t6_value);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Total recovered: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t9_value);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Add to favorite");
			this.h();
		},
		l: function claim(nodes) {
			article = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "ARTICLE", { class: true });
			var article_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(article);
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "H1", { class: true });
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, t0_value);
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Total infected: ");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, t3_value);
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Total deaths: ");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, t6_value);
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "P", { class: true });
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "Total recovered: ");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, t9_value);
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(article_nodes);
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(article_nodes, "BUTTON", { class: true });
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button_nodes, "Add to favorite");
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			article_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h1, "class", "white svelte-sakdfv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 9, 1, 105);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "text orange svelte-sakdfv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 10, 1, 144);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p1, "class", "text red svelte-sakdfv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 11, 1, 259);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p2, "class", "text green svelte-sakdfv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 12, 1, 366);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "class", "btn svelte-sakdfv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 13, 1, 481);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(article, "class", "svelte-sakdfv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(article, file, 8, 0, 93);
		},
		m: function mount(target, anchor, remount) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, article, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, h1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(article, button);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button, t11);
			if (remount) dispose();

			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(
				button,
				"click",
				function () {
					if (Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["is_function"])(addToFavorite(/*item*/ ctx[0]))) addToFavorite(/*item*/ ctx[0]).apply(this, arguments);
				},
				false,
				false,
				false
			);
		},
		p: function update(new_ctx, [dirty]) {
			ctx = new_ctx;
			if (dirty & /*item*/ 1 && t0_value !== (t0_value = /*item*/ ctx[0].Country + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t0, t0_value);
			if (dirty & /*item*/ 1 && t3_value !== (t3_value = /*item*/ ctx[0].TotalConfirmed.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t3, t3_value);
			if (dirty & /*item*/ 1 && t6_value !== (t6_value = /*item*/ ctx[0].TotalDeaths.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t6, t6_value);
			if (dirty & /*item*/ 1 && t9_value !== (t9_value = /*item*/ ctx[0].TotalRecovered.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t9, t9_value);
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(article);
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { item } = $$props;
	e
	const writable_props = ["item"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<World> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("World", $$slots, []);

	$$self.$set = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
	};

	$$self.$capture_state = () => ({ favorite: _routes_index_svelte__WEBPACK_IMPORTED_MODULE_1__["favorite"], item });

	$$self.$inject_state = $$props => {
		if ("item" in $$props) $$invalidate(0, item = $$props.item);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [item];
}

class World extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-sakdfv-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { item: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "World",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*item*/ ctx[0] === undefined && !("item" in props)) {
			console.warn("<World> was created without expected prop 'item'");
		}
	}

	get item() {
		throw new Error("<World>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set item(value) {
		throw new Error("<World>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (World);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/Loader.svelte */ "./src/components/Loader.svelte");
/* harmony import */ var _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! ../components/World.svelte */ "./src/components/World.svelte");
/* src/routes/index.svelte generated by Svelte v3.22.2 */


const { console: console_1, document: document_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];



const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-mj86kf-style";
	style.textContent = "div.svelte-mj86kf{display:grid;background-color:#1b1b30;width:100vw;justify-content:center}section.svelte-mj86kf{display:grid;grid-template-columns:repeat(auto-fit, minmax(200px, 1fr));justify-content:center;gap:2rem;margin:auto;width:70vw;min-height:100vh}.sort.svelte-mj86kf{display:grid;grid-template-columns:100px 100px 100px 100px;gap:10px;width:90vw;margin:auto;justify-content:center}label.svelte-mj86kf{color:white;margin:auto;padding:1rem;text-align:1.9rem}.button.svelte-mj86kf{height:30px;background-color:indigo;color:white;outline:none}.searchbar.svelte-mj86kf{align-content:center;width:100vw;text-align:center}.search-input.svelte-mj86kf{border-radius:4px;border:1px solid black;padding:1rem;font-size:20px;margin:15px;outline:none;width:30rem}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHN2ZWx0ZTpoZWFkPlxuXHQ8dGl0bGU+Q29yb25hIGluZm9ybWF0aW9uPC90aXRsZT5cbjwvc3ZlbHRlOmhlYWQ+XG5cbjxzY3JpcHQ+XG5cdGltcG9ydCB7IG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCJcblx0aW1wb3J0IExvYWRlciBmcm9tIFwiLi4vY29tcG9uZW50cy9Mb2FkZXIuc3ZlbHRlXCJcblx0aW1wb3J0IFdvcmxkIGZyb20gXCIuLi9jb21wb25lbnRzL1dvcmxkLnN2ZWx0ZVwiXG5cblxuXHRsZXQgd29ybGQgPSBbXVxuXHRsZXQgc2VhcmNoZWQgPSBbXVxuXHRsZXQgQWxsT3ZlcldvcmxkXG5cbiAgICBvbk1vdW50KCAoKSA9PiB7XG5cdFx0ZmV0Y2goYENvcm9uYS5qc29uYClcblx0XHQudGhlbiggcmVzcG9uc2UgPT4gcmVzcG9uc2UuanNvbigpIClcbiAgICAgICAgLnRoZW4oIGpzb24gPT4ge1xuXHRcdFx0Ly8gV29ybGRcblx0XHRcdHdvcmxkID0ganNvbi5Db3VudHJpZXNcblx0XHRcdHNlYXJjaGVkID0gd29ybGRcblx0XHRcdEFsbE92ZXJXb3JsZCAgPSBqc29uLkdsb2JhbFxuXHRcdFx0Y29uc29sZS5sb2coQWxsT3ZlcldvcmxkKVxuICAgICAgICB9XG4gICAgICAgICkuY2F0Y2goKGVycikgPT4gY29uc29sZS5sb2coZXJyKSlcblx0fSApXG5cblx0bGV0IG9yZGVyID0gXCJ0aXRsZVwiXG4gICAgJDogIHN3aXRjaChvcmRlcil7ICAgICAgXG5cdFx0Y2FzZSAndGl0bGUnOiBzZWFyY2hlZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuQ291bnRyeSA+IGIuQ291bnRyeSA/IDEgOiAtMSk7YnJlYWtcbiAgICAgICAgICAgIGNhc2UgJ2RlYXRoJzogc2VhcmNoZWQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLlRvdGFsRGVhdGhzIDwgYi5Ub3RhbERlYXRocyA/IDEgOiAtMSk7IGJyZWFrXG4gICAgICAgICAgICBjYXNlICdpbmZlY3RlZCc6IHNlYXJjaGVkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Ub3RhbENvbmZpcm1lZCA8IGIuVG90YWxDb25maXJtZWQgPyAxIDogLTEpOyBicmVha1xuICAgICAgICAgICAgY2FzZSAncmVjb3ZlcmVkJzogc2VhcmNoZWQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLlRvdGFsUmVjb3ZlcmVkIDwgYi5Ub3RhbFJlY292ZXJlZCA/IDEgOiAtMSk7IGJyZWFrXG5cdH1cblxuXHQgICAgbGV0IHNlYXJjaCA9IFwiXCJcbiAgICBjb25zdCBmaWx0ZXJSZXN1bHQgPSAoKSA9PiB7XG5cdFx0aWYoc2VhcmNoID09PSBcIiBcIil7XG5cdFx0XHRzZWFyY2hlZCA9IHdvcmxkXG5cdFx0fWVsc2Uge1xuXHRcdFx0c2VhcmNoZWQgPSB3b3JsZC5maWx0ZXIoIHdvcmxkID0+IHdvcmxkLkNvdW50cnkudG9Mb3dlckNhc2UoKS5pbmNsdWRlcyhzZWFyY2gudG9Mb3dlckNhc2UoKSkpXG5cdFx0fVxuICAgIH1cblxuXG4vKlxuXHRjb25zdCBidG5Db250YWluZXIgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKFwiI215RGl2XCIpO1xuXHRjb25zdCBidG5zID0gYnRuQ29udGFpbmVyLnF1ZXJ5U2VsZWN0b3IoXCIuYnRuXCIpXG5cdGZvcih2YXIgaSA9IDA7IGkgPCBidG5zLmxlbmd0aDsgaSsrKSB7XG5cdFx0YnRuc1tpXS5hZGRFdmVudExpc3RlbmVyKFwiY2xpY2tcIiwgZnVuY3Rpb24oKSB7XG5cdFx0XHR2YXIgY3VycmVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRzQnlDbGFzc05hbWUoXCJhY3RpdmVcIik7XG5cblx0XHRcdGlmKGN1cnJlbnQubGVuZ3RoID4gMCkge1xuXHRcdFx0XHRjdXJyZW50WzBdLmNsYXNzTmFtZSA9IGN1cnJlbnRbMF0uY2xhc3NOYW1lLnJlcGxhY2UoXCIgYWN0aXZlXCIsIFwiXCIpO1xuXHRcdFx0fVxuXG5cdFx0XHR0aGlzLmNsYXNzTmFtZSArPSBcIiBhY3RpdmVcIlxuXHRcdH0pXG5cdH1cblxuKi9cblx0ZXhwb3J0IGxldCBmYXZvcml0ZXMgPSBbXVxuXG5cdGNvbnN0IGFkZFRvRmF2b3JpdGUgPSAoaXRlbSkgPT4ge1xuXHRcdGNvbnN0IGZvdW5kID0gZmF2b3JpdGVzLmZpbmQoZmF2ID0+IGZhdi5uYW1lID09PSBpdGVtLkNvdW50cnkpXG5cdFx0Y29uc29sZS5sb2coaXRlbSlcblx0XHRpZihmb3VuZCl7XG5cdFx0XHRyZXR1cm47XG5cdFx0fWVsc2Uge1xuXHRcdFx0ZmF2b3JpdGVzLnB1c2goe1xuXHRcdFx0XHRuYW1lOiBpdGVtLkNvdW50cnlcblx0XHRcdH0pXG5cdFx0Y29uc29sZS5sb2coZmF2b3JpdGVzKVxuXHRcdH1cblx0fVxuXG5cblx0Y29uc3QgYnV0dG9ucyA9IFtcblx0XHR7b3JkZXI6IFwiVGl0bGVcIiwgb3JkZXJUeXBlOiBcInRpdGxlXCJ9LFxuXHRcdHtvcmRlcjogXCJEZWF0aFwiLCBvcmRlclR5cGU6IFwiZGVhdGhcIn0sXG5cdFx0e29yZGVyOiBcIkluZmVjdGVkXCIsIG9yZGVyVHlwZTogXCJpbmZlY3RlZFwifSxcblx0XHR7b3JkZXI6IFwiUmVjb3ZlcmVkXCIsIG9yZGVyVHlwZTogXCJyZWNvdmVyZWRcIn1cblx0XVxuXG5cblx0bGV0IHggPSBkb2N1bWVudC5hY3RpdmVFbGVtZW50LnRhZ05hbWU7XG5cbjwvc2NyaXB0PlxuXG48ZGl2PlxuXHQ8bGFiZWwgZm9yPVwiYnRuXCIgPlNvcnQgYnk6PC9sYWJlbD5cblx0PGRpdiBjbGFzcz1cInNvcnRcIiBpZD1cIm15RGl2XCI+XG5cdHsjZWFjaCBidXR0b25zIGFzIGJ1dHRvbn1cblx0XHQ8YnV0dG9uIGlkPVwiYnRuXCIgY2xhc3M9XCJidXR0b25cIiBvbjpjbGljaz17KCkgPT4gb3JkZXIgPSBgJHtidXR0b24ub3JkZXJUeXBlfWB9ID57YnV0dG9uLm9yZGVyfTwvYnV0dG9uPlxuXHR7L2VhY2h9XG5cblx0PC9kaXY+XG5cdDxkaXYgY2xhc3M9XCJzZWFyY2hiYXJcIj5cbiAgICAgICAgPGlucHV0IGF1dG9jb21wbGV0ZT1cIm9mZlwiICBjbGFzcz1cInNlYXJjaC1pbnB1dFwiIHR5cGU9XCJzZWFyY2hcIiBwbGFjZWhvbGRlcj1cIlNlYXJjaCBhZnRlciBjb3VudHJ5XCIgYmluZDp2YWx1ZT17c2VhcmNofSBvbjppbnB1dHxwcmV2ZW50RGVmYXVsdD17ZmlsdGVyUmVzdWx0fS8+XG4gICAgPC9kaXY+XG5cdDxzZWN0aW9uPlxuXHRcdHsjZWFjaCBzZWFyY2hlZCBhcyBpdGVtfVxuXHRcdFx0PFdvcmxkIGl0ZW09e2l0ZW19IGFkZFRvRmF2b3JpdGU9e2FkZFRvRmF2b3JpdGV9IC8+XG5cdFx0ezplbHNlfVxuXHRcdDxkaXY+PC9kaXY+XG5cdFx0PGRpdj48L2Rpdj5cblx0XHRcdDxMb2FkZXIgLz5cblx0XHQ8ZGl2PjwvZGl2PlxuXHRcdDxkaXY+PC9kaXY+XG5cdFx0ey9lYWNofSAgIFxuXHQ8L3NlY3Rpb24+XG48L2Rpdj5cblxuPHN0eWxlPlxuXHRkaXYge1xuXHRcdGRpc3BsYXk6IGdyaWQ7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogIzFiMWIzMDtcblx0XHR3aWR0aDogMTAwdnc7XG5cdFx0anVzdGlmeS1jb250ZW50OiBjZW50ZXI7XG5cdH1cbiAgICBzZWN0aW9ue1xuXHRcdGRpc3BsYXk6IGdyaWQ7XG4gICAgICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogcmVwZWF0KGF1dG8tZml0LCBtaW5tYXgoMjAwcHgsIDFmcikpO1xuICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0XHRnYXA6IDJyZW07XG4gICAgICAgIG1hcmdpbjogYXV0bztcblx0XHR3aWR0aDogNzB2dztcblx0XHRtaW4taGVpZ2h0OiAxMDB2aDtcbiAgICB9XG5cdC5zb3J0IHtcblx0XHRkaXNwbGF5OiBncmlkO1xuXHRcdGdyaWQtdGVtcGxhdGUtY29sdW1uczogMTAwcHggMTAwcHggMTAwcHggMTAwcHg7XG5cdFx0Z2FwOiAxMHB4O1xuXHRcdHdpZHRoOiA5MHZ3O1xuXHRcdG1hcmdpbjogYXV0bztcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0fVxuXHRsYWJlbCB7XG5cdFx0Y29sb3I6IHdoaXRlO1xuXHRcdG1hcmdpbjogYXV0bztcblx0XHRwYWRkaW5nOiAxcmVtO1xuXHRcdHRleHQtYWxpZ246IDEuOXJlbTtcblx0fVxuXHQuYnV0dG9uIHtcblx0XHRoZWlnaHQ6IDMwcHg7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogaW5kaWdvO1xuXHRcdGNvbG9yOiB3aGl0ZTtcblx0XHRvdXRsaW5lOiBub25lO1xuXHR9XG5cdC5zZWFyY2hiYXIge1xuICAgICAgICBhbGlnbi1jb250ZW50OiBjZW50ZXI7XG4gICAgICAgIHdpZHRoOiAxMDB2dztcbiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIH1cbiAgICAuc2VhcmNoLWlucHV0IHtcbiAgICAgICAgYm9yZGVyLXJhZGl1czogNHB4O1xuICAgICAgICBib3JkZXI6IDFweCBzb2xpZCBibGFjaztcbiAgICAgICAgcGFkZGluZzogMXJlbTtcbiAgICAgICAgZm9udC1zaXplOiAyMHB4O1xuICAgICAgICBtYXJnaW46IDE1cHg7XG4gICAgICAgIG91dGxpbmU6IG5vbmU7XG4gICAgICAgIHdpZHRoOiAzMHJlbTtcbiAgICB9XG5cbjwvc3R5bGU+XG5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFrSEMsR0FBRyxjQUFDLENBQUMsQUFDSixPQUFPLENBQUUsSUFBSSxDQUNiLGdCQUFnQixDQUFFLE9BQU8sQ0FDekIsS0FBSyxDQUFFLEtBQUssQ0FDWixlQUFlLENBQUUsTUFBTSxBQUN4QixDQUFDLEFBQ0UscUJBQU8sQ0FBQyxBQUNWLE9BQU8sQ0FBRSxJQUFJLENBQ1AscUJBQXFCLENBQUUsT0FBTyxRQUFRLENBQUMsQ0FBQyxPQUFPLEtBQUssQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQzNELGVBQWUsQ0FBRSxNQUFNLENBQzdCLEdBQUcsQ0FBRSxJQUFJLENBQ0gsTUFBTSxDQUFFLElBQUksQ0FDbEIsS0FBSyxDQUFFLElBQUksQ0FDWCxVQUFVLENBQUUsS0FBSyxBQUNmLENBQUMsQUFDSixLQUFLLGNBQUMsQ0FBQyxBQUNOLE9BQU8sQ0FBRSxJQUFJLENBQ2IscUJBQXFCLENBQUUsS0FBSyxDQUFDLEtBQUssQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUM5QyxHQUFHLENBQUUsSUFBSSxDQUNULEtBQUssQ0FBRSxJQUFJLENBQ1gsTUFBTSxDQUFFLElBQUksQ0FDWixlQUFlLENBQUUsTUFBTSxBQUN4QixDQUFDLEFBQ0QsS0FBSyxjQUFDLENBQUMsQUFDTixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxJQUFJLENBQ1osT0FBTyxDQUFFLElBQUksQ0FDYixVQUFVLENBQUUsTUFBTSxBQUNuQixDQUFDLEFBQ0QsT0FBTyxjQUFDLENBQUMsQUFDUixNQUFNLENBQUUsSUFBSSxDQUNaLGdCQUFnQixDQUFFLE1BQU0sQ0FDeEIsS0FBSyxDQUFFLEtBQUssQ0FDWixPQUFPLENBQUUsSUFBSSxBQUNkLENBQUMsQUFDRCxVQUFVLGNBQUMsQ0FBQyxBQUNMLGFBQWEsQ0FBRSxNQUFNLENBQ3JCLEtBQUssQ0FBRSxLQUFLLENBQ1osVUFBVSxDQUFFLE1BQU0sQUFDdEIsQ0FBQyxBQUNELGFBQWEsY0FBQyxDQUFDLEFBQ1gsYUFBYSxDQUFFLEdBQUcsQ0FDbEIsTUFBTSxDQUFFLEdBQUcsQ0FBQyxLQUFLLENBQUMsS0FBSyxDQUN2QixPQUFPLENBQUUsSUFBSSxDQUNiLFNBQVMsQ0FBRSxJQUFJLENBQ2YsTUFBTSxDQUFFLElBQUksQ0FDWixPQUFPLENBQUUsSUFBSSxDQUNiLEtBQUssQ0FBRSxLQUFLLEFBQ2hCLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document_1.head, style);
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[12] = list[i];
	return child_ctx;
}

function get_each_context_1(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[15] = list[i];
	return child_ctx;
}

// (93:1) {#each buttons as button}
function create_each_block_1(ctx) {
	let button;
	let t_value = /*button*/ ctx[15].order + "";
	let t;
	let dispose;

	function click_handler(...args) {
		return /*click_handler*/ ctx[10](/*button*/ ctx[15], ...args);
	}

	const block = {
		c: function create() {
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "BUTTON", { id: true, class: true });
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(button_nodes, t_value);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "id", "btn");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "class", "button svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 93, 2, 2260);
		},
		m: function mount(target, anchor, remount) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, button, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button, t);
			if (remount) dispose();
			dispose = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(button, "click", click_handler, false, false, false);
		},
		p: function update(new_ctx, dirty) {
			ctx = new_ctx;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(button);
			dispose();
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block_1.name,
		type: "each",
		source: "(93:1) {#each buttons as button}",
		ctx
	});

	return block;
}

// (104:2) {:else}
function create_else_block(ctx) {
	let div0;
	let t0;
	let div1;
	let t1;
	let t2;
	let div2;
	let t3;
	let div3;
	let current;
	const loader = new _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(loader.$$.fragment);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			this.h();
		},
		l: function claim(nodes) {
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(loader.$$.fragment, nodes);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 104, 2, 2689);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 105, 2, 2703);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 107, 2, 2731);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 108, 2, 2745);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(loader, target, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t3, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div3, anchor);
			current = true;
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(loader.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(loader.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div1);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(loader, detaching);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t2);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div2);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t3);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div3);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_else_block.name,
		type: "else",
		source: "(104:2) {:else}",
		ctx
	});

	return block;
}

// (102:2) {#each searched as item}
function create_each_block(ctx) {
	let current;

	const world_1 = new _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__["default"]({
			props: {
				item: /*item*/ ctx[12],
				addToFavorite: /*addToFavorite*/ ctx[4]
			},
			$$inline: true
		});

	const block = {
		c: function create() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(world_1.$$.fragment);
		},
		l: function claim(nodes) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(world_1.$$.fragment, nodes);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(world_1, target, anchor);
			current = true;
		},
		p: function update(ctx, dirty) {
			const world_1_changes = {};
			if (dirty & /*searched*/ 1) world_1_changes.item = /*item*/ ctx[12];
			world_1.$set(world_1_changes);
		},
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(world_1.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(world_1.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(world_1, detaching);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_each_block.name,
		type: "each",
		source: "(102:2) {#each searched as item}",
		ctx
	});

	return block;
}

function create_fragment(ctx) {
	let t0;
	let div2;
	let label;
	let t1;
	let t2;
	let div0;
	let t3;
	let div1;
	let input;
	let t4;
	let section;
	let current;
	let dispose;
	let each_value_1 = /*buttons*/ ctx[5];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value_1);
	let each_blocks_1 = [];

	for (let i = 0; i < each_value_1.length; i += 1) {
		each_blocks_1[i] = create_each_block_1(get_each_context_1(ctx, each_value_1, i));
	}

	let each_value = /*searched*/ ctx[0];
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	const out = i => Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i], 1, 1, () => {
		each_blocks[i] = null;
	});

	let each1_else = null;

	if (!each_value.length) {
		each1_else = create_else_block(ctx);
	}

	const block = {
		c: function create() {
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("label");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Sort by:");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].c();
			}

			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("input");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("section");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			if (each1_else) {
				each1_else.c();
			}

			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1136c5u\"]", document_1.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			label = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "LABEL", { for: true, class: true });
			var label_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(label);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(label_nodes, "Sort by:");
			label_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true, id: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].l(div0_nodes);
			}

			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			input = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "INPUT", {
				autocomplete: true,
				class: true,
				type: true,
				placeholder: true
			});

			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			section = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "SECTION", { class: true });
			var section_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(section);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].l(section_nodes);
			}

			if (each1_else) {
				each1_else.l(section_nodes);
			}

			section_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document_1.title = "Corona information";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "for", "btn");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(label, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(label, file, 90, 1, 2165);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "sort svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "id", "myDiv");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 91, 1, 2201);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "autocomplete", "off");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "class", "search-input svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "type", "search");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(input, "placeholder", "Search after country");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(input, file, 98, 8, 2415);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "searchbar svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 97, 1, 2383);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(section, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(section, file, 100, 1, 2585);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "svelte-mj86kf");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 89, 0, 2158);
		},
		m: function mount(target, anchor, remount) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t0, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div2, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, label);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(label, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div0);

			for (let i = 0; i < each_blocks_1.length; i += 1) {
				each_blocks_1[i].m(div0, null);
			}

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, input);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*search*/ ctx[2]);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, section);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(section, null);
			}

			if (each1_else) {
				each1_else.m(section, null);
			}

			current = true;
			if (remount) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);

			dispose = [
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "input", /*input_input_handler*/ ctx[11]),
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["listen_dev"])(input, "input", Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["prevent_default"])(/*filterResult*/ ctx[3]), false, true, false)
			];
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*order, buttons*/ 34) {
				each_value_1 = /*buttons*/ ctx[5];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value_1);
				let i;

				for (i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks_1[i]) {
						each_blocks_1[i].p(child_ctx, dirty);
					} else {
						each_blocks_1[i] = create_each_block_1(child_ctx);
						each_blocks_1[i].c();
						each_blocks_1[i].m(div0, null);
					}
				}

				for (; i < each_blocks_1.length; i += 1) {
					each_blocks_1[i].d(1);
				}

				each_blocks_1.length = each_value_1.length;
			}

			if (dirty & /*search*/ 4) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_input_value"])(input, /*search*/ ctx[2]);
			}

			if (dirty & /*searched, addToFavorite*/ 17) {
				each_value = /*searched*/ ctx[0];
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_each_argument"])(each_value);
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i], 1);
						each_blocks[i].m(section, null);
					}
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["group_outros"])();

				for (i = each_value.length; i < each_blocks.length; i += 1) {
					out(i);
				}

				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["check_outros"])();

				if (each_value.length) {
					if (each1_else) {
						each1_else.d(1);
						each1_else = null;
					}
				} else if (!each1_else) {
					each1_else = create_else_block(ctx);
					each1_else.c();
					each1_else.m(section, null);
				}
			}
		},
		i: function intro(local) {
			if (current) return;

			for (let i = 0; i < each_value.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(each_blocks[i]);
			}

			current = true;
		},
		o: function outro(local) {
			each_blocks = each_blocks.filter(Boolean);

			for (let i = 0; i < each_blocks.length; i += 1) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(each_blocks[i]);
			}

			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t0);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks_1, detaching);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_each"])(each_blocks, detaching);
			if (each1_else) each1_else.d();
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["run_all"])(dispose);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let world = [];
	let searched = [];
	let AllOverWorld;

	Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(() => {
		fetch(`Corona.json`).then(response => response.json()).then(json => {
			// World
			$$invalidate(7, world = json.Countries);

			$$invalidate(0, searched = world);
			AllOverWorld = json.Global;
			console.log(AllOverWorld);
		}).catch(err => console.log(err));
	});

	let order = "title";
	let search = "";

	const filterResult = () => {
		if (search === " ") {
			$$invalidate(0, searched = world);
		} else {
			$$invalidate(0, searched = world.filter(world => world.Country.toLowerCase().includes(search.toLowerCase())));
		}
	};

	let { favorites = [] } = $$props;

	const addToFavorite = item => {
		const found = favorites.find(fav => fav.name === item.Country);
		console.log(item);

		if (found) {
			return;
		} else {
			favorites.push({ name: item.Country });
			console.log(favorites);
		}
	};

	const buttons = [
		{ order: "Title", orderType: "title" },
		{ order: "Death", orderType: "death" },
		{ order: "Infected", orderType: "infected" },
		{
			order: "Recovered",
			orderType: "recovered"
		}
	];

	let x = document.activeElement.tagName;
	const writable_props = ["favorites"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<Routes> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("Routes", $$slots, []);
	const click_handler = button => $$invalidate(1, order = `${button.orderType}`);

	function input_input_handler() {
		search = this.value;
		$$invalidate(2, search);
	}

	$$self.$set = $$props => {
		if ("favorites" in $$props) $$invalidate(6, favorites = $$props.favorites);
	};

	$$self.$capture_state = () => ({
		onMount: svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"],
		Loader: _components_Loader_svelte__WEBPACK_IMPORTED_MODULE_2__["default"],
		World: _components_World_svelte__WEBPACK_IMPORTED_MODULE_3__["default"],
		world,
		searched,
		AllOverWorld,
		order,
		search,
		filterResult,
		favorites,
		addToFavorite,
		buttons,
		x
	});

	$$self.$inject_state = $$props => {
		if ("world" in $$props) $$invalidate(7, world = $$props.world);
		if ("searched" in $$props) $$invalidate(0, searched = $$props.searched);
		if ("AllOverWorld" in $$props) AllOverWorld = $$props.AllOverWorld;
		if ("order" in $$props) $$invalidate(1, order = $$props.order);
		if ("search" in $$props) $$invalidate(2, search = $$props.search);
		if ("favorites" in $$props) $$invalidate(6, favorites = $$props.favorites);
		if ("x" in $$props) x = $$props.x;
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*order, world*/ 130) {
			$: switch (order) {
				case "title":
					$$invalidate(0, searched = world.sort((a, b) => a.Country > b.Country ? 1 : -1));
					break;
				case "death":
					$$invalidate(0, searched = world.sort((a, b) => a.TotalDeaths < b.TotalDeaths ? 1 : -1));
					break;
				case "infected":
					$$invalidate(0, searched = world.sort((a, b) => a.TotalConfirmed < b.TotalConfirmed ? 1 : -1));
					break;
				case "recovered":
					$$invalidate(0, searched = world.sort((a, b) => a.TotalRecovered < b.TotalRecovered ? 1 : -1));
					break;
			}
		}
	};

	return [
		searched,
		order,
		search,
		filterResult,
		addToFavorite,
		buttons,
		favorites,
		world,
		AllOverWorld,
		x,
		click_handler,
		input_input_handler
	];
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document_1.getElementById("svelte-mj86kf-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { favorites: 6 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "Routes",
			options,
			id: create_fragment.name
		});
	}

	get favorites() {
		throw new Error("<Routes>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set favorites(value) {
		throw new Error("<Routes>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9Xb3JsZC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9pbmRleC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUNrRDs7Ozs7Ozs7Ozs7Ozt5QkFROUIsR0FBSSxJQUFDLE9BQU87Ozs7O3lCQUNTLEdBQUksSUFBQyxjQUFjLENBQUMsUUFBUSxHQUFHLE9BQU8sQ0FBQyx1QkFBdUIsRUFBRSxHQUFHOzs7Ozt5QkFDeEUsR0FBSSxJQUFDLFdBQVcsQ0FBQyxRQUFRLEdBQUcsT0FBTyxDQUFDLHVCQUF1QixFQUFFLEdBQUc7Ozs7O3lCQUMzRCxHQUFJLElBQUMsY0FBYyxDQUFDLFFBQVEsR0FBRyxPQUFPLENBQUMsdUJBQXVCLEVBQUUsR0FBRzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkVBQ3pGLGFBQWEsVUFBQyxHQUFJLE9BQWxCLGFBQWEsVUFBQyxHQUFJOzs7Ozs7Ozs7K0RBSmpCLEdBQUksSUFBQyxPQUFPOytEQUNTLEdBQUksSUFBQyxjQUFjLENBQUMsUUFBUSxHQUFHLE9BQU8sQ0FBQyx1QkFBdUIsRUFBRSxHQUFHOytEQUN4RSxHQUFJLElBQUMsV0FBVyxDQUFDLFFBQVEsR0FBRyxPQUFPLENBQUMsdUJBQXVCLEVBQUUsR0FBRzsrREFDM0QsR0FBSSxJQUFDLGNBQWMsQ0FBQyxRQUFRLEdBQUcsT0FBTyxDQUFDLHVCQUF1QixFQUFFLEdBQUc7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7T0FWaEcsSUFBSTtDQUNmLENBQUM7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ0UrQjtBQUNnQjtBQUNGOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBCQXNGb0MsR0FBTSxLQUFDLEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O21CQVMvRSxHQUFJO3FDQUFpQixHQUFhOzs7Ozs7Ozs7Ozs7Ozs7Ozs7K0RBQWxDLEdBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztnQ0FWWixHQUFPOzs7O2tDQUFaLE1BQUk7Ozs7K0JBU0UsR0FBUTs7OztnQ0FBYixNQUFJOzs7Ozs7Ozs7O2lCQUFKLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7NkZBSDZHLEdBQU07Ozs7Ozs7Ozs7Ozs7Ozs7O2dMQUEyQixHQUFZOzs7OzsrQkFOMUosR0FBTzs7OztpQ0FBWixNQUFJOzs7Ozs7Ozs7Ozs7Ozs7O3dDQUFKLE1BQUk7Ozs7OEZBTThHLEdBQU07Ozs7OEJBR2xILEdBQVE7Ozs7K0JBQWIsTUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozt3QkFBSixNQUFJOzs7Ozs7bUJBQUosTUFBSTs7Ozs7Ozs7Ozs7Ozs7O2tDQUFKLE1BQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7S0EzRkgsS0FBSztLQUNMLFFBQVE7S0FDUixZQUFZOztDQUViLHNEQUFPO0VBQ1QsS0FBSyxnQkFDSixJQUFJLENBQUUsUUFBUSxJQUFJLFFBQVEsQ0FBQyxJQUFJLElBQ3pCLElBQUksQ0FBRSxJQUFJOzttQkFFaEIsS0FBSyxHQUFHLElBQUksQ0FBQyxTQUFTOzttQkFDdEIsUUFBUSxHQUFHLEtBQUs7R0FDaEIsWUFBWSxHQUFJLElBQUksQ0FBQyxNQUFNO0dBQzNCLE9BQU8sQ0FBQyxHQUFHLENBQUMsWUFBWTtLQUVqQixLQUFLLENBQUUsR0FBRyxJQUFLLE9BQU8sQ0FBQyxHQUFHLENBQUMsR0FBRzs7O0tBR25DLEtBQUssR0FBRyxPQUFPO0tBUVgsTUFBTSxHQUFHLEVBQUU7O09BQ1YsWUFBWTtNQUNqQixNQUFNLEtBQUssR0FBRzttQkFDaEIsUUFBUSxHQUFHLEtBQUs7O21CQUVoQixRQUFRLEdBQUcsS0FBSyxDQUFDLE1BQU0sQ0FBRSxLQUFLLElBQUksS0FBSyxDQUFDLE9BQU8sQ0FBQyxXQUFXLEdBQUcsUUFBUSxDQUFDLE1BQU0sQ0FBQyxXQUFXOzs7O09BcUJoRixTQUFTOztPQUVkLGFBQWEsR0FBSSxJQUFJO1FBQ3BCLEtBQUssR0FBRyxTQUFTLENBQUMsSUFBSSxDQUFDLEdBQUcsSUFBSSxHQUFHLENBQUMsSUFBSSxLQUFLLElBQUksQ0FBQyxPQUFPO0VBQzdELE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSTs7TUFDYixLQUFLOzs7R0FHUCxTQUFTLENBQUMsSUFBSSxHQUNiLElBQUksRUFBRSxJQUFJLENBQUMsT0FBTztHQUVwQixPQUFPLENBQUMsR0FBRyxDQUFDLFNBQVM7Ozs7T0FLaEIsT0FBTztJQUNYLEtBQUssRUFBRSxPQUFPLEVBQUUsU0FBUyxFQUFFLE9BQU87SUFDbEMsS0FBSyxFQUFFLE9BQU8sRUFBRSxTQUFTLEVBQUUsT0FBTztJQUNsQyxLQUFLLEVBQUUsVUFBVSxFQUFFLFNBQVMsRUFBRSxVQUFVOztHQUN4QyxLQUFLLEVBQUUsV0FBVztHQUFFLFNBQVMsRUFBRSxXQUFXOzs7O0tBSXhDLENBQUMsR0FBRyxRQUFRLENBQUMsYUFBYSxDQUFDLE9BQU87Ozs7Ozs7OztpREFRVyxLQUFLLE1BQU0sTUFBTSxDQUFDLFNBQVM7OztFQUt3QyxNQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0dBdEV2SCxDQUFDLFVBQVUsS0FBSztTQUNiLE9BQU87cUJBQUUsUUFBUSxHQUFHLEtBQUssQ0FBQyxJQUFJLEVBQUcsQ0FBQyxFQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsT0FBTyxHQUFHLENBQUMsQ0FBQyxPQUFPLEdBQUcsQ0FBQyxJQUFJLENBQUM7O1NBQzdELE9BQU87cUJBQUUsUUFBUSxHQUFHLEtBQUssQ0FBQyxJQUFJLEVBQUcsQ0FBQyxFQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsV0FBVyxHQUFHLENBQUMsQ0FBQyxXQUFXLEdBQUcsQ0FBQyxJQUFJLENBQUM7O1NBQy9FLFVBQVU7cUJBQUUsUUFBUSxHQUFHLEtBQUssQ0FBQyxJQUFJLEVBQUcsQ0FBQyxFQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsY0FBYyxHQUFHLENBQUMsQ0FBQyxjQUFjLEdBQUcsQ0FBQyxJQUFJLENBQUM7O1NBQ3hGLFdBQVc7cUJBQUUsUUFBUSxHQUFHLEtBQUssQ0FBQyxJQUFJLEVBQUcsQ0FBQyxFQUFDLENBQUMsS0FBSyxDQUFDLENBQUMsY0FBYyxHQUFHLENBQUMsQ0FBQyxjQUFjLEdBQUcsQ0FBQyxJQUFJLENBQUMiLCJmaWxlIjoiOWEyZjc1ZmNjODM0M2ZkNjMyZTMvaW5kZXguaW5kZXguanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuXHRpbXBvcnQgeyBmYXZvcml0ZSB9IGZyb20gXCIuLi9yb3V0ZXMvaW5kZXguc3ZlbHRlXCJcblx0ZXhwb3J0IGxldCBpdGVtXG5cdGVcblxuPC9zY3JpcHQ+XG5cblxuPGFydGljbGUgPlxuXHQ8aDEgY2xhc3M9XCJ3aGl0ZVwiPntpdGVtLkNvdW50cnl9PC9oMT5cblx0PHAgY2xhc3M9XCJ0ZXh0IG9yYW5nZVwiPlRvdGFsIGluZmVjdGVkOiB7aXRlbS5Ub3RhbENvbmZpcm1lZC50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG5cdDxwIGNsYXNzPVwidGV4dCByZWRcIj5Ub3RhbCBkZWF0aHM6IHtpdGVtLlRvdGFsRGVhdGhzLnRvU3RyaW5nKCkucmVwbGFjZSgvXFxCKD89KFxcZHszfSkrKD8hXFxkKSkvZywgXCIsXCIpfTwvcD5cblx0PHAgY2xhc3M9XCJ0ZXh0IGdyZWVuXCI+VG90YWwgcmVjb3ZlcmVkOiB7aXRlbS5Ub3RhbFJlY292ZXJlZC50b1N0cmluZygpLnJlcGxhY2UoL1xcQig/PShcXGR7M30pKyg/IVxcZCkpL2csIFwiLFwiKX08L3A+XG5cdDxidXR0b24gb246Y2xpY2s9e2FkZFRvRmF2b3JpdGUoaXRlbSl9IGNsYXNzPVwiYnRuXCI+QWRkIHRvIGZhdm9yaXRlPC9idXR0b24+XG48L2FydGljbGU+XHRcdFxuXG48c3R5bGU+XG5cdGFydGljbGUge1xuXHRcdGJhY2tncm91bmQtY29sb3I6IHJnYmEoNCwgNCwgNCwgLjYpO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdFx0Ym9yZGVyLXJhZGl1czogMTBweDtcblx0XHRkaXNwbGF5OiBncmlkO1xuXHRcdG1heC13aWR0aDogMTVyZW07XG5cdFx0bWF4LWhlaWdodDogMTZyZW07XG5cdH1cblx0YXJ0aWNsZTpob3ZlciB7XG5cdFx0YmFja2dyb3VuZC1jb2xvcjogcmdiYSg0LCA0LCA0LCAuMik7XG5cdH1cblx0LmJ0biB7XG5cdFx0Ym9yZGVyOiAxcHggc29saWQgcmVkO1xuXHRcdG91dGxpbmU6IG5vbmU7XG5cdH1cblx0LndoaXRlIHtcblx0XHRjb2xvcjogd2hpdGU7XG5cdFx0dGV4dC1hbGlnbjogY2VudGVyO1xuXHRcdGZvbnQtc2l6ZTogMS44cmVtO1xuXHR9XG5cdC5ncmVlbiB7XG5cdFx0Y29sb3I6IGdyZWVuO1xuXHR9XG5cdC5yZWQge1xuXHRcdGNvbG9yOiByZWQ7XG5cdH1cblx0Lm9yYW5nZSB7XG5cdFx0Y29sb3I6IG9yYW5nZTtcblx0fVxuPC9zdHlsZT4iLCI8c3ZlbHRlOmhlYWQ+XG5cdDx0aXRsZT5Db3JvbmEgaW5mb3JtYXRpb248L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cblxuPHNjcmlwdD5cblx0aW1wb3J0IHsgb25Nb3VudCB9IGZyb20gXCJzdmVsdGVcIlxuXHRpbXBvcnQgTG9hZGVyIGZyb20gXCIuLi9jb21wb25lbnRzL0xvYWRlci5zdmVsdGVcIlxuXHRpbXBvcnQgV29ybGQgZnJvbSBcIi4uL2NvbXBvbmVudHMvV29ybGQuc3ZlbHRlXCJcblxuXG5cdGxldCB3b3JsZCA9IFtdXG5cdGxldCBzZWFyY2hlZCA9IFtdXG5cdGxldCBBbGxPdmVyV29ybGRcblxuICAgIG9uTW91bnQoICgpID0+IHtcblx0XHRmZXRjaChgQ29yb25hLmpzb25gKVxuXHRcdC50aGVuKCByZXNwb25zZSA9PiByZXNwb25zZS5qc29uKCkgKVxuICAgICAgICAudGhlbigganNvbiA9PiB7XG5cdFx0XHQvLyBXb3JsZFxuXHRcdFx0d29ybGQgPSBqc29uLkNvdW50cmllc1xuXHRcdFx0c2VhcmNoZWQgPSB3b3JsZFxuXHRcdFx0QWxsT3ZlcldvcmxkICA9IGpzb24uR2xvYmFsXG5cdFx0XHRjb25zb2xlLmxvZyhBbGxPdmVyV29ybGQpXG4gICAgICAgIH1cbiAgICAgICAgKS5jYXRjaCgoZXJyKSA9PiBjb25zb2xlLmxvZyhlcnIpKVxuXHR9IClcblxuXHRsZXQgb3JkZXIgPSBcInRpdGxlXCJcbiAgICAkOiAgc3dpdGNoKG9yZGVyKXsgICAgICBcblx0XHRjYXNlICd0aXRsZSc6IHNlYXJjaGVkID0gd29ybGQuc29ydCggKGEsYikgPT4gYS5Db3VudHJ5ID4gYi5Db3VudHJ5ID8gMSA6IC0xKTticmVha1xuICAgICAgICAgICAgY2FzZSAnZGVhdGgnOiBzZWFyY2hlZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxEZWF0aHMgPCBiLlRvdGFsRGVhdGhzID8gMSA6IC0xKTsgYnJlYWtcbiAgICAgICAgICAgIGNhc2UgJ2luZmVjdGVkJzogc2VhcmNoZWQgPSB3b3JsZC5zb3J0KCAoYSxiKSA9PiBhLlRvdGFsQ29uZmlybWVkIDwgYi5Ub3RhbENvbmZpcm1lZCA/IDEgOiAtMSk7IGJyZWFrXG4gICAgICAgICAgICBjYXNlICdyZWNvdmVyZWQnOiBzZWFyY2hlZCA9IHdvcmxkLnNvcnQoIChhLGIpID0+IGEuVG90YWxSZWNvdmVyZWQgPCBiLlRvdGFsUmVjb3ZlcmVkID8gMSA6IC0xKTsgYnJlYWtcblx0fVxuXG5cdCAgICBsZXQgc2VhcmNoID0gXCJcIlxuICAgIGNvbnN0IGZpbHRlclJlc3VsdCA9ICgpID0+IHtcblx0XHRpZihzZWFyY2ggPT09IFwiIFwiKXtcblx0XHRcdHNlYXJjaGVkID0gd29ybGRcblx0XHR9ZWxzZSB7XG5cdFx0XHRzZWFyY2hlZCA9IHdvcmxkLmZpbHRlciggd29ybGQgPT4gd29ybGQuQ291bnRyeS50b0xvd2VyQ2FzZSgpLmluY2x1ZGVzKHNlYXJjaC50b0xvd2VyQ2FzZSgpKSlcblx0XHR9XG4gICAgfVxuXG5cbi8qXG5cdGNvbnN0IGJ0bkNvbnRhaW5lciA9IGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoXCIjbXlEaXZcIik7XG5cdGNvbnN0IGJ0bnMgPSBidG5Db250YWluZXIucXVlcnlTZWxlY3RvcihcIi5idG5cIilcblx0Zm9yKHZhciBpID0gMDsgaSA8IGJ0bnMubGVuZ3RoOyBpKyspIHtcblx0XHRidG5zW2ldLmFkZEV2ZW50TGlzdGVuZXIoXCJjbGlja1wiLCBmdW5jdGlvbigpIHtcblx0XHRcdHZhciBjdXJyZW50ID0gZG9jdW1lbnQuZ2V0RWxlbWVudHNCeUNsYXNzTmFtZShcImFjdGl2ZVwiKTtcblxuXHRcdFx0aWYoY3VycmVudC5sZW5ndGggPiAwKSB7XG5cdFx0XHRcdGN1cnJlbnRbMF0uY2xhc3NOYW1lID0gY3VycmVudFswXS5jbGFzc05hbWUucmVwbGFjZShcIiBhY3RpdmVcIiwgXCJcIik7XG5cdFx0XHR9XG5cblx0XHRcdHRoaXMuY2xhc3NOYW1lICs9IFwiIGFjdGl2ZVwiXG5cdFx0fSlcblx0fVxuXG4qL1xuXHRleHBvcnQgbGV0IGZhdm9yaXRlcyA9IFtdXG5cblx0Y29uc3QgYWRkVG9GYXZvcml0ZSA9IChpdGVtKSA9PiB7XG5cdFx0Y29uc3QgZm91bmQgPSBmYXZvcml0ZXMuZmluZChmYXYgPT4gZmF2Lm5hbWUgPT09IGl0ZW0uQ291bnRyeSlcblx0XHRjb25zb2xlLmxvZyhpdGVtKVxuXHRcdGlmKGZvdW5kKXtcblx0XHRcdHJldHVybjtcblx0XHR9ZWxzZSB7XG5cdFx0XHRmYXZvcml0ZXMucHVzaCh7XG5cdFx0XHRcdG5hbWU6IGl0ZW0uQ291bnRyeVxuXHRcdFx0fSlcblx0XHRjb25zb2xlLmxvZyhmYXZvcml0ZXMpXG5cdFx0fVxuXHR9XG5cblxuXHRjb25zdCBidXR0b25zID0gW1xuXHRcdHtvcmRlcjogXCJUaXRsZVwiLCBvcmRlclR5cGU6IFwidGl0bGVcIn0sXG5cdFx0e29yZGVyOiBcIkRlYXRoXCIsIG9yZGVyVHlwZTogXCJkZWF0aFwifSxcblx0XHR7b3JkZXI6IFwiSW5mZWN0ZWRcIiwgb3JkZXJUeXBlOiBcImluZmVjdGVkXCJ9LFxuXHRcdHtvcmRlcjogXCJSZWNvdmVyZWRcIiwgb3JkZXJUeXBlOiBcInJlY292ZXJlZFwifVxuXHRdXG5cblxuXHRsZXQgeCA9IGRvY3VtZW50LmFjdGl2ZUVsZW1lbnQudGFnTmFtZTtcblxuPC9zY3JpcHQ+XG5cbjxkaXY+XG5cdDxsYWJlbCBmb3I9XCJidG5cIiA+U29ydCBieTo8L2xhYmVsPlxuXHQ8ZGl2IGNsYXNzPVwic29ydFwiIGlkPVwibXlEaXZcIj5cblx0eyNlYWNoIGJ1dHRvbnMgYXMgYnV0dG9ufVxuXHRcdDxidXR0b24gaWQ9XCJidG5cIiBjbGFzcz1cImJ1dHRvblwiIG9uOmNsaWNrPXsoKSA9PiBvcmRlciA9IGAke2J1dHRvbi5vcmRlclR5cGV9YH0gPntidXR0b24ub3JkZXJ9PC9idXR0b24+XG5cdHsvZWFjaH1cblxuXHQ8L2Rpdj5cblx0PGRpdiBjbGFzcz1cInNlYXJjaGJhclwiPlxuICAgICAgICA8aW5wdXQgYXV0b2NvbXBsZXRlPVwib2ZmXCIgIGNsYXNzPVwic2VhcmNoLWlucHV0XCIgdHlwZT1cInNlYXJjaFwiIHBsYWNlaG9sZGVyPVwiU2VhcmNoIGFmdGVyIGNvdW50cnlcIiBiaW5kOnZhbHVlPXtzZWFyY2h9IG9uOmlucHV0fHByZXZlbnREZWZhdWx0PXtmaWx0ZXJSZXN1bHR9Lz5cbiAgICA8L2Rpdj5cblx0PHNlY3Rpb24+XG5cdFx0eyNlYWNoIHNlYXJjaGVkIGFzIGl0ZW19XG5cdFx0XHQ8V29ybGQgaXRlbT17aXRlbX0gYWRkVG9GYXZvcml0ZT17YWRkVG9GYXZvcml0ZX0gLz5cblx0XHR7OmVsc2V9XG5cdFx0PGRpdj48L2Rpdj5cblx0XHQ8ZGl2PjwvZGl2PlxuXHRcdFx0PExvYWRlciAvPlxuXHRcdDxkaXY+PC9kaXY+XG5cdFx0PGRpdj48L2Rpdj5cblx0XHR7L2VhY2h9ICAgXG5cdDwvc2VjdGlvbj5cbjwvZGl2PlxuXG48c3R5bGU+XG5cdGRpdiB7XG5cdFx0ZGlzcGxheTogZ3JpZDtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiAjMWIxYjMwO1xuXHRcdHdpZHRoOiAxMDB2dztcblx0XHRqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjtcblx0fVxuICAgIHNlY3Rpb257XG5cdFx0ZGlzcGxheTogZ3JpZDtcbiAgICAgICAgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiByZXBlYXQoYXV0by1maXQsIG1pbm1heCgyMDBweCwgMWZyKSk7XG4gICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHRcdGdhcDogMnJlbTtcbiAgICAgICAgbWFyZ2luOiBhdXRvO1xuXHRcdHdpZHRoOiA3MHZ3O1xuXHRcdG1pbi1oZWlnaHQ6IDEwMHZoO1xuICAgIH1cblx0LnNvcnQge1xuXHRcdGRpc3BsYXk6IGdyaWQ7XG5cdFx0Z3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxMDBweCAxMDBweCAxMDBweCAxMDBweDtcblx0XHRnYXA6IDEwcHg7XG5cdFx0d2lkdGg6IDkwdnc7XG5cdFx0bWFyZ2luOiBhdXRvO1xuXHRcdGp1c3RpZnktY29udGVudDogY2VudGVyO1xuXHR9XG5cdGxhYmVsIHtcblx0XHRjb2xvcjogd2hpdGU7XG5cdFx0bWFyZ2luOiBhdXRvO1xuXHRcdHBhZGRpbmc6IDFyZW07XG5cdFx0dGV4dC1hbGlnbjogMS45cmVtO1xuXHR9XG5cdC5idXR0b24ge1xuXHRcdGhlaWdodDogMzBweDtcblx0XHRiYWNrZ3JvdW5kLWNvbG9yOiBpbmRpZ287XG5cdFx0Y29sb3I6IHdoaXRlO1xuXHRcdG91dGxpbmU6IG5vbmU7XG5cdH1cblx0LnNlYXJjaGJhciB7XG4gICAgICAgIGFsaWduLWNvbnRlbnQ6IGNlbnRlcjtcbiAgICAgICAgd2lkdGg6IDEwMHZ3O1xuICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgfVxuICAgIC5zZWFyY2gtaW5wdXQge1xuICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7XG4gICAgICAgIGJvcmRlcjogMXB4IHNvbGlkIGJsYWNrO1xuICAgICAgICBwYWRkaW5nOiAxcmVtO1xuICAgICAgICBmb250LXNpemU6IDIwcHg7XG4gICAgICAgIG1hcmdpbjogMTVweDtcbiAgICAgICAgb3V0bGluZTogbm9uZTtcbiAgICAgICAgd2lkdGg6IDMwcmVtO1xuICAgIH1cblxuPC9zdHlsZT5cblxuIl0sInNvdXJjZVJvb3QiOiIifQ==